### ISSUE TITLE
EPERM errors on local build

### ISSUE THREAD

**Issue by Mitko-Kerezov** [NativeScript/sidekick-feedback#106]
### Did you verify whether this issue has already been reported here?
Yes - there is one other EPERM issue but it is not related to renaming

### Tell us about the problem.
Whenever trying to execute a local build, Sidekick fails with `EPERM: operation not permitted, rename`.
I suspect the problem may be related to a slow hard drive.

### Which platform(s) does the issue occur on?
Android
Windows

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** 1.0.1-v.2017.11.16.1
- **NativeScript CLI:** 3.3.1
- **CLI extension nativescript-cloud:** 1.0.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Try to build an application for the Android platform locally

### Does this issue happen every time?
Yes

### Send the client logs.
Relevant part of the log:
```
[17-12-06 17:17:46.190] (Error) ab.errorHandler.shell.error - EPERM: operation not permitted, rename 'C:\Users\USERNAME\AppData\Roaming\NativeScriptSidekick\storage\analyticsEnabled.2672589488' -> 'C:\Users\USERNAME\AppData\Roaming\NativeScriptSidekick\storage\analyticsEnabled', Error: EPERM: operation not permitted, rename 'C:\Users\USERNAME\AppData\Roaming\NativeScriptSidekick\storage\analyticsEnabled.2672589488' -> 'C:\Users\USERNAME\AppData\Roaming\NativeScriptSidekick\storage\analyticsEnabled'
    at Object.fs.renameSync (fs.js:776:18)
    at writeFileSync (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at LocalStorage.setItem (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:177:7)
    at Storage.setItem (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\shell\core\storage.js:17:38)
    at AnalyticsController._onAnalyticsEnabled (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\modules\analytics\analytics-controller.js:83:25)
    at SafeSubscriber.disposables.push.api.actionService.getActions.subscribe.args [as _next] (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\modules\analytics\analytics-controller.js:46:41)
    at SafeSubscriber.__tryOrUnsub (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subscriber.js:89:18)
    at MergeAllSubscriber.OuterSubscriber.notifyNext (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\OuterSubscriber.js:19:26)
    at InnerSubscriber._next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\InnerSubscriber.js:23:21)
    at InnerSubscriber.Subscriber.next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subscriber.js:89:18)
    at EndlessReplaySubject.Subject.next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\Subject.js:55:25)
    at EndlessReplaySubject.ReplaySubject.next (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\node_modules\rxjs\ReplaySubject.js:31:31)
    at ActionServiceShell._onOtherThreadActionExecuted (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\app.asar\shared\core\action-service.js:167:38)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (C:\Users\USERNAME\AppData\Local\NativeScriptSidekick\app-1.0.1-v201711161\resources\electron.asar\browser\api\web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```

**Comment by nukuuk** [comment]
Just installed sidekick.  Am getting this error too.
