### ISSUE TITLE
Error clearing Device Console

### ISSUE THREAD

**Issue by rogertthat** [NativeScript/sidekick-feedback#113]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I recently upgraded Sidekick and now whenever I try to clear the console for any device, an error is reported and the console is not cleared.

### Which platform(s) does the issue occur on?
iOS (actual device - iPhone 6s) and Android (emulator - Nexus_5X_API_27_x86)
Windows 10 Home (64-bit)

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.1.0-v.2017.12.21.2
- **NativeScript CLI:** 3.4.0
- **CLI extension nativescript-cloud:** 1.2.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Start SideKick.
2. View an Application.
3. Select Run on Device.
4. Attach a device (emulator or actual device)
5. Click on the "Devices" tab at the bottom right of the screen.
6. Click on the "Console" tab in the middle of the screen.
7. Click on the "Erase" icon to the right.
8. Notice the error will result and the console will not be cleared.

### Does this issue happen every time?
Yes

### Error reported by SideKick
[17-12-27 12:04:53.394] (Error) Source: event handler for "clear-device-log" Message: Trying to set value of property (logData) of frozen object., Error: Source: event handler for "clear-device-log" Message: Trying to set value of property (logData) of frozen object.
    at Object.set (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:5259:23)
    at a._onClearDeviceLog (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:17925:45)
    at Ot.n (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:1189)
    at Ot.e.$emit (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:62362)
    at VueService.emit (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:8371:18)
    at a.onClick (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:10117:40)
    at a.n [as onClick] (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:1177)
    at click (eval at wi (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:52507), <anonymous>:2:979)
    at t (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:7412)
    at HTMLAnchorElement.e._withTask.e._withTask (file:///C:/Users/me/AppData/Local/NativeScriptSidekick/app-1.1.0-v201712212/resources/app.asar/ui/app.js:531:6821)

### Send the client logs.
Gist of logs: https://gist.github.com/rogertthat/162f992208b36239c36b7e3639944ec2

**Comment by ahitrov** [comment]
Hi @rogertthat 

Thank you for reporting this issue. We will provide a fix early next year.
