### ISSUE TITLE
Unexpected timeout at Sidekick startup

### ISSUE THREAD

**Issue by angel-gavrilov** [NativeScript/sidekick-feedback#115]
[18-01-04 14:55:08.215] (Error) Timeout has occurred, TimeoutError: Timeout has occurred
at new TimeoutError (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\util\TimeoutError.js:17:26)
at Observable.timeout (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\operator\timeout.js:22:79)
at InstallPrerequisitesController._installPrerequisites (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\modules\tns-doctor\install-prerequisites-controller.js:87:18)
at ActionServiceShell._actionFactory (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\core\action-service.js:150:38)
at SafeSubscriber.__tryOrUnsub (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\Subscriber.js:238:16)
at SafeSubscriber.next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\Subscriber.js:185:22)
at Subscriber._next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\Subscriber.js:125:26)
at Subscriber.next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\Subscriber.js:89:18)
at MergeAllSubscriber.OuterSubscriber.notifyNext (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\OuterSubscriber.js:19:26)
at InnerSubscriber._next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\InnerSubscriber.js:23:21)
at InnerSubscriber.Subscriber.next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\rxjs\Subscriber.js:89:18)
at _.forEach (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\base\endless-subjects.js:47:29)
at arrayEach (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\lodash\lodash.js:537:11)
at Function.forEach (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\node_modules\lodash\lodash.js:9359:14)
at EndlessReplaySubject.handleSubscriberErrors (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\base\endless-subjects.js:43:7)
at EndlessReplaySubject.onNext (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\base\endless-subjects.js:71:28)
at EndlessReplaySubject.next (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\base\endless-subjects.js:116:16)
at ActionServiceShell._onOtherThreadActionExecuted (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\app.asar\shared\core\action-service.js:180:38)
at emitTwo (events.js:106:13)
at EventEmitter.emit (events.js:194:7)
at WebContents.<anonymous> (C:\Users\1408571\AppData\Local\NativeScriptSidekick\app-1.1.0-v201712212\resources\electron.asar\browser\api\web-contents.js:247:13)
at emitTwo (events.js:106:13)

**Comment by angel-gavrilov** [comment]
There are logs and the screenshots.
![pc](https://user-images.githubusercontent.com/29333581/34575944-456a21c6-f174-11e7-8c9a-a8d9cf4273fd.JPG)
![phone](https://user-images.githubusercontent.com/29333581/34575945-45a5562e-f174-11e7-94e8-b0821427850e.png)

[console_18-01-04_14-49-17.105.zip](https://github.com/NativeScript/sidekick-feedback/files/1604142/console_18-01-04_14-49-17.105.zip)

**Comment by tsvetie** [comment]
Hi @angel-gavrilov,

Could you please explain in greater detail your scenario and the problem you report? I am not quite sure I understand correctly the steps you followed and the result you got. From the log files you attached, I see that you performed two successful cloud builds. I tested the resulting qr code images and I managed to scan both of them successfully. So, I am guessing there is no problem with the images themselves?

**Comment by angel-gavrilov** [comment]
Hi @tsvetie,
If you want I can send you all of the discussion on the Sidekick support chat about this. Te member of the support chat ask me to publish here the logs:

"Hey Angel, I am glad the issue is resolved. However, I'd like to ask you for a favor. That error message you sent me is unexpected. Would you please open a GitHub issue here and attach all the logs from the app (the issue template describes the exact steps). This will help the team to investigate the fix the problem."

**Comment by tsvetie** [comment]
Hey @angel-gavrilov,

I found the original conversation that lead to this issue. Let me explain a bit better the idea of my colleague. Basically, the error that you observed had nothing to do with the QR code or the problem you had to scan it. 

This error is related to the process that you triggered when you started Sidekick - you probably got a message telling you that you do not have NodeJS or NativeScrtipt CLI and these are prerequisites for Sidekick to run. On this screen, you clicked the Install button and this installation timed out so you retried it and the second time, it was successful.

In case I am correct, the error that got my colleague worried was the details for the time out of your first try to install NativeScript CLI. Am I correct in my assumption?

**Comment by teobugslayer** [comment]
I've changed the issue name to match the issue we are tracking. @angel-gavrilov, could you please attach the app logs from %AppData%\NativeScriptSidekick\Logs ?

**Comment by tsvetie** [comment]
Hey @teobugslayer, the logs are already attached in the original post. The information that we need is actually whether my assumption is correct.

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. Please, do not hesitate to reopen it if you still encounter this issue with the latest version of Sidekick.

Thank you!
