### ISSUE TITLE
stuck at loading screen and never open 

### ISSUE THREAD

**Issue by elmissouri16** [NativeScript/sidekick-feedback#116]
this my log file 
[18-01-05 22:26:14.245] (Info) ab.actionsLogger.shell.appVersion - {"name":"NativeScript Sidekick","version":"1.1.1-v.2018.1.4.6"}
[18-01-05 22:26:14.251] (Info) ab.addPage.shell.appFlavor - No value provided
[18-01-05 22:26:14.258] (Info) ab.analytics.shell.analyticsEnabled - No value provided
[18-01-05 22:26:14.270] (Info) ab.analytics.shell.customDimensionIndexes - {"shellVersion":1,"nodeVersion":2,"npmVersion":3,"tnsVersion":4,"accountType":5,"localBuildEnv":6,"dayFromFirstRun":7,"dayFromFirstLogin":8,"sessionId":9,"clientId":10,"timestampPerHit":11,"crossClientId":12,"uiVersion":13}
[18-01-05 22:26:14.274] (Info) ab.analytics.shell.clientId - No value provided
[18-01-05 22:26:14.399] (Info) ab.appContext.shell.appContext - No value provided
[18-01-05 22:26:14.625] (Info) ab.appValidityWatcher.shell.isAppValid - No value provided
[18-01-05 22:26:14.658] (Info) ab.autoUpdate.shell.updates - {"eventName":"checking-for-update","message":"Checking for updates..."}
[18-01-05 22:26:14.754] (Info) ab.buildDeploy.shell.buildConfigChanged - {"platform":null,"buildType":"Cloud Build","buildConfig":"Debug","emulatorDevice":"nexus5","webpack":{"isWebpack":false,"env":{"uglify":true,"snapshot":true}}}
[18-01-05 22:26:14.761] (Info) ab.buildDeploy.shell.isWebpackSupported - No value provided
[18-01-05 22:26:14.851] (Info) ab.certificateStore.shell.isSupported - true
[18-01-05 22:26:14.865] (Info) ab.codeSigning.shell.codeSigningChanged - {"ios":{},"android":{}}
[18-01-05 22:26:14.924] (Info) ab.codeSigning.shell.csrCountries - {"countries":[{"text":"Afghanistan","value":"AF"},{"text":"Albania","value":"AL"},{"text":"Algeria","value":"DZ"},{"text":"American Samoa","value":"AS"},{"text":"Andorra","value":"AD"},{"text":"Angola","value":"AO"},{"text":"Anguilla","value":"AI"},{"text":"Antarctica","value":"AQ"},{"text":"Antigua and Barbuda","value":"AG"},{"text":"Argentina","value":"AR"},{"text":"Armenia","value":"AM"},{"text":"Aruba","value":"AW"},{"text":"Australia","value":"AU"},{"text":"Austria","value":"AT"},{"text":"Azerbaijan","value":"AZ"},{"text":"Bahamas","value":"BS"},{"text":"Bahrain","value":"BH"},{"text":"Bangladesh","value":"BD"},{"text":"Barbados","value":"BB"},{"text":"Belarus","value":"BY"},{"text":"Belgium","value":"BE"},{"text":"Belize","value":"BZ"},{"text":"Benin","value":"BJ"},{"text":"Bermuda","value":"BM"},{"text":"Bhutan","value":"BT"},{"text":"Bolivia","value":"BO"},{"text":"Bosnia and Herzegovina","value":"BA"},{"text":"Botswana","value":"BW"},{"text":"Bouvet Island","value":"BV"},{"text":"Brazil","value":"BR"},{"text":"British Indian Ocean Territory","value":"IO"},{"text":"Brunei","value":"BN"},{"text":"Bulgaria","value":"BG"},{"text":"Burkina Faso","value":"BF"},{"text":"Burundi","value":"BI"},{"text":"Cambodia","value":"KH"},{"text":"Cameroon","value":"CM"},{"text":"Canada","value":"CA"},{"text":"Cape Verde","value":"CV"},{"text":"Cayman Islands","value":"KY"},{"text":"Central African Republic","value":"CF"},{"text":"Chad","value":"TD"},{"text":"Chile","value":"CL"},{"text":"China","value":"CN"},{"text":"Christmas Island","value":"CX"},{"text":"Cocos (Keeling) Islands","value":"CC"},{"text":"Colombia","value":"CO"},{"text":"Comoros","value":"KM"},{"text":"Congo","value":"CG"},{"text":"Congo, The Democratic Republic of the","value":"CD"},{"text":"Cook Islands","value":"CK"},{"text":"Costa Rica","value":"CR"},{"text":"Croatia","value":"HR"},{"text":"Cuba","value":"CU"},{"text":"Cyprus","value":"CY"},{"text":"Czech Republic","value":"CZ"},{"text":"Denmark","value":"DK"},{"text":"Djibouti","value":"DJ"},{"text":"Dominica","value":"DM"},{"text":"Dominican Republic","value":"DO"},{"text":"East Timor","value":"TP"},{"text":"Ecuador","value":"EC"},{"text":"Egypt","value":"EG"},{"text":"El Salvador","value":"SV"},{"text":"Equatorial Guinea","value":"GQ"},{"text":"Eritrea","value":"ER"},{"text":"Estonia","value":"EE"},{"text":"Ethiopia","value":"ET"},{"text":"Falkland Islands","value":"FK"},{"text":"Faroe Islands","value":"FO"},{"text":"Fiji Islands","value":"FJ"},{"text":"Finland","value":"FI"},{"text":"France","value":"FR"},{"text":"French Guiana","value":"GF"},{"text":"French Polynesia","value":"PF"},{"text":"French Southern territories","value":"TF"},{"text":"Gabon","value":"GA"},{"text":"Gambia","value":"GM"},{"text":"Georgia","value":"GE"},{"text":"Germany","value":"DE"},{"text":"Ghana","value":"GH"},{"text":"Gibraltar","value":"GI"},{"text":"Greece","value":"GR"},{"text":"Greenland","value":"GL"},{"text":"Grenada","value":"GD"},{"text":"Guadeloupe","value":"GP"},{"text":"Guam","value":"GU"},{"text":"Guatemala","value":"GT"},{"text":"Guinea","value":"GN"},{"text":"Guinea-Bissau","value":"GW"},{"text":"Guyana","value":"GY"},{"text":"Haiti","value":"HT"},{"text":"Heard Island and McDonald Islands","value":"HM"},{"text":"Holy See (Vatican City State)","value":"VA"},{"text":"Honduras","value":"HN"},{"text":"Hong Kong","value":"HK"},{"text":"Hungary","value":"HU"},{"text":"Iceland","value":"IS"},{"text":"India","value":"IN"},{"text":"Indonesia","value":"ID"},{"text":"Iran","value":"IR"},{"text":"Iraq","value":"IQ"},{"text":"Ireland","value":"IE"},{"text":"Israel","value":"IL"},{"text":"Italy","value":"IT"},{"text":"Ivory Coast","value":"CI"},{"text":"Jamaica","value":"JM"},{"text":"Japan","value":"JP"},{"text":"Jordan","value":"JO"},{"text":"Kazakstan","value":"KZ"},{"text":"Kenya","value":"KE"},{"text":"Kiribati","value":"KI"},{"text":"Kuwait","value":"KW"},{"text":"Kyrgyzstan","value":"KG"},{"text":"Laos","value":"LA"},{"text":"Latvia","value":"LV"},{"text":"Lebanon","value":"LB"},{"text":"Lesotho","value":"LS"},{"text":"Liberia","value":"LR"},{"text":"Libyan Arab Jamahiriya","value":"LY"},{"text":"Liechtenstein","value":"LI"},{"text":"Lithuania","value":"LT"},{"text":"Luxembourg","value":"LU"},{"text":"Macao","value":"MO"},{"text":"Macedonia","value":"MK"},{"text":"Madagascar","value":"MG"},{"text":"Malawi","value":"MW"},{"text":"Malaysia","value":"MY"},{"text":"Maldives","value":"MV"},{"text":"Mali","value":"ML"},{"text":"Malta","value":"MT"},{"text":"Marshall Islands","value":"MH"},{"text":"Martinique","value":"MQ"},{"text":"Mauritania","value":"MR"},{"text":"Mauritius","value":"MU"},{"text":"Mayotte","value":"YT"},{"text":"Mexico","value":"MX"},{"text":"Micronesia, Federated States of","value":"FM"},{"text":"Moldova","value":"MD"},{"text":"Monaco","value":"MC"},{"text":"Mongolia","value":"MN"},{"text":"Montserrat","value":"MS"},{"text":"Morocco","value":"MA"},{"text":"Mozambique","value":"MZ"},{"text":"Myanmar","value":"MM"},{"text":"Namibia","value":"NA"},{"text":"Nauru","value":"NR"},{"text":"Nepal","value":"NP"},{"text":"Netherlands","value":"NL"},{"text":"Netherlands Antilles","value":"AN"},{"text":"New Caledonia","value":"NC"},{"text":"New Zealand","value":"NZ"},{"text":"Nicaragua","value":"NI"},{"text":"Niger","value":"NE"},{"text":"Nigeria","value":"NG"},{"text":"Niue","value":"NU"},{"text":"Norfolk Island","value":"NF"},{"text":"North Korea","value":"KP"},{"text":"Northern Mariana Islands","value":"MP"},{"text":"Norway","value":"NO"},{"text":"Oman","value":"OM"},{"text":"Pakistan","value":"PK"},{"text":"Palau","value":"PW"},{"text":"Palestine","value":"PS"},{"text":"Panama","value":"PA"},{"text":"Papua New Guinea","value":"PG"},{"text":"Paraguay","value":"PY"},{"text":"Peru","value":"PE"},{"text":"Philippines","value":"PH"},{"text":"Pitcairn","value":"PN"},{"text":"Poland","value":"PL"},{"text":"Portugal","value":"PT"},{"text":"Puerto Rico","value":"PR"},{"text":"Qatar","value":"QA"},{"text":"Reunion","value":"RE"},{"text":"Romania","value":"RO"},{"text":"Russian Federation","value":"RU"},{"text":"Rwanda","value":"RW"},{"text":"Saint Helena","value":"SH"},{"text":"Saint Kitts and Nevis","value":"KN"},{"text":"Saint Lucia","value":"LC"},{"text":"Saint Pierre and Miquelon","value":"PM"},{"text":"Saint Vincent and the Grenadines","value":"VC"},{"text":"Samoa","value":"WS"},{"text":"San Marino","value":"SM"},{"text":"Sao Tome and Principe","value":"ST"},{"text":"Saudi Arabia","value":"SA"},{"text":"Senegal","value":"SN"},{"text":"Seychelles","value":"SC"},{"text":"Sierra Leone","value":"SL"},{"text":"Singapore","value":"SG"},{"text":"Slovakia","value":"SK"},{"text":"Slovenia","value":"SI"},{"text":"Solomon Islands","value":"SB"},{"text":"Somalia","value":"SO"},{"text":"South Africa","value":"ZA"},{"text":"South Georgia and the South Sandwich Islands","value":"GS"},{"text":"South Korea","value":"KR"},{"text":"Spain","value":"ES"},{"text":"Sri Lanka","value":"LK"},{"text":"Sudan","value":"SD"},{"text":"Suriname","value":"SR"},{"text":"Svalbard and Jan Mayen","value":"SJ"},{"text":"Swaziland","value":"SZ"},{"text":"Sweden","value":"SE"},{"text":"Switzerland","value":"CH"},{"text":"Syria","value":"SY"},{"text":"Taiwan","value":"TW"},{"text":"Tajikistan","value":"TJ"},{"text":"Tanzania","value":"TZ"},{"text":"Thailand","value":"TH"},{"text":"Togo","value":"TG"},{"text":"Tokelau","value":"TK"},{"text":"Tonga","value":"TO"},{"text":"Trinidad and Tobago","value":"TT"},{"text":"Tunisia","value":"TN"},{"text":"Turkey","value":"TR"},{"text":"Turkmenistan","value":"TM"},{"text":"Turks and Caicos Islands","value":"TC"},{"text":"Tuvalu","value":"TV"},{"text":"Uganda","value":"UG"},{"text":"Ukraine","value":"UA"},{"text":"United Arab Emirates","value":"AE"},{"text":"United Kingdom","value":"GB"},{"text":"United States","value":"US"},{"text":"United States Minor Outlying Islands","value":"UM"},{"text":"Uruguay","value":"UY"},{"text":"Uzbekistan","value":"UZ"},{"text":"Vanuatu","value":"VU"},{"text":"Venezuela","value":"VE"},{"text":"Vietnam","value":"VN"},{"text":"Virgin Islands,British","value":"VG"},{"text":"Virgin Islands,U.S.","value":"VI"},{"text":"Wallis and Futuna","value":"WF"},{"text":"Western Sahara","value":"EH"},{"text":"Yemen","value":"YE"},{"text":"Yugoslavia","value":"YU"},{"text":"Zambia","value":"ZM"},{"text":"Zimbabwe","value":"ZW"}]}
[18-01-05 22:26:14.929] (Info) ab.codeSigning.shell.csrStore - {}
[18-01-05 22:26:14.970] (Info) ab.createApp.shell.lastUsedAppDirectory - {"appDirectory":""}
[18-01-05 22:26:15.906] (Info) ab.proxy.shell.proxySettings - {}
[18-01-05 22:26:15.959] (Info) ab.recentApps.shell.recentAppsListUpdated - {"recentAppsList":[]}
[18-01-05 22:26:15.983] (Info) ab.subscriptions.shell.usageInfo - []
[18-01-05 22:26:15.985] (Info) ab.subscriptions.shell.userAccounts - []
[18-01-05 22:26:46.115] (Info) ab.analytics.ui.setVersion - {"version":"1.1.1-v.2018.1.4.6"}
[18-01-05 22:26:46.120] (Info) ab.buildDeploy.ui.pendingRequests - No value provided
[18-01-05 22:26:46.145] (Info) ab.vueService.ui.routeChanged - {"path":"/recent-apps","query":{}}
[18-01-05 22:26:46.168] (Info) ab.autoUpdate.shell.updates - {"eventName":"update-not-available","message":"No updates available."}
[18-01-05 22:27:33.280] (Info) ab.tnsDoctor.shell.checkDependencies - {"node":{"name":"NodeJS","version":"8.9.0","minVersion":"6.0.0","preferredVersion":"6.11.4","isMet":true,"isAutoFixSupported":false},"npm":{"name":"npm","version":"5.5.1","isMet":true,"isAutoFixSupported":false},"tns":{"name":"NativeScript CLI","version":"3.5.0-2017-12-20-10289","minVersion":"3.4.0","preferredVersion":"latest","isMet":true,"isAutoFixSupported":false}}
[18-01-05 22:27:35.004] (Info) ab.tnsDoctor.shell.checkLocalBuild - {"iOS":{"canExecuteLocalBuild":false,"warnings":[{"warning":"NOTE: You can develop for iOS only on Mac OS X systems.","additionalInformation":"To be able to work with iOS devices and projects, you need Mac OS X Mavericks or later.\r\n","platforms":["iOS"]}]},"Android":{"canExecuteLocalBuild":true,"warnings":[]}}
[18-01-05 22:28:01.958] (Error) ab.childProcessCommunication.shell.cli - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.003] (Error) ab.eula.shell.eulaData - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.007] (Error) ab.errorHandler.shell.error - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.012] (Error) ab.errorHandler.shell.error - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.015] (Error) ab.errorHandler.shell.error - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.018] (Error) ab.errorHandler.shell.error - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.021] (Error) ab.errorHandler.shell.error - Communication with the child process was ended. Errors: module.js:538
    throw err;
    ^

Error: Cannot find module './common/appbuilder/device-log-provider'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Yok.resolveDependency (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:338:13)
    at Yok.resolveByName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:315:31)
    at Yok.resolve (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:262:25)
    at ctor.$inject.args.map.paramName (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:292:29)
    at Array.map (<anonymous>)
    at Yok.resolveConstructor (C:\Users\El\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:287:48)

[18-01-05 22:28:02.122] (Info) ab.connectedDevices.ui.deviceSelected - No value provided
[18-01-05 22:28:02.125] (Info) ab.connectedDevices.ui.devicesListChanged - {}
[18-01-05 22:28:16.021] (Info) ab.autoUpdate.shell.updates - {"eventName":"checking-for-update","message":"Checking for updates..."}
[18-01-05 22:28:16.027] (Info) ab.trayMenu.shell.checkUpdates - {"isAlreadyTracked":false}
[18-01-05 22:28:17.572] (Info) ab.autoUpdate.shell.updates - {"eventName":"update-not-available","message":"No updates available."}

**when i install it its stuck on splash screen i thought is updating or loading some component i give it time to load but its stuck there **

**Comment by tsvetie** [comment]
Hi @elmissouri16,

It seems that there is a problem with your installation of NativeScript CLI. Most probably, you will get an error, if you try to execute one of the following commands in the terminal:

```
tns --version
tns doctor
```
Can you try removing and installing NativeScript CLI to see if this will fix the problem? To do this, execute the following commands:
```
npm remove -g nativescript
npm i -g nativescript
```
or if you prefer to keep using the next version:
```
npm i -g nativescript@next
```

**Comment by elmissouri16** [comment]
@tsvetie  still the same problem I try all
