### ISSUE TITLE
Cloud Build Error

### ISSUE THREAD

**Issue by LorenDorez** [NativeScript/sidekick-feedback#124]
### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem.
When i try to run a Cloud Build is get an error
```
[18-01-29 13:50:56.692] (Info) /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/lib/binding.js:15
[18-01-29 13:50:56.693] (Info) throw new Error(errors.missingBinary());
```

### Which platform(s) does the issue occur on?
Both iOS and Android

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** : 1.2.1-v2018.1.25.3
- **NativeScript CLI:** : 3.4.1
- **CLI extension nativescript-cloud:**: 1.30 
- **CLI extension nativescript-starter-kits:**: 0.3.4 

### Tell us how to recreate the issue in as much detail as possible.
I have an app that builds local with android just fine. When o try to do Cloud build it fails with several errors like the above

### Does this issue happen every time?
YES

### Send the client logs.
```
[18-01-29 13:49:18.354] (Info) NativeScript Sidekick version: 1.2.1-v.2018.1.25.3
[18-01-29 13:49:18.493] (Info) Checking for updates...
[18-01-29 13:49:19.247] (Info) No updates available.
[18-01-29 13:49:19.994] (Info) Dependencies versions: NodeJS: 8.9.4, npm: 5.6.0, NativeScript CLI: 3.4.1.
[18-01-29 13:49:21.833] (Info) Devices service initialized.
[18-01-29 13:49:43.601] (Info) Installed CLI extension nativescript-cloud, version 1.3.0.
[18-01-29 13:49:43.610] (Info) Loaded CLI extension nativescript-cloud, version 1.3.0.
[18-01-29 13:49:43.614] (Info) Loaded CLI extension nativescript-starter-kits, version 0.3.4.
[18-01-29 13:50:02.163] (Info) App with path: F:\GLSS\Clients\Oversii\MobileApps\NativeScript\Patrolman Mobile App was opened.
[18-01-29 13:50:08.394] (Info) Build started.
[18-01-29 13:50:09.656] (Info) Prepare step started.
[18-01-29 13:50:10.468] (Info) Prepare step completed.
[18-01-29 13:50:11.169] (Info) Upload step started.
[18-01-29 13:50:14.230] (Info) Upload step completed.
[18-01-29 13:50:14.668] (Info) Build step started.
[18-01-29 13:50:45.726] (Info) GRADLE_USER_HOME is /opt/docker_shared/Sy8rnGSZGSqy2G8Q4L.gradle
[18-01-29 13:50:45.729] (Info) android Build Tooling revision 2018.01.10.4r
[18-01-29 13:50:45.730] (Info) Build Tooling Hostname 82b8fa8652c6
[18-01-29 13:50:45.732] (Info) App package not specified. Skipping unzip step.
[18-01-29 13:50:47.352] (Info) NativeScript CLI version 3.4.1
[18-01-29 13:50:47.353] (Info) Copying template files...
[18-01-29 13:50:47.354] (Info) Installing  tns-android
[18-01-29 13:50:47.355] (Info)   ◜ Installing tns-android
[18-01-29 13:50:47.356] (Info)   ◠ Installing tns-android
[18-01-29 13:50:47.357] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.830] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.831] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.833] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.834] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.836] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.837] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.838] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.840] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.842] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.843] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.843] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.845] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.846] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.847] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.848] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.850] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.851] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.852] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.853] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.854] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.856] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.857] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.859] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.860] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.861] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.862] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.863] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.864] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.865] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.866] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.867] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.868] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.870] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.871] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.872] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.873] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.874] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.876] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.877] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.879] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.880] (Info) /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp
[18-01-29 13:50:53.882] (Info) ├─┬ nativescript-sqlite-commercial@1.0.0
[18-01-29 13:50:53.884] (Info) │ └── nativescript-sqlite@2.0.1
[18-01-29 13:50:53.885] (Info) └── tns-android@3.4.1
[18-01-29 13:50:53.886] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.887] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.888] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.889] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.891] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.891] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.892] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.893] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.895] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.896] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.896] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.898] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.899] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.901] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.902] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.904] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.908] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.910] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.911] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.912] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.913] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.914] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.915] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.916] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.918] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.920] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.922] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.923] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.924] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.925] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.926] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.927] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.928] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.929] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.930] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.931] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.936] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.937] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.938] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.939] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.940] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.941] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.942] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.943] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.944] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.945] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.946] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.947] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.948] (Info)   ◠ Installing tns-android
[18-01-29 13:50:53.949] (Info)   ◝ Installing tns-android
[18-01-29 13:50:53.950] (Info)   ◞ Installing tns-android
[18-01-29 13:50:53.952] (Info)   ◡ Installing tns-android
[18-01-29 13:50:53.953] (Info)   ◟ Installing tns-android
[18-01-29 13:50:53.954] (Info)   ◜ Installing tns-android
[18-01-29 13:50:53.955] (Info)   ◠ Installing tns-android
[18-01-29 13:50:54.786] (Info)   ◝ Installing tns-android
[18-01-29 13:50:54.788] (Info)   ◞ Installing tns-android
[18-01-29 13:50:54.790] (Info)   ◡ Installing tns-android
[18-01-29 13:50:54.792] (Info)   ◟ Installing tns-android
[18-01-29 13:50:54.793] (Info)   ◜ Installing tns-android
[18-01-29 13:50:54.794] (Info)   ◠ Installing tns-android
[18-01-29 13:50:54.795] (Info)   ◝ Installing tns-android
[18-01-29 13:50:54.797] (Info)   ◞ Installing tns-android
[18-01-29 13:50:54.798] (Info) \u001b[2K
[18-01-29 13:50:54.799] (Info) Project successfully created.
[18-01-29 13:50:54.800] (Info) Executing before-prepare hook from /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/hooks/before-prepare/nativescript-dev-sass.js
[18-01-29 13:50:54.802] (Info) Found peer node-sass
[18-01-29 13:50:56.692] (Info) /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/lib/binding.js:15
[18-01-29 13:50:56.693] (Info) throw new Error(errors.missingBinary());
[18-01-29 13:50:56.695] (Info) ^
[18-01-29 13:50:56.696] (Info) Error: Missing binding /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/vendor/linux-x64-48/binding.node
[18-01-29 13:50:56.697] (Info) Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x
[18-01-29 13:50:56.698] (Info) Found bindings for the following environments:
[18-01-29 13:50:56.699] (Info) - Windows 64-bit with Node.js 8.x
[18-01-29 13:50:56.700] (Info) This usually happens because your environment has changed since running `npm install`.
[18-01-29 13:50:56.702] (Info) Run `npm rebuild node-sass --force` to build the binding for your current environment.
[18-01-29 13:50:56.702] (Info) at module.exports (/mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/lib/binding.js:15:13)
[18-01-29 13:50:56.706] (Info) at Object.<anonymous> (/mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/lib/index.js:14:35)
[18-01-29 13:50:56.707] (Info) at Module._compile (module.js:556:32)
[18-01-29 13:50:56.708] (Info) at Object.Module._extensions..js (module.js:565:10)
[18-01-29 13:50:56.709] (Info) at Module.load (module.js:473:32)
[18-01-29 13:50:56.710] (Info) at tryModuleLoad (module.js:432:12)
[18-01-29 13:50:56.711] (Info) at Function.Module._load (module.js:424:3)
[18-01-29 13:50:56.712] (Info) at Module.require (module.js:483:17)
[18-01-29 13:50:56.713] (Info) at require (internal/module.js:20:19)
[18-01-29 13:50:56.714] (Info) at Object.<anonymous> (/mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/bin/node-sass:11:10)
[18-01-29 13:50:56.715] (Info) SASS compiler failed with exit code 1
[18-01-29 13:50:56.716] (Info) Error: Missing binding /mnt/storage/builds/_/9326e170c89f45bb79497545babe0314f24e8dd3/3.4.1/PatrolmanMobileApp/node_modules/node-sass/vendor/linux-x64-48/binding.node
[18-01-29 13:50:56.717] (Info) SASS compiler failed with exit code 1
[18-01-29 13:50:56.718] (Info) bc_Sy8rnGSZGSqy2G8Q4L
[18-01-29 13:50:56.722] (Error) Build failed.

```

**Comment by LorenDorez** [comment]
After several attempts it finally built. Leaving open in case there was an issue that you can track on the build machines

**Comment by tsvetie** [comment]
Hey @LorenDorez,

I have an assumption and it would be great if you can verify if it is correct. Can you send me the _.gitignore_ file from the root folder of your application? You should have the the node_modules folder in it. In case you do not, this could be the cause for the problem you have.
