### ISSUE TITLE
Windows 10 - Communication with the child process has ended

### ISSUE THREAD

**Issue by emmanuelchucks** [NativeScript/sidekick-feedback#127]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
After installing and trying to open Sidekick, I get a notification, "Communication with the child process was ended. Errors: assert.js:42 throw new errors.AssertionError({"

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

NativeScript Sidekick: 1.3.0-v2018.2.2.2
NativeScript CLI: 3.4.2

### Tell us how to recreate the issue in as much detail as possible.
Start the application ..
Loading screen loads for a while, window notification pops up with error "Communication with the child process was ended. Errors: assert.js:42 throw new errors.AssertionError({" and loading screen keeps loading forever

### Does this issue happen every time?
Yes

### Send the client logs.
No Logs folders found in: %AppData%\NativeScriptSidekick\

Screnshot:
![capture](https://user-images.githubusercontent.com/31349069/35775277-b0bd7fce-097d-11e8-84f0-6f438112da99.PNG)

**Comment by tsvetie** [comment]
@emmanuelchucks did you by any chance use yarn to install NativeScript CLI? The issue you are reporting sounds like one of our previous issues (#70). If this is the case, please remove it and install it with npm.

On a side note, it is a bit strange that you have no log files - the code that seems to fail should generate log files. Could you check the folder again?

**Comment by emmanuelchucks** [comment]
@tsvetie Using npm instead of Yarn actually worked for me. Thanks a lot for your help.

**Comment by McNairy** [comment]
Uninstallling via yarn and reinstalling with npm worked for me. Here are my logs from when the installed failed.

Using NativeScript CLI located in null

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: missing path
    at Module.require (module.js:585:3)
    at require (internal/module.js:11:18)
    at CLIProvider._requireCLI (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\cli-provider.js:38:20)
    at CLIProvider._getCLIInitializePromise (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\cli-provider.js:31:30)
    at CLIProvider.getInitializedCLI._.memoize (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\cli-provider.js:17:59)
    at CLIProvider.memoized [as getInitializedCLI] (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\node_modules\lodash\lodash.js:10566:27)
    at CLIBuildService.requireCLI (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\base\cli-service-base.js:8:48)
    at CLIBuildService._bindToEvents (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\services\cli-build-service.js:253:18)
    at new CLIBuildService (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\cli\services\cli-build-service.js:11:18)
    at _.forEach (C:\Users\micha\AppData\Local\NativeScriptSidekick\app-1.5.0-v20182153\resources\app.asar.unpacked\shared\child-process\child-services-loader.js:19:31)
