### ISSUE TITLE
Can't accept Terms of Service in Windows 10

### ISSUE THREAD

**Issue by r-dunbar** [NativeScript/sidekick-feedback#131]
## Please, provide the details below:
Sidekick app is stuck on Terms of Service page and will not let me click the 'Continue' button, even after checking 'I agree'. This in effect prevents me from ever opening the sidekick app.

### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
After installing the Sidekick app on Windows, I'm unable to ever open it as I'm stuck on the 'Terms of Service' popup. Even after I click 'I agree', the 'Continue' button lights up but still behaves as if it's still disabled.

**UPDATE**
I managed to figure out that the certificate issue was caused by our corporate firewall. In troubleshooting this issue I also found I was able to replicate this bug by simply being offline when opening Sidekick for the first time. Can I please suggest updating the UX so that the user is notified of any connection problems in a visual way as just having the button do nothing is not a great experience.

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** Version: 1.5.0-v.2018.2.15.3 (latest)
- **NativeScript CLI:** 3.4.2
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Install nativescript cli using 'npm install nativescript -g'
2.Download and install Sidekick from https://www.nativescript.org/nativescript-sidekick

### Does this issue happen every time?
Yes

### Send the client logs.
An extract of the logs/main file tells me it might be something to do with a certificate. Can anybody shed some more light on this / suggest a solution? If this is the problem, at the very least I feel the UX could be improved by giving an indication there was an error.

(Info) ab.analytics.shell.analyticsEnabled - No value provided
[18-02-23 09:45:39.763] (Info) ab.eula.shell.eulaData - {"url":"https://www.nativescript.org/nativescript-sidekick/eula","shouldAcceptEula":true}
[18-02-23 09:46:21.063] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:22.689] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:22.977] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:23.240] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:23.504] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:23.770] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:24.010] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:24.052] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:24.234] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:24.457] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:25.941] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:25.947] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:25.959] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:25.968] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:25.976] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:25.984] (Error) ab.eula.shell.acceptEula - self signed certificate in certificate chain, Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
[18-02-23 09:46:27.673] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:27.849] (Info) ab.eula.ui.accept - No value provided
[18-02-23 09:46:28.547] (Info) ab.userAgreement.ui.quit - {"eula":{"accepted":true}}

**Comment by bundyo** [comment]
You seem to pass your traffic through a some kind of proxy that uses a self-signed certificate. This is a security issue (open to MitM attacks) and Sidekick throws an error. This error should show a notification in Windows 10 (in one of the screen corners) and write it down in the notification area in the taskbar (if the Windows 10 version is newer).

To resolve the error check why you have a self-signed certificate in your certificate chain - might be a forgotten Fiddler network debugger, some other network software like a firewall or even malware of some kind. If you're behind a system-wide firewall, you might want to ask your system administrator.

**UPDATE**: I saw later that you were behind company firewall, but I'm leaving the above text as a explanation if someone else hits this issue.

As for offline - currently Sidekick doesn't support working off the grid as most of its functionality is network-based (Create App for instance downloads the templates from Internet, Cloud Builds and Add Page too. Even local builds need Internet to run npm install before passing the build to the SDK.

I'm closing the issue, let me know if I missed something.

**Comment by r-dunbar** [comment]
Thanks for the help in debugging this, I've managed to get around the issue for now by disabling the corporate proxy. I still think this is a UX issue though, as there are no visual indications of any error such as you mention. The only sidekick window that is open is the small Terms of Service modal which does not show any indication of any error, other than the Continue button not working.

**Comment by bundyo** [comment]
Thanks, we will think of a way to warn users if Internet connection is missing.

Meanwhile we released a new version (1.5.1), which fixes the not clickable Terms of Service link (along with several other fixes).

**Comment by Peperud** [comment]
@bundyo 
Corporate firewall terminating SSL connection is very common nowadays. The firewall/proxy will terminate the SSL, inspect the traffic, then issue a certificate, matching the requested domain, and establish connection from the proxy to the user with this certificate.

Usually the measure is applied by pushing the root certificate of the (local) signing authority to the users machines. Most programs use Windows cert store and will experience no issues.
Some (java, firefox, npm, git etc.) however do not. They do use some other cert storage and the signing cert can either be added there or they have an option to ignore ssl errors.

The question then is what storage Sidekick uses and can it be updated?

**Comment by charles2359** [comment]
@ivanovit I am following up on @Peperud last comment about corporate firewall terminating ssl connection. Is there any way we can add our signing cert so this error can be resolved? If you expect us in corporate settings to develop behind firewall/proxy then we will need a way to do this. Thank you.

**Comment by iameduardod** [comment]
@ivanovit any update? I am getting this error
