### ISSUE TITLE
Error: SASS compiler failed with exit code 1: Run->Build and Run ->Run on Device

### ISSUE THREAD

**Issue by In-the-Black-Games** [NativeScript/sidekick-feedback#147]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I run a build either in regular build or on a device I get the following message everytime and I cannot complete the local build. This is the error message: Error detected during LiveSync on 87a2debc for C:\Users\VibeFamily\Documents\Danielle\Force_Positive. Error: SASS compiler failed with exit code 1

### Which platform(s) does the issue occur on?
Android
Windows

### Provide the following version numbers that the issue occurs with:
Version: 1.7.1-v.2018.3.16.2 (latest)
- **NativeScript Sidekick:** 

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application ..
2. View App
3. Click on Run, then Build. Select platform (Android), select local build and Debug
4. Select Build -> Then error occurs

1. Start the application ..
2. View App
3. Click on Run, then Run on Device. Select device, select local build and Debug
4. Select Run on Device -> Then error occurs

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

Run on Device Log (Local Build/Debug):
[18-03-21 09:57:42.586] Build started.
[18-03-21 09:57:50.150] (CLI) Executing before-prepare hook from C:\Users\VibeFamily\Documents\Danielle\Force_Positive\hooks\before-prepare\nativescript-dev-sass.js
[18-03-21 09:57:50.162] (CLI) Found peer node-sass
[18-03-21 09:57:51.201] (CLI) C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15
[18-03-21 09:57:51.201] (CLI)       throw new Error(errors.missingBinary());
[18-03-21 09:57:51.201] (CLI)       ^
[18-03-21 09:57:51.201] (CLI) Error: Missing binding C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\vendor\win32-x64-57\binding.node
[18-03-21 09:57:51.201] (CLI) Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x
[18-03-21 09:57:51.201] (CLI) Found bindings for the following environments:
[18-03-21 09:57:51.201] (CLI)   - Windows 64-bit with Node.js 6.x
[18-03-21 09:57:51.201] (CLI) This usually happens because your environment has changed since running `npm install`.
[18-03-21 09:57:51.201] (CLI) Run `npm rebuild node-sass --force` to build the binding for your current environment.
[18-03-21 09:57:51.201] (CLI)     at module.exports (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15:13)
[18-03-21 09:57:51.201] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\index.js:14:35)
[18-03-21 09:57:51.201] (CLI)     at Module._compile (module.js:652:30)
[18-03-21 09:57:51.201] (CLI)     at Object.Module._extensions..js (module.js:663:10)
[18-03-21 09:57:51.201] (CLI)     at Module.load (module.js:565:32)
[18-03-21 09:57:51.201] (CLI)     at tryModuleLoad (module.js:505:12)
[18-03-21 09:57:51.201] (CLI)     at Function.Module._load (module.js:497:3)
[18-03-21 09:57:51.201] (CLI)     at Module.require (module.js:596:17)
[18-03-21 09:57:51.201] (CLI)     at require (internal/module.js:11:18)
[18-03-21 09:57:51.201] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\bin\node-sass:10:10)
[18-03-21 09:57:51.251] (CLI) Unable to apply changes on device: 87a2debc. Error is: SASS compiler failed with exit code 1.
[18-03-21 09:57:51.261] Error detected during LiveSync on 87a2debc for C:\Users\VibeFamily\Documents\Danielle\Force_Positive. Error: SASS compiler failed with exit code 1
[18-03-21 09:57:51.275] (CLI) Executing after-watch hook from C:\Users\VibeFamily\Documents\Danielle\Force_Positive\hooks\after-watch\nativescript-dev-sass.js
[18-03-21 09:57:51.289] Stopped LiveSync on 87a2debc for C:\Users\VibeFamily\Documents\Danielle\Force_Positive.
[18-03-21 10:00:03.306] Build started.
[18-03-21 10:00:11.231] (CLI) Executing before-prepare hook from C:\Users\VibeFamily\Documents\Danielle\Force_Positive\hooks\before-prepare\nativescript-dev-sass.js
[18-03-21 10:00:11.240] (CLI) Found peer node-sass
[18-03-21 10:00:12.225] (CLI) C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15
[18-03-21 10:00:12.225] (CLI)       throw new Error(errors.missingBinary());
[18-03-21 10:00:12.225] (CLI)       ^
[18-03-21 10:00:12.225] (CLI) Error: Missing binding C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\vendor\win32-x64-57\binding.node
[18-03-21 10:00:12.225] (CLI) Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x
[18-03-21 10:00:12.225] (CLI) Found bindings for the following environments:
[18-03-21 10:00:12.225] (CLI)   - Windows 64-bit with Node.js 6.x
[18-03-21 10:00:12.225] (CLI) This usually happens because your environment has changed since running `npm install`.
[18-03-21 10:00:12.225] (CLI) Run `npm rebuild node-sass --force` to build the binding for your current environment.
[18-03-21 10:00:12.225] (CLI)     at module.exports (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15:13)
[18-03-21 10:00:12.225] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\index.js:14:35)
[18-03-21 10:00:12.225] (CLI)     at Module._compile (module.js:652:30)
[18-03-21 10:00:12.225] (CLI)     at Object.Module._extensions..js (module.js:663:10)
[18-03-21 10:00:12.225] (CLI)     at Module.load (module.js:565:32)
[18-03-21 10:00:12.225] (CLI)     at tryModuleLoad (module.js:505:12)
[18-03-21 10:00:12.225] (CLI)     at Function.Module._load (module.js:497:3)
[18-03-21 10:00:12.225] (CLI)     at Module.require (module.js:596:17)
[18-03-21 10:00:12.225] (CLI)     at require (internal/module.js:11:18)
[18-03-21 10:00:12.225] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\bin\node-sass:10:10)
[18-03-21 10:00:12.235] (CLI) Unable to apply changes on device: 87a2debc. Error is: SASS compiler failed with exit code 1.
[18-03-21 10:00:12.245] Error detected during LiveSync on 87a2debc for C:\Users\VibeFamily\Documents\Danielle\Force_Positive. Error: SASS compiler failed with exit code 1
[18-03-21 10:00:12.272] (CLI) Executing after-watch hook from C:\Users\VibeFamily\Documents\Danielle\Force_Positive\hooks\after-watch\nativescript-dev-sass.js
[18-03-21 10:00:12.285] Stopped LiveSync on 87a2debc for C:\Users\VibeFamily\Documents\Danielle\Force_Positive.

**Run Build (Target Platform - Local Build/Debug) Log:**
[18-03-21 10:01:16.728] Build started.
[18-03-21 10:01:24.366] (CLI) Executing before-prepare hook from C:\Users\VibeFamily\Documents\Danielle\Force_Positive\hooks\before-prepare\nativescript-dev-sass.js
[18-03-21 10:01:24.366] (CLI) Found peer node-sass
[18-03-21 10:01:25.528] (CLI) C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15
[18-03-21 10:01:25.528] (CLI)       throw new Error(errors.missingBinary());
[18-03-21 10:01:25.528] (CLI)       ^
[18-03-21 10:01:25.528] (CLI) Error: Missing binding C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\vendor\win32-x64-57\binding.node
[18-03-21 10:01:25.528] (CLI) Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x
[18-03-21 10:01:25.528] (CLI) Found bindings for the following environments:
[18-03-21 10:01:25.528] (CLI)   - Windows 64-bit with Node.js 6.x
[18-03-21 10:01:25.528] (CLI) This usually happens because your environment has changed since running `npm install`.
[18-03-21 10:01:25.528] (CLI) Run `npm rebuild node-sass --force` to build the binding for your current environment.
[18-03-21 10:01:25.528] (CLI)     at module.exports (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\binding.js:15:13)
[18-03-21 10:01:25.528] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\lib\index.js:14:35)
[18-03-21 10:01:25.528] (CLI)     at Module._compile (module.js:652:30)
[18-03-21 10:01:25.528] (CLI)     at Object.Module._extensions..js (module.js:663:10)
[18-03-21 10:01:25.528] (CLI)     at Module.load (module.js:565:32)
[18-03-21 10:01:25.528] (CLI)     at tryModuleLoad (module.js:505:12)
[18-03-21 10:01:25.528] (CLI)     at Function.Module._load (module.js:497:3)
[18-03-21 10:01:25.528] (CLI)     at Module.require (module.js:596:17)
[18-03-21 10:01:25.528] (CLI)     at require (internal/module.js:11:18)
[18-03-21 10:01:25.528] (CLI)     at Object.<anonymous> (C:\Users\VibeFamily\Documents\Danielle\Force_Positive\node_modules\node-sass\bin\node-sass:10:10)
[18-03-21 10:01:25.556] Build failed. SASS compiler failed with exit code 1

**Comment by In-the-Black-Games** [comment]
I was able to get the issue fixed. I deleted the Node_Modules and the platforms folders from the from the Projects folder (the main folder where the Apps files will be located).

I then re-ran the app (run -> build and run -> run on device) and the build completed with no errors.
