### ISSUE TITLE
iOS Simulator and Sidekick can't work together

### ISSUE THREAD

**Issue by brianha** [NativeScript/sidekick-feedback#150]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
I basically can not have my iOS simulator and sidekick running at the same time. I can start up sidekick first, could build and so on without errors.

If I start the simulator thru Xcode after I start sidekick  I get an error in Sidekick: 

[18-03-24 16:57:34.241] (CLI) /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/errors.js:5
    throw new Error(util.format.apply(null, args));
    ^
Error: Could not find device section. null
    at Object.fail (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/errors.js:5:11)
    at Simctl.getDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:57:20)
    at XCodeSimctlSimulator.getBootedDevice (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-xcode-simctl.js:166:35)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js:18:60)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

### Which platform(s) does the issue occur on?
IOS, MaxOS. Sidekick 1.7.1. Xcode 9.2.

### Does this issue happen every time?
Yes

I have tried to uninstall and reinstall but no luck. I don't think there is that much info around to help if the 3 step sidekick installation guide doesn't just work. :(  I am new to Mac as well and bought this mac just to able to use Sidekick for nativescript actually, so I need it working (can't develop iOS on a PC with sidekick yet as far as I know)

I hope some of you people can help me try to find my issue. I appreciate any help.

Best regards
Brian

**Comment by SP1966** [comment]
I'm having the same issue, unfortunately I haven't accidentally fixed mine! 😀
