### ISSUE TITLE
"Could not find developer disk image" iOS 11.3 Cloud Build

### ISSUE THREAD

**Issue by kjlaw89** [NativeScript/sidekick-feedback#159]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Build fully completes and installs on the phone but is unable to launch app. The error message "Could not find developer disk image" is displayed:

`[18-04-04 23:36:48.676] Could not find developer disk image, Error: Could not find developer disk image
    at DevicesService.<anonymous> (C:\Users\X1 laptop\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:282:38)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\X1 laptop\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:11:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 DEVICES 2  OUTPUT 9`

### Which platform(s) does the issue occur on?
iOS 11.3
Windows 10

### Provide the following version numbers that the issue occurs with:
- **NativeScript Sidekick:** 1.8.2-v.2018.3.30.1 (latest)
- **NativeScript CLI:** 3.4.3
- **CLI extension nativescript-cloud:** 1.8.0
- **CLI extension nativescript-starter-kits:** 0.3.4 

### Tell us how to recreate the issue in as much detail as possible.
Perform iOS Cloud build in debug mode. Error message will occur shortly after "Refreshing application..." begins.

### Does this issue happen every time?
Yes

### Send the client logs.
Relevant details:

`[18-04-04 23:36:41.732] (CLI) Refreshing application...
[18-04-04 23:36:43.250] (CLI) Error while trying to start application org.nativescript.Cleanup on device 44e1d64fdc925849ca3e93ea97df93171be2f2e1. Error is: Could not find developer disk image
[18-04-04 23:36:43.250] (CLI) Unable to start application org.nativescript.Cleanup on device 44e1d64fdc925849ca3e93ea97df93171be2f2e1. Try starting it manually.
[18-04-04 23:36:43.282] (CLI) Successfully synced application org.nativescript.Cleanup on device 44e1d64fdc925849ca3e93ea97df93171be2f2e1.
[18-04-04 23:36:47.695] (CLI) Starting...
[18-04-04 23:36:48.676] Could not find developer disk image, Error: Could not find developer disk image
    at DevicesService.<anonymous> (C:\Users\X1 laptop\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:282:38)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\X1 laptop\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:11:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
 
From what I researched on the error message, it looks like Xcode needs to be updated at the server level for the newer iOS.

**Comment by ventsislav-georgiev** [comment]
@kjlaw89 This is expected and we cannot solve it by updating code on the server. The issue is that in order to be able to launch an app on iOS device, the device needs to have a mounted developer disk image. The developer disk images are distributed with XCode on Mac and are not available on Windows. As the error message says you need to start the app manually on the device.

**Comment by kjlaw89** [comment]
Ah, I was attributing it to my poorly timed update to iOS 11.3 last night. So it's not possible to do realtime debugging on Windows, or is just a limitation of automatically starting the app? My issue is that I compiled and app, but it just closes immediately when I start it and provides no information about why it closed.  I'll have to keep messing around then to see if I can figure something out.

**Comment by ventsislav-georgiev** [comment]
Realtime debugging works. This is just a limitation of automatically starting the app. As for the crash on application start, check the device log, it should contain more information:
Devices:
![image](https://user-images.githubusercontent.com/5616486/38410602-b1571b58-398d-11e8-9801-e8b84f8d24eb.png)
Console:
![image](https://user-images.githubusercontent.com/5616486/38410621-bd3dd75e-398d-11e8-92cc-a3267f76653b.png)

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. If you are still experiencing the reported behavior with the latest version of Sidekick and would like us to investigate it further, please feel free to reopen it.
