### ISSUE TITLE
iOS Cloud Build Fails - Get Tracing?

### ISSUE THREAD

**Issue by vtjon** [NativeScript/sidekick-feedback#162]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
IOS Cloud Build Failed but no details on why

### Which platform(s) does the issue occur on?
IOS 3.4.1

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

### Tell us how to recreate the issue in as much detail as possible.
This app does build on a Mac but I can't see any details on why the cloud build failed. 

### Does this issue happen every time?
Yes

### Send the client logs.
Last bit of the logs:
```
▸ Building Pods/MNFloatingActionButton-MNFloatingActionButton [Debug]
▸ Check Dependencies
▸ Processing ResourceBundle-MNFloatingActionButton-Info.plist
▸ Touching MNFloatingActionButton.bundle
▸ Building Pods/ColorArt [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling ColorArt-dummy.m
▸ Compiling SLColorArt.m
▸ Compiling UIImage+ColorArt.m
▸ Compiling UIImage+Scale.m
▸ Compiling ColorArt_vers.c
▸ Compiling ColorArt-dummy.m
▸ Compiling SLColorArt.m
▸ Compiling UIImage+ColorArt.m
▸ Compiling UIImage+Scale.m
▸ Compiling ColorArt_vers.c
▸ Linking ColorArt
▸ Linking ColorArt
▸ Copying ColorArt-umbrella.h
▸ Copying SLColorArt.h
▸ Copying UIImage+ColorArt.h
▸ Copying UIImage+Scale.h
▸ Touching ColorArt.framework
▸ Building Pods/HockeySDK-Source-HockeySDKResources [Debug]
▸ Check Dependencies
▸ Processing ResourceBundle-HockeySDKResour


[18-04-06 11:14:22.598] (Info) ab.childProcessCommunication.shell.cliStdout - ur


[18-04-06 11:14:48.097] (Error) ab.buildDeploy.shell.build - Build failed., Error: Build failed.
    at CloudBuildService.<anonymous> (C:\Users\jaust\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-service.js:60:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jaust\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 Dump: {"platform":"iOS","buildConfig":"Debug","buildType":"Cloud Build","isClean":true,"useSharedCloud":false,"webpack":{"isWebpack":false,"env":{"aot":true,"snapshot":true,"uglify":true}},"devicesCount":0}
 Output dump: {"buildId":"64cd5e64-73cd-4a26-be3b-aa45ce7838ee"}
[18-04-06 11:14:48.184] (Info) ab.buildDeploy.ui.pendingRequests - No value provided
[18-04-06 11:22:12.398] (Info) ab.subscriptions.ui.requestUsageInfo - No value provided
[18-04-06 11:22:45.998] (Info) ab.fileSystemWatcher.shell.change - C:\src\FirefighterConnect\.git\FETCH_HEAD
[18-04-06 11:22:48.678] (Info) ab.fileSystemWatcher.shell.change - C:\src\FirefighterConnect\.git\FETCH_HEAD
[18-04-06 11:25:53.661] (Info) ab.menu.shell.openHelpLink - {"isAlreadyTracked":false,"actionId":"ab.gettingStarted.ui.openNativeScriptStackOverflow"}
[18-04-06 11:26:00.910] (Info) ab.menu.shell.showLogs - {"isAlreadyTracked":false}

```

**Comment by ahitrov** [comment]
Hi @vtjon ,

Can you give us the exact version strings for

NativeScript Sidekick:
NativeScript CLI:
CLI extension nativescript-cloud:
CLI extension nativescript-starter-kits:

We'd also need the full log file.

Cheers

**Comment by ggarabedian** [comment]
I’m closing this issue because it has been inactive for several months. If you are still experiencing such problems with the latest version of Sidekick and would like us to investigate it further, please feel free to reopen it.
