### ISSUE TITLE
iOS Auto Generate Provisioning Profile and Certificate ERROR: Invalid URI 

### ISSUE THREAD

**Issue by obiwankenoobi** [NativeScript/sidekick-feedback#170]
### Did you verify whether this issue has already been reported here?
_Yes/

### Tell us about the problem
 when I try to run app on device using
iOS Auto Generate Provisioning Profile and Certificate I get an error :
`Invalid URI "N2EXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkODcx/provision.mobileprovision"`

### Which platform(s) does the issue occur on?
MACOS High Sierra
iphone 6S plus ios 11
 
### Provide the following version numbers that the issue occurs with:

NativeScript Sidekick Desktop
Version: 1.9.0-v.2018.4.11.4 (latest)
NativeScript CLI version: 4.0.0
CLI extension nativescript-cloud version: 1.9.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start the application 
Run > 
Run on device > 
Manage iOS Provisioning and Certificates > 
iOS Auto Generate Provisioning Profile and Certificate >
*set apple details >
Auto Generate>
> ERROR: `Auto Generation Failed Invalid URI "N2EXXXXXXXXXXXXXXXXXXXXXXXXXXXXXkODcx/provision.mobileprovision"`

### Does this issue happen every time?
_Yes/

log:
```
[18-04-19 14:47:09.669] (Info) ab.childProcessCommunication.shell.cliStdout - Starting generation of iOS certificate and provision files.
[18-04-19 14:47:18.780] (Info) ab.childProcessCommunication.shell.cliStdout - Finished generation of iOS certificate and provision files successfully. Downloading result...


[18-04-19 14:47:18.785] (Error) ab.codeSigning.shell.generateiOSCodeSignFiles - Invalid URI "OWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNmU1YzMz/cert.p12", Error: Invalid URI "OWXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNmU1YzMz/cert.p12"
    at Request.init (/usr/local/lib/node_modules/nativescript/node_modules/request/request.js:276:31)
    at new Request (/usr/local/lib/node_modules/nativescript/node_modules/request/request.js:130:8)
    at request (/usr/local/lib/node_modules/nativescript/node_modules/request/index.js:54:10)
    at Promise (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:88:36)
    at new Promise (<anonymous>)
    at HttpClient.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:71:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by house-md** [comment]
I am having the same problem with windows and osx version.

**Comment by HunterTKingsley** [comment]
I've been getting this same issue since Sunday. Windows 10. Latest version of Sidekick. Would not re-deploy when I started development on Sunday. Tried re-generate and it fails every time.

**Comment by tjvantoll** [comment]
@nadyaA It worked for me! Thanks for the quick fix.

Unfortunately though my build failed after using the generated cert and provisioning profile with this error—https://gist.github.com/tjvantoll/28ba1a0643e2a8c073de9d5307d66d84. Do you think this is related, or should I file a separate issue?

**Comment by ventsislav-georgiev** [comment]
@tjvantoll the failed build does not seem related. Could you try to running the build using the **Clean** option and see if the issue persists.

**Comment by kono-paku** [comment]
@nadyaA I have also checked out that it works fine. Deeply appreciate to nadyaA.

**Comment by tjvantoll** [comment]
@ventsislav-georgiev It worked with a Clean build. Thanks again all, this is working great now!
