### ISSUE TITLE
iOS certificate/provisioning profile auto generation fails with invalid URI

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/sidekick-feedback#174]
### Did you verify whether this issue has already been reported here?
Yes, this is similar to https://github.com/NativeScript/sidekick-feedback/issues/92, but I’m getting a different error so I decided to create a new issue.

### Tell us about the problem
When I try to automatically generate a provisioning profile and certificate for my apps I get the following error.

![screen shot 2018-04-20 at 5 07 01 pm](https://user-images.githubusercontent.com/544280/39073865-518f8a58-44bd-11e8-87dd-699a45ca894d.png)

I’m using a newly created iOS developer account and a newly created app. (It’s a throwaway account so I can provide you with the credentials privately if you’d like to help recreate this.)

Here’s the full error that appears in the log:

```
[18-04-20 17:06:23.409] Invalid URI "MTg5ODc5M2ItZWZmNi00ODQ5LTY2MTItZWQ2ZTIxMjZhNzY0/cert.p12", Error: Invalid URI "MTg5ODc5M2ItZWZmNi00ODQ5LTY2MTItZWQ2ZTIxMjZhNzY0/cert.p12"
    at Request.init (/usr/local/lib/node_modules/nativescript/node_modules/request/request.js:276:31)
    at new Request (/usr/local/lib/node_modules/nativescript/node_modules/request/request.js:130:8)
    at request (/usr/local/lib/node_modules/nativescript/node_modules/request/index.js:54:10)
    at Promise (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:88:36)
    at new Promise (<anonymous>)
    at HttpClient.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:71:28)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/nativescript/lib/common/http-client.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Which platform(s) does the issue occur on?
iOS and macOS

### Provide the following version numbers that the issue occurs with:

* Version: 1.9.0-v.2018.4.11.4 (latest)
* NativeScript CLI version: 4.0.0
* CLI extension nativescript-cloud version: 1.9.0
* CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible

1. Start Sidekick and create a new app (existing apps are probably fine too)
2. Click the “Run on Device” menu option.
3. Plug in an iOS device via USB.
4. Click the cog to configure certificates and provisioning profiles.
5. Click the “Auto Generate” button.
6. Type in the credentials of a free iOS developer account and click submit.

### Does this issue happen every time?
Yes

### Send the client logs
Log—https://gist.github.com/tjvantoll/adc91c1cf9febd66d371c675852c27bb (scroll to the bottom for the relevant stuff)

**Comment by HunterTKingsley** [comment]
I'm getting the same error. Auto Generation Failed

Invalid URI "NDczMTFmZmMtMDQ0ZC00MjkwLTUwNDgtMjNiNTYyNDU3NGRk/provision.mobileprovision". This was an existing app and I was successfully debugging it.

**Comment by ventsislav-georgiev** [comment]
duplicated: https://github.com/NativeScript/sidekick-feedback/issues/170
