### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by fthuin** [NativeScript/sidekick-feedback#183]
### Did you verify whether this issue has already been reported here?
Yes, Github can't find the stack trace.

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

There is an error randomly showing in the console.

### Which platform(s) does the issue occur on?
macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop** 

Version: 1.9.1-v.2018.4.23.1 (latest)
NativeScript CLI version: 4.0.0
CLI extension nativescript-cloud version: 1.9.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Don't use it for a while (more than 3h in my case)

### Does this issue happen every time?
Don't know, first time I see it

### Send the client logs

```
[18-05-08 14:53:01.271] (CLI) (node:23712) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
at _addListener (events.js:280:19)
at IOSDeviceLibStdioHandler.addListener (events.js:297:10)
at Promise (/Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/node_modules/ios-device-lib/index.js:121:35)
at new Promise (<anonymous>)
at IOSDeviceLib._getPromise (/Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/node_modules/ios-device-lib/index.js:103:10)
at IOSDeviceLib.startDeviceLog (/Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/node_modules/ios-device-lib/index.js:90:8)
at IOSDeviceOperations.startDeviceLog (/Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device-operations.js:85:24)
at IOSDevice.<anonymous> (/Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device.js:65:43)
at Generator.next (<anonymous>)
at /Users/fthuin/.nvm/versions/node/v8.9.4/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device.js:13:71

```

**Comment by fthuin** [comment]
@tsvetie I'm using nativescript 4.0.0, I'll update to nativescript 4.0.1 as suggested. I'll post here again if the issue still arises.

**Comment by fthuin** [comment]
Did not see the error for a whole week, I close, thank you for your answer!

**Comment by NL33** [comment]
Note that error has happened to me with SideKick and NS / CLI 5.1.0. Simple app, started with sidekick. for iOS, running on device. Gives this error all of a sudden.
