### ISSUE TITLE
Do not compile my app with IOS

### ISSUE THREAD

**Issue by CarlosTolenk** [NativeScript/sidekick-feedback#191]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows
### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

**Comment by CarlosTolenk** [comment]
The application works perfectly on Android but at the time of compiling it launches this is the console:

[18-05-17 23:57:52.807] NativeScript Sidekick version: 1.9.1-v.2018.4.23.1
[18-05-17 23:57:52.878] Checking for updates...
[18-05-17 23:57:54.465] Dependencies versions: NodeJS: 8.9.4, npm: 5.6.0, NativeScript CLI: 4.1.0-2018-05-17-11549.
[18-05-17 23:57:54.987] (CLI) Using NativeScript CLI located in C:\Users\CarlosTolenk\AppData\Roaming\npm\node_modules\nativescript
[18-05-17 23:57:55.388] No updates available.
[18-05-17 23:57:55.474] (CLI) Searching for devices...
[18-05-17 23:57:55.858] Loaded CLI extension nativescript-cloud, version 1.9.0.
[18-05-17 23:57:55.860] Loaded CLI extension nativescript-starter-kits, version 0.3.4.
[18-05-17 23:57:56.139] Devices service initialized.
[18-05-17 23:58:03.871] App with path: C:\Users\CarlosTolenk\Desktop\CDiamante_Mobile\CDiamante was opened.
[18-05-17 23:58:22.480] Build started.
[18-05-17 23:58:23.077] (CLI) Starting cloud build of 'C:\Users\CarlosTolenk\Desktop\CDiamante_Mobile\CDiamante', platform: 'iOS', configuration: 'Debug', buildId: 4361e2b8-276c-481d-a381-d9c36e1dbdd6.
[18-05-17 23:58:23.081] (CLI) (node:8160) TypeError: Converting circular structure to JSON
at JSON.stringify (<anonymous>)
at process.target._send (internal/child_process.js:675:23)
at process.target.send (internal/child_process.js:586:19)
at MessageService.sendMessage (C:\Users\CarlosTolenk\AppData\Local\NativeScriptSidekick\app-1.9.1-v20184231\resources\app.asar.unpacked\shared\child-process\message-service.js:34:21)
at sendMessage (C:\Users\CarlosTolenk\AppData\Local\NativeScriptSidekick\app-1.9.1-v20184231\resources\app.asar.unpacked\shared\child-process\child-helpers.js:13:24)
at sendErrorMessage (C:\Users\CarlosTolenk\AppData\Local\NativeScriptSidekick\app-1.9.1-v20184231\resources\app.asar.unpacked\shared\child-process\child-helpers.js:19:9)
at promise.then.catch (C:\Users\CarlosTolenk\AppData\Local\NativeScriptSidekick\app-1.9.1-v20184231\resources\app.asar.unpacked\shared\child-process\child-helpers.js:36:17)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
(node:8160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
at emitWarning (internal/process/promises.js:78:15)
at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by ahitrov** [comment]
Hi @CarlosTolenk 

Thank you for reporting this issue. We will provide a fix soon.

Cheers,

Alex

**Comment by markcoenradie** [comment]
Same issue with circular reference in child-helpers.js. Is this already (being) fixed?

**Comment by sohail-kaleem** [comment]
I ran into the same error using Nativescript Sidekick IOS cloud build while Android works without an error. I'm running on Ubuntu 18.x based Linux.

Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.4.0
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5

Error Output:
[20-02-22 15:54:44.372] (CLI) (node:30057) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Error'
--- property 'errors' closes the circle
at stringify ()
at writeChannelMessage (internal/child_process/serialization.js:118:20)
at process.target._send (internal/child_process.js:779:17)
at process.target.send (internal/child_process.js:677:19)
at MessageService.sendMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/message-service.js:34:21)
at sendMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:13:24)
at sendErrorMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:19:9)
at /opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:36:17
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
at processPromiseRejections (internal/process/promises.js:211:11)
at processTicksAndRejections (internal/process/task_queues.js:98:32)
[20-02-22 15:54:44.376] (CLI) (node:30057) TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Error'
--- property 'errors' closes the circle
at stringify ()
at writeChannelMessage (internal/child_process/serialization.js:118:20)
at process.target._send (internal/child_process.js:779:17)
at process.target.send (internal/child_process.js:677:19)
at MessageService.sendMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/message-service.js:34:21)
at sendMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:13:24)
at sendErrorMessage (/opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:19:9)
at /opt/NativeScript Sidekick/resources/app.asar.unpacked/shared/child-process/child-helpers.js:36:17
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
at emitDeprecationWarning (internal/process/promises.js:161:11)
at processPromiseRejections (internal/process/promises.js:213:13)
at processTicksAndRejections (internal/process/task_queues.js:98:32)

**Comment by BHuys** [comment]
Any progress or a workaround for this issue? I'm having the exact same issue as sohail-kaleem. Android builds fine, IOS build has the circular JSON error on the Error object.
