### ISSUE TITLE
removeChild' on 'Node

### ISSUE THREAD

**Issue by elieobeid7** [NativeScript/sidekick-feedback#192]
```
[18-05-20 00:11:04.909] Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node., Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at o.beforeDestroy (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:27405:31)
at _t (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:14739)
at o.un.$destroy (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:32023)
at destroy (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:23582)
at w (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:53815)
at w (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:53914)
at w (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:53914)
at w (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:53914)
at w (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:53914)
at o.e.nodeOps [as __patch__] (file:///C:/Users/user-pc/AppData/Local/NativeScriptSidekick/app-1.9.1-v20184231/resources/app.asar/ui/app.js:537:57225)
```
I have the latest nativescript installed, this happens whenever I switch tabs in sidekick,  one of the biggest errors i've seen. It usually happens either when I click on plugins or when installing a plugin

**Comment by tsvetie** [comment]
Hi @elieobeid7,

Can you give me a bit more information how to reproduce the problem? It would be great if you could send me the log files of a session, in which you reproduced the problem as well. To open the folder of the log files, select Help -> Show Logs from the Sidekick window menu.

**Comment by tsvetie** [comment]
Sounds good. With the new UI we changed a lot of things and this might have been fixed among other things. In case you reproduce the problem again with the new UI, could you send me all log files - Sidekick creates two logs files - main and console. You sent me the console log file. The main log file contains information about the actions you performed so I can use it to follow the steps you made when you got the error.

**Comment by elieobeid7** [comment]
I'll close the issue for now and reopen it in case I encounter the error again. Thank you so much.
