### ISSUE TITLE
Local iOS build fails

### ISSUE THREAD

**Issue by godrose** [NativeScript/sidekick-feedback#194]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Unable to create a successful local iOS build for an app that was built successfully before

### Which platform(s) does the issue occur on?
iOS - latest
macOS - latest

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop**  1.9.1-v.2018.4.23.1 (latest) 
- **NativeScript CLI:** 4.0.2
- **CLI extension nativescript-cloud:** 1.9.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Start the NativeScript Sidekick
2. Try to run local iOS build

### Does this issue happen every time?
_Yes_

### Send the client logs
[18-05-22 11:07:44.914] Loaded CLI extension nativescript-cloud, version 1.9.0.
[18-05-22 11:07:44.917] Loaded CLI extension nativescript-starter-kits, version 0.3.4.
[18-05-22 11:07:46.328] (CLI) /usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:116
            throw new Error(`Error while executing command '${["xcrun", "simctl", command].concat(args).join(" ")}'. Please ensure your tools are configured correctly. More info: ${result.stderr.toString()}`);
            ^
Error: Error while executing command 'xcrun simctl list devices'. Please ensure your tools are configured correctly. More info: 2018-05-22 11:07:45.852 simctl[84951:11665050] CoreSimulator detected Xcode.app relocation or CoreSimulatorService version change.  Framework path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework) and version (518.21) does not match existing job path (/Library/Developer/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc) and version (518.19).  Attempting to remove the stale service in order to add the expected version.
    at Simctl.simctlExec (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:116:19)
    at Simctl.getDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/simctl.js:51:31)
    at XCodeSimctlSimulator.getBootedDevices (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/iphone-simulator-xcode-simctl.js:184:37)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/nativescript/node_modules/ios-sim-portable/lib/ios-sim.js:39:63)
    at ontimeout (timers.js:458:11)

**Comment by tsvetie** [comment]
Hi @godrose,

The important part of the log that you sent is the following CLI messages:

_(CLI) Xcode 8 requires a team id to be specified when building for device.
(CLI) You can specify the team id by setting the DEVELOPMENT_TEAM setting in build.xcconfig file located in App_Resources folder of your app, or by using the --teamId option when calling run, debug or livesync commands._

Since you are not using NS CLI commands, but Sidekick, your only option is to set the DEVELOPMENT_TEAM. Follow these steps to do this:

1. In your app folder, navigate to app/AppResources/iOS and open the build.xcconfig file.
2. (Optional) If the build.xcconfig file does not exist, create it manually.
3. Specify a team id by entering DEVELOPMENT_TEAM = YOUR_TEAM_ID.

**Comment by godrose** [comment]
Thanks for the response. Which value should I provide for the team id? I
don't belong to any team so it's not clear what should be put there. Thanks.

**Comment by godrose** [comment]
@tsvetie

**Comment by tsvetie** [comment]
Hey @godrose,

There are two problems that lead to this error - the first is if there is no default development team specified in the native Xcode project, the second is if you are a member of two or more development teams.

The instructions that I first sent you were for the second problem type. If I understand you correctly, you have hit the first problem. In order to fix it, open Xcode and log in with your development account. You can find a short overview of the iOS Developer Program and how it relates to Sidekick builds [here](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/ios-developer-program).

These videos cover the topic as well:

- [Deploying iOS Apps Using NativeScript Sidekick—Free Account Workflow](https://www.youtube.com/watch?v=eLOLiiCSWF8&feature=youtu.be)
- [Deploying iOS Apps Using NativeScript Sidekick—Paid Account Workflow](https://www.youtube.com/watch?v=5gKuR2UCOnM&feature=youtu.be)

Please note that since you are working on a Mac, then you have iOSSimulator. In case you just want to test your app, you can run and deploy on the iOSSimulator instead of a real device and this build will not require provision, certificate or default development team so you will not need to do these steps now.
