### ISSUE TITLE
Certificate has expired error

### ISSUE THREAD

**Issue by jkulubya** [NativeScript/sidekick-feedback#219]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I get a "certificate has expired" error on startup. Sidekick hangs on the splash screen

### Which platform(s) does the issue occur on?
Android <br/>
Ubuntu 16.04.4

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application

### Does this issue happen every time?
Yes

### Send the client logs
```
[18-07-02 15:43:52.953] (Info) ab.actionsLogger.shell.appVersion - {"name":"NativeScript Sidekick","version":"1.10.3-v.2018.6.26.1"}
[18-07-02 15:43:52.957] (Info) ab.addPage.shell.appFlavor - No value provided
[18-07-02 15:43:52.995] (Info) ab.appContext.shell.appContext - No value provided
[18-07-02 15:43:53.025] (Info) ab.appValidityWatcher.shell.isAppValid - No value provided
[18-07-02 15:43:53.040] (Info) ab.autoUpdate.shell.updates - {"eventName":"checking-for-update","message":"Checking for updates..."}
[18-07-02 15:43:53.063] (Info) ab.buildDeploy.shell.buildConfigChanged - {"platform":null,"buildType":"Cloud","buildConfig":"Debug","emulatorDevice":"nexus5","isClean":false,"useSharedCloud":false,"webpack":{"isWebpack":false,"env":{"uglify":true,"snapshot":true,"aot":true}}}
[18-07-02 15:43:53.074] (Info) ab.buildDeploy.shell.isWebpackSupported - No value provided
[18-07-02 15:43:53.077] (Info) ab.buildDeploy.shell.isAOTSupported - No value provided
[18-07-02 15:43:53.078] (Info) ab.buildDeploy.shell.canChangeWebpackOption - true
[18-07-02 15:43:53.082] (Info) ab.buildDeploy.shell.isSharedCloudFlagSupported - No value provided
[18-07-02 15:43:53.106] (Info) ab.codeSigning.shell.codeSigningChanged - {"ios":{},"android":{}}
[18-07-02 15:43:53.111] (Info) ab.codeSigning.shell.csrStore - {}
[18-07-02 15:43:53.127] (Info) ab.createApp.shell.lastUsedAppDirectory - {"appDirectory":"/home/x/Projects"}
[18-07-02 15:43:53.140] (Info) ab.editor.shell.editorSettings - {"editorPath":"","args":"{projectPath}"}
[18-07-02 15:43:53.151] (Info) ab.kinveyAuth.shell.configData - {"shouldConfigure":false}
[18-07-02 15:43:53.152] (Info) ab.kinveyAuth.shell.checkEula - No value provided
[18-07-02 15:43:53.229] (Info) ab.privacy.shell.privacyConfig - {"skipTracking":true,"privacyPolicyUrl":"https://www.progress.com/legal/privacy-policy","intercomPrivacyPolicyUrl":"https://www.intercom.com/terms-and-policies#privacy","forgetMeUrl":"https://app.onetrust.com/app/#/webform/65e969b1-9755-4cb6-adbb-0ae5939fb132","unsubscribeUrl":"https://forms.progress.com/emailoptin","partnersUrl":"https://www.progress.com/partners/partner-directory","privacyInfoShown":true,"emailsAccepted":false}
[18-07-02 15:43:53.232] (Info) ab.proxy.shell.proxySettings - {}
[18-07-02 15:43:53.252] (Info) ab.subscriptions.shell.usageInfo - No value provided
[18-07-02 15:43:53.254] (Info) ab.subscriptions.shell.accountFeatures - []
[18-07-02 15:43:53.381] (Info) ab.userAccounts.shell.userAccountList - []
[18-07-02 15:43:53.384] (Info) ab.userAccounts.shell.activeUserAccount - No value provided
[18-07-02 15:43:54.340] (Info) ab.analytics.ui.setVersion - {"version":"1.10.3-v.2018.6.26.1"}
[18-07-02 15:43:54.351] (Info) ab.buildDeploy.ui.pendingRequests - No value provided
[18-07-02 15:43:54.425] (Info) ab.vueService.ui.routeChanged - {"path":"/recent-apps","query":{"back":true}}
[18-07-02 15:43:54.551] (Info) ab.tnsDoctor.shell.checkDependencies - {"node":{"name":"NodeJS","version":"8.11.1","minVersion":"8.0.0","preferredVersion":"8.11.3","isMet":true,"isAutoFixSupported":false},"npm":{"name":"npm","version":"5.6.0","isMet":true,"isAutoFixSupported":false},"tns":{"name":"NativeScript CLI","version":"4.1.2","minVersion":"4.1.0","preferredVersion":"latest","isMet":true,"isAutoFixSupported":false}}
[18-07-02 15:43:54.643] (Info) ab.connectedDevices.ui.devicesListChanged - {}
[18-07-02 15:43:56.096] (Info) ab.tnsDoctor.shell.checkLocalBuild - {"iOS":{"canExecuteLocalBuild":false,"warnings":[]},"Android":{"canExecuteLocalBuild":true,"warnings":[]}}
[18-07-02 15:43:56.414] (Info) ab.autoUpdate.shell.updates - {"eventName":"update-not-available","message":"No updates available."}
[18-07-02 15:43:56.670] (Info) ab.childProcessCommunication.shell.cliStdout - Using NativeScript CLI located in /home/x/.config/yarn/global/node_modules/nativescript



[18-07-02 15:43:56.955] (Info) ab.childProcessCommunication.shell.cliStdout - Searching for devices...


[18-07-02 15:43:57.143] (Info) ab.childProcessCommunication.shell.cliStdout - iTunes is not available for this operating system. You will not be able to work with connected iOS devices.


[18-07-02 15:43:57.213] (Info) ab.cliExtensions.shell.extensionLoaded - {"extensionName":"nativescript-cloud","extensionVersion":"1.11.0"}
[18-07-02 15:43:57.220] (Info) ab.cliExtensions.shell.extensionLoaded - {"extensionName":"nativescript-starter-kits","extensionVersion":"0.3.4"}
[18-07-02 15:43:57.225] (Info) ab.cliExtensions.shell.extensionsLoaded - [{"extensionName":"nativescript-cloud","extensionVersion":"1.11.0"},{"extensionName":"nativescript-starter-kits","extensionVersion":"0.3.4"}]
[18-07-02 15:43:57.465] (Info) ab.cliExtensions.shell.tnsInitialize - {}
[18-07-02 15:44:02.395] (Info) ab.kinveyEula.shell.eulaData - {"url":"https://www.nativescript.org/nativescript-sidekick/eula","shouldAcceptEula":true}
[18-07-02 15:44:04.880] (Info) ab.analyticsProvider.shell.enableTracking - No value provided
[18-07-02 15:44:04.899] (Info) ab.analytics.shell.analyticsEnabled - true
[18-07-02 15:44:04.902] (Info) ab.eula.shell.eulaData - {"url":"https://www.nativescript.org/nativescript-sidekick/eula","shouldAcceptEula":false}
[18-07-02 15:44:06.239] (Error) ab.errorHandler.shell.error - certificate has expired, Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1105:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:469:38)
```

**Comment by bradrice** [comment]
I'm getting the issue as well. I just tried opening Sidekick on my Mac and am getting the Certificate has Expired and it hangs and won't open.

**Comment by ggarabedian** [comment]
@jkulubya, @bradrice and @JillevdW, we are aware of the issue and we have already taken the necessary steps to resolve the problem. However, it will take some time for the changes to propagate throughout the cloud infrastructure and in the meantime, we would appreciate your patience and understanding. 

Thank you!
