### ISSUE TITLE
Multiple Missing API Errors After Re-Install

### ISSUE THREAD

**Issue by francisco-merizalde** [NativeScript/sidekick-feedback#228]
I started getting these errors yesterday after re-installing Sidekick. I have since reset my PC and still have this error after installing Sidekick, each time it runs. I have tried re-installing everything to no avail. The errors in the main log are below.

[18-07-10 14:24:34.415] (Info) ab.cliExtensions.shell.extensionsLoaded - []
[18-07-10 14:24:35.058] (Error) ab.childProcessCommunication.shell.cliStderr - (node:5960) UnhandledPromiseRejectionWarning: Error: Missing API. - tns.nsCloudBuildService
    at Object.get (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\cli-provider.js:151:39)
    at requireCLI.then (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\services\cli-build-service.js:264:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5960) Error: Missing API. - tns.nsCloudBuildService
    at Object.get (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\cli-provider.js:151:39)
    at requireCLI.then (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\services\cli-build-service.js:264:45)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:5960) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:92:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)

[18-07-10 14:24:35.062] (Error) ab.eula.shell.eulaData - Missing API. - tns.nsCloudEulaService, Error: Missing API. - tns.nsCloudEulaService
    at Object.get (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\cli-provider.js:151:39)
    at requireCLI.then (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\services\cli-eula-service.js:16:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-10 14:24:35.066] (Error) ab.errorHandler.shell.error - Missing API. - tns.nsStarterKitsApplicationService, Error: Missing API. - tns.nsStarterKitsApplicationService
    at Object.get (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\cli-provider.js:151:39)
    at requireCLI.then (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\services\cli-template-service.js:20:64)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-10 14:24:35.068] (Error) ab.kinveyEula.shell.eulaData - Missing API. - tns.nsCloudKinveyEulaService, Error: Missing API. - tns.nsCloudKinveyEulaService
    at Object.get (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\cli-provider.js:151:39)
    at requireCLI.then (C:\Users\Francisco.Merizalde\AppData\Local\NativeScriptSidekick\app-1.10.3-v20186261\resources\app.asar.unpacked\cli\services\cli-kinvey-eula-service.js:19:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ventsislav-georgiev** [comment]
@francisco-merizalde This seems to be an issue related to the CLI's extensions. Could you try removing the `AppData\Roaming\.nativescript-cli\extensions` folder. Sidekick will reinstall those extensions on boot.

**Comment by francisco-merizalde** [comment]
Thanks for your help. I really needed to get back up and running and I had tried cleaning those folders up. I ultimately re-imaged my machine to get back up and running.
