### ISSUE TITLE
Cannot install SideKick beta

### ISSUE THREAD

**Issue by gpmkn** [NativeScript/sidekick-feedback#24]
Hi,
Have installed CLI using Windows Installer and all dependencies are installed and verified with 
"tns doctor".
But i cannot install SideKick beta that is available for public review. After few mins it say “Installation has failed”.
Installed "Visual Studio Code"  without problem and installed all NativeScript extensions. 
This is fresh machine Win 10 32Bit just created for NativeScript development.
As i am new to Mobile App development and NativeScript and from Microsoft\Windows platform please guide me to get this installed.
Thank you.

Below is the log
----------------------------------------------------------------------------------------
```txt
2017-08-05 06:23:08> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2017-08-05 06:23:08> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 06:23:08> Program: About to install to: C:\Users\Admin\AppData\Local\NativeScriptSidekick
2017-08-05 06:23:09> CheckForUpdateImpl: Couldn’t write out staging user ID, this user probably shouldn’t get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages.betaId’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter…ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-08-05 06:23:09> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages\RELEASES’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-08-05 06:23:09> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 06:23:09> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-08-05 06:23:09> ApplyReleasesImpl: Writing files to app directory: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314
2017-08-05 06:23:42> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe]
2017-08-05 06:23:43> ApplyReleasesImpl: Couldn’t run Squirrel hook, continuing: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.Utility.d__11.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<b__0>d.MoveNext()
2017-08-05 06:23:43> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.b__10_6(ProcessStartInfo info)
at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable1 source, Action1 onNext)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__34.MoveNext()
2017-08-05 06:23:43> Unhandled exception: System.AggregateException: One or more errors occurred. —> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.b__10_6(ProcessStartInfo info)
at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable1 source, Action1 onNext)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__34.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__2.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()
— End of inner exception stack trace —
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at Squirrel.Update.Program.executeCommandLine(String[] args)
at Squirrel.Update.Program.main(String[] args)
—> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.b__10_6(ProcessStartInfo info)
at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable1 source, Action1 onNext)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__34.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__2.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()<—

2017-08-05 06:46:01> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2017-08-05 06:46:01> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 06:46:01> Program: About to install to: C:\Users\Admin\AppData\Local\NativeScriptSidekick
2017-08-05 06:46:01> Program: Install path C:\Users\Admin\AppData\Local\NativeScriptSidekick already exists, burning it to the ground
2017-08-05 06:46:04> CheckForUpdateImpl: Couldn’t write out staging user ID, this user probably shouldn’t get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages.betaId’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter…ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-08-05 06:46:04> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages\RELEASES’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-08-05 06:46:04> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 06:46:04> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-08-05 06:46:04> ApplyReleasesImpl: Writing files to app directory: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314
2017-08-05 06:46:50> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe]
2017-08-05 06:46:50> ApplyReleasesImpl: Couldn’t run Squirrel hook, continuing: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.Utility.d__11.MoveNext()
— End of stack trace from previous location where exception was thrown —

— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()<—

2017-08-05 12:19:07> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC
2017-08-05 12:19:07> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 12:19:07> Program: About to install to: C:\Users\Admin\AppData\Local\NativeScriptSidekick
2017-08-05 12:19:07> Program: Install path C:\Users\Admin\AppData\Local\NativeScriptSidekick already exists, burning it to the ground
2017-08-05 12:19:12> CheckForUpdateImpl: Couldn’t write out staging user ID, this user probably shouldn’t get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages.betaId’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter…ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-08-05 12:19:12> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages\RELEASES’.
2017-08-05 12:19:48> Program: Starting Squirrel Updater: --install.
2017-08-05 12:19:48> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 12:19:48> Program: About to install to: C:\Users\Admin\AppData\Local\NativeScriptSidekick
2017-08-05 12:19:48> Program: Install path C:\Users\Admin\AppData\Local\NativeScriptSidekick already exists, burning it to the ground
2017-08-05 12:19:51> CheckForUpdateImpl: Couldn’t write out staging user ID, this user probably shouldn’t get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages.betaId’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter…ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-08-05 12:19:51> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages\RELEASES’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-08-05 12:19:51> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-05 12:19:51> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-08-05 12:19:51> ApplyReleasesImpl: Writing files to app directory: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314
2017-08-05 12:20:14> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe]
2017-08-05 12:20:14> ApplyReleasesImpl: Couldn’t run Squirrel hook, continuing: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.Utility.d__11.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass10_0.<b__0>d.MoveNext()
2017-08-05 12:20:14> IEnableLogger: Failed to invoke post-install: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.b__10_6(ProcessStartInfo info)
at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable1 source, Action1 onNext)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__34.MoveNext()
2017-08-05 12:20:14> Unhandled exception: System.AggregateException: One or more errors occurred. —> System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.UpdateManager.ApplyReleasesImpl.<>c.b__10_6(ProcessStartInfo info)
at Squirrel.EnumerableExtensions.ForEach[TSource](IEnumerable1 source, Action1 onNext)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__10.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.Utility.d__34.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.UpdateManager.ApplyReleasesImpl.d__2.MoveNext()
— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Squirrel.UpdateManager.d__10.MoveNext()

— End of stack trace from previous location where exception was thrown —
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Squirrel.Update.Program.d__4.MoveNext()<—

2017-08-06 09:48:52> Program: Starting Squirrel Updater: --install .
2017-08-06 09:48:52> Program: Starting install, writing to C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-06 09:48:52> Program: About to install to: C:\Users\Admin\AppData\Local\NativeScriptSidekick
2017-08-06 09:48:52> Program: Install path C:\Users\Admin\AppData\Local\NativeScriptSidekick already exists, burning it to the ground
2017-08-06 09:48:54> CheckForUpdateImpl: Couldn’t write out staging user ID, this user probably shouldn’t get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages.betaId’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
at System.IO.StreamWriter…ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2017-08-06 09:48:54> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path ‘C:\Users\Admin\AppData\Local\NativeScriptSidekick\packages\RELEASES’.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
at System.IO.FileStream…ctor(String path, FileMode mode, FileAccess access, FileShare share)
at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
at Squirrel.UpdateManager.CheckForUpdateImpl.d__2.MoveNext()
2017-08-06 09:48:54> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Admin\AppData\Local\SquirrelTemp
2017-08-06 09:48:54> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2017-08-06 09:48:54> ApplyReleasesImpl: Writing files to app directory: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314
2017-08-06 09:49:23> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe]
2017-08-06 09:49:23> ApplyReleasesImpl: Couldn’t run Squirrel hook, continuing: C:\Users\Admin\AppData\Local\NativeScriptSidekick\app-0.2.0-v20177314\NativeScriptSidekick.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at Squirrel.Utility.d__11.MoveNext()
— End of stack trace from previous location where exception was thrown —
```
----------------------------------------------------------------------------------------

**Comment by ventsislav-georgiev** [comment]
@gpmkn The Sidekick only supports 64-bit environments. If there is a large demand, we will consider adding 32-bit environment support.

**Comment by gpmkn** [comment]
Thanks Ventsislav, I think i tried on 64 bit also, may be i used 32 bit JDK.
Will start a fresh VM, everything 64bit.

**Comment by gpmkn** [comment]
Though i had some issues installing CLI using Windows Installer on fresh 64bit machine,, i managed to install it manually following "Advanced Windows installation" steps. 
SideKick was installed without any problem on 64bit machine. 
This specific requirement "Supports only on 64Bit" would have been more highlighted, i just wasted a day trying different things.
Anyway, thanks very much Ventsislav for pointing out this.
