### ISSUE TITLE
Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..

### ISSUE THREAD

**Issue by gaob** [NativeScript/sidekick-feedback#240]
### Did you verify whether this issue has already been reported here?
Yes at https://github.com/NativeScript/sidekick-feedback/issues/92, but that issue doesn't provide resolution and it was marked as "need more information".

### Tell us about the problem
An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

### Which platform(s) does the issue occur on?
iOS
macOS 10.13.3

### Provide the following version numbers that the issue occurs with:

NativeScript Sidekick Desktop 1.11.1-v.2018.7.17.4 (latest)
with NativeScript CLI: 4.1.2 installed.
CLI extension nativescript-cloud: 1.13.0
CLI extension nativescript-starter-kits: 0.3.4

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Connect my iPhone via USB to my macbook air.
3. Go to Sidekick Devices.
4. Click the settings icon of my connected iPhone.
5. Click Auto Generate and see the error.

### Does this issue happen every time?
Yes.

### Send the client logs
[18-07-29 18:34:26.197] (CLI) Searching for devices...
[18-07-29 18:34:26.941] Loaded CLI extension nativescript-cloud, version 1.13.0.
[18-07-29 18:34:26.948] Loaded CLI extension nativescript-starter-kits, version 0.3.4.
[18-07-29 18:34:32.312] Devices service initialized.
[18-07-29 18:34:32.528] The user   logged in.
[18-07-29 18:34:37.292] App with path: /Users/bingao/nativescript/giftler was opened.
[18-07-29 18:35:55.791] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:36:01.946] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 18:37:33.889] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:37:41.310] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 18:39:42.609] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:39:50.043] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 18:43:43.220] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:43:49.244] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 18:45:26.542] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:45:32.311] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 18:50:00.577] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 18:50:06.355] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[18-07-29 20:34:22.244] Checking for updates...
[18-07-29 20:34:22.912] No updates available.
[18-07-29 22:34:22.090] Checking for updates...
[18-07-29 22:34:22.797] No updates available.
[18-07-29 23:06:31.402] (CLI) Starting generation of iOS certificate and provision files.
[18-07-29 23:06:39.110] An error has occured while generating the certificate and mobile provision. Reason: The Code Signing Assistance service is temporary unavailable. Please try again later.., Error: Codesign failed. Reason is: The Code Signing Assistance service is temporary unavailable. Please try again later..
    at CloudCodesignService.<anonymous> (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:86:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bingao/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ggarabedian** [comment]
Hello @gaob,

The Code Signing Assistance service depends on an Apple service to generate the temporary certificates and mobile provisions. The reported error is occurring when the Apple service is down for maintenance and the user cannot be logged in.

Having said that, the only suggestion we can give in this case is to wait for some time and attempt to access the Code Signing Assistance later. 

I hope this is of any help.

**Comment by gaob** [comment]
Garo,

Thank you! I have tried the same thing tonight with the same error.

If I cannot Auto Generate the code signing, what can I do to manually generate Certificate and Provision files?

Also, which Apple service is down that caused this issue? Will that be due to some other errors?

Regards,

@gaob

**Comment by ggarabedian** [comment]
@gaob, I am sorry to hear that you continue to experience the issue. I just tried to create a temporary certificate and mobile provision with the Code Signing Assistance and everything worked as expected. As far as we are aware, the reported error message is occurring only when the specific Apple service is down (for maintenance or other reason).

The service used to generate the temporary certificate and mobile provision is the same one used by Xcode. To use a free Apple account to generate temporary certificate and mobile provision, you need to use Sidekick on a macOS system. If you have a paid Apple account, you can start from [The iOS Developer Program](https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/ios-developer-program) article in our documentation and follow the steps outlined there.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
