### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by HunterTKingsley** [NativeScript/sidekick-feedback#275]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Simply retesting and I get build fails. 

### Which platform(s) does the issue occur on?
IOS <br/>
Windows 10

### Provide the following version numbers that the issue occurs with:

**NativeScript Sidekick Desktop 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Attach iPhone, go to "Select target platform" and pick ios
2. Build - it give error

### Does this issue happen every time?
Yes

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._
[18-10-07 20:14:09.995] NativeScript Sidekick version: 1.12.2-v.2018.9.17.5
[18-10-07 20:14:10.095] Checking for updates...
[18-10-07 20:14:10.544] Dependencies versions: NodeJS: 6.11.4, npm: 6.3.0, NativeScript CLI: 4.2.3.
[18-10-07 20:14:11.430] No updates available.
[18-10-07 20:14:12.484] (CLI) Using NativeScript CLI located in C:\Users\Hunte\AppData\Roaming\npm\node_modules\nativescript
[18-10-07 20:14:14.009] (CLI) Searching for devices...
[18-10-07 20:14:14.818] Support for Node.js ^6.0.0 is deprecated and will be removed in one of the next releases of NativeScript. Please, upgrade to the latest Node.js LTS version.
[18-10-07 20:14:20.651] Devices service initialized.
[18-10-07 20:14:32.584] (CLI) + nativescript-cloud@1.14.0
[18-10-07 20:14:32.584] (CLI) added 2 packages from 3 contributors, removed 18 packages, updated 11 packages and audited 452 packages in 15.2s
[18-10-07 20:14:32.587] (CLI) found 26 vulnerabilities (18 low, 2 moderate, 6 high)
[18-10-07 20:14:32.587] (CLI)   run `npm audit fix` to fix them, or `npm audit` for details
[18-10-07 20:14:39.246] Installed CLI extension nativescript-cloud, version 1.14.0.
[18-10-07 20:14:39.256] Loaded CLI extension nativescript-cloud, version 1.14.0.
[18-10-07 20:14:39.259] Loaded CLI extension nativescript-starter-kits, version 0.3.5.
[18-10-07 20:14:46.129] (CLI) Launching login page in browser.
[18-10-07 20:15:28.672] The user Hunter Kingsley logged in.
[18-10-07 20:15:38.208] App with path: C:\World Perfect LLC\RHAReferralCalculator was opened.
[18-10-07 20:16:25.355] Build started.
[18-10-07 20:16:27.886] (CLI) Starting cloud build of 'C:\World Perfect LLC\RHAReferralCalculator', platform: 'iOS', configuration: 'Debug', buildId: 11d1c6bc-6327-4d01-ab88-b0f062df7c53.
[18-10-07 20:16:27.976] Prepare step started.
[18-10-07 20:16:30.112] (CLI) Executing before-shouldPrepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-shouldPrepare\nativescript-dev-webpack.js
[18-10-07 20:16:30.155] (CLI) Executing before-cleanApp hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-cleanApp\nativescript-dev-webpack.js
[18-10-07 20:16:30.677] (CLI) Executing before-prepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-prepare\nativescript-dev-typescript.js
[18-10-07 20:16:30.691] (CLI) Found peer TypeScript 2.7.2
[18-10-07 20:16:34.221] (CLI) Preparing project...
[18-10-07 20:16:34.223] (CLI) Executing before-prepareJSApp hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-prepareJSApp\nativescript-dev-webpack.js
[18-10-07 20:16:37.997] (CLI) Successfully prepared plugin nativescript-intl for ios.
[18-10-07 20:16:38.098] (CLI) Successfully prepared plugin nativescript-theme-core for ios.
[18-10-07 20:16:38.186] (CLI) Successfully prepared plugin tns-core-modules for ios.
[18-10-07 20:16:38.274] (CLI) Successfully prepared plugin tns-core-modules-widgets for ios.
[18-10-07 20:16:38.369] (CLI) Project successfully prepared (iOS)
[18-10-07 20:16:38.372] (CLI) Executing after-prepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\after-prepare\nativescript-dev-webpack.js
[18-10-07 20:16:38.378] Prepare step completed.
[18-10-07 20:16:40.030] Upload step started.
[18-10-07 20:16:41.462] (CLI) Unable to use git, reason is:
[18-10-07 20:16:41.462] (CLI) Command C:\Program Files\Git\cmd\git.exe failed with exit code 128 Error output:
[18-10-07 20:16:41.462] (CLI) *** Please tell me who you are.
[18-10-07 20:16:41.462] (CLI) Run
[18-10-07 20:16:41.462] (CLI)   git config --global user.email "you@example.com"
[18-10-07 20:16:41.462] (CLI)   git config --global user.name "Your Name"
[18-10-07 20:16:41.462] (CLI) to set your account's default identity.
[18-10-07 20:16:41.462] (CLI) Omit --global to set the identity only in this repository.
[18-10-07 20:16:41.462] (CLI) fatal: unable to auto-detect email address (got 'Hunte@DESKTOP-BQL3CM4.(none)')
[18-10-07 20:16:48.150] Upload step completed.
[18-10-07 20:16:49.118] Build step started.
[18-10-07 20:17:43.433] (CLI) internal/streams/legacy.js:59
[18-10-07 20:17:43.433] (CLI)       throw er; // Unhandled stream error in pipe.
[18-10-07 20:17:43.433] (CLI)       ^
[18-10-07 20:17:43.433] (CLI) Error: getaddrinfo ENOTFOUND livesync.ly livesync.ly:443
[18-10-07 20:17:43.433] (CLI)     at errnoException (dns.js:50:10)
[18-10-07 20:17:43.433] (CLI)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
[18-10-07 20:17:43.442] Build failed.

**Comment by HunterTKingsley** [comment]
Rob, after I posted this I decided to create a new csr and cert and, of course, a new development provisioning profile.  Now, it builds!

Thanks!

[18-10-07 21:01:35.703] Build started.
[18-10-07 21:01:38.388] (CLI) Starting cloud build of 'C:\World Perfect LLC\RHAReferralCalculator', platform: 'iOS', configuration: 'Debug', buildId: faade02c-0d9c-497d-abf2-4407e1969d6d.
[18-10-07 21:01:38.447] Prepare step started.
[18-10-07 21:01:39.672] (CLI) Executing before-shouldPrepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-shouldPrepare\nativescript-dev-webpack.js
[18-10-07 21:01:39.680] (CLI) Executing before-prepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-prepare\nativescript-dev-typescript.js
[18-10-07 21:01:39.683] (CLI) Found peer TypeScript 2.7.2
[18-10-07 21:01:42.465] (CLI) Preparing project...
[18-10-07 21:01:42.467] (CLI) Executing before-prepareJSApp hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\before-prepareJSApp\nativescript-dev-webpack.js
[18-10-07 21:01:42.698] (CLI) Project successfully prepared (iOS)
[18-10-07 21:01:42.700] (CLI) Executing after-prepare hook from C:\World Perfect LLC\RHAReferralCalculator\hooks\after-prepare\nativescript-dev-webpack.js
[18-10-07 21:01:42.704] Prepare step completed.
[18-10-07 21:01:44.144] Upload step started.
[18-10-07 21:01:44.504] (CLI) Unable to use git, reason is:
[18-10-07 21:01:44.504] (CLI) Command C:\Program Files\Git\cmd\git.exe failed with exit code 128 Error output:
[18-10-07 21:01:44.504] (CLI) *** Please tell me who you are.
[18-10-07 21:01:44.504] (CLI) Run
[18-10-07 21:01:44.504] (CLI)   git config --global user.email "you@example.com"
[18-10-07 21:01:44.504] (CLI)   git config --global user.name "Your Name"
[18-10-07 21:01:44.504] (CLI) to set your account's default identity.
[18-10-07 21:01:44.504] (CLI) Omit --global to set the identity only in this repository.
[18-10-07 21:01:44.504] (CLI) fatal: unable to auto-detect email address (got 'Hunte@DESKTOP-BQL3CM4.(none)')
[18-10-07 21:01:52.110] Upload step completed.
[18-10-07 21:01:52.724] Build step started.
[18-10-07 21:02:02.757] (CLI) ios Build Tooling revision 2018.08.08.1r
[18-10-07 21:02:02.757] (CLI)   Build Tooling Hostname administrators-mac-4.local
[18-10-07 21:02:02.757] (CLI)  Unzip Project Files
[18-10-07 21:02:02.757] (CLI)   NativeScript CLI version 4.0.2
[18-10-07 21:02:02.757] (CLI)  Add platform ios with runtime version 4.0.1
[18-10-07 21:02:05.834] (CLI) Copying template files...
[18-10-07 21:02:05.834] (CLI)  Installing tns-ios
[18-10-07 21:02:48.030] (CLI) Success: \"/private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node\" already installed
[18-10-07 21:02:48.030] (CLI)  Pass --update-binary to reinstall or --build-from-source to recompile
[18-10-07 21:02:49.587] (CLI) Hook already installed: nativescript-dev-typescript at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-prepare
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-typescript at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-watchPatterns
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-typescript at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-watch
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-typescript at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/after-watch
[18-10-07 21:02:49.587] (CLI)  Adding 'es6' lib to tsconfig.json...
[18-10-07 21:02:49.587] (CLI)  Adding 'dom' lib to tsconfig.json...
[18-10-07 21:02:49.587] (CLI)  Adding tns-core-modules path mappings lib to tsconfig.json...
[18-10-07 21:02:49.587] (CLI) Project already targets TypeScript ~2.7.2
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-prepareJSApp
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-cleanApp
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-watch
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/after-watch
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-watchPatterns
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-shouldPrepare
[18-10-07 21:02:49.587] (CLI)  Hook already installed: nativescript-dev-webpack at location: /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/after-prepare
[18-10-07 21:02:49.587] (CLI) NativeScript Webpack plugin was successfully added.
[18-10-07 21:02:49.587] (CLI) You can now bundle your project by passing --bundle flag to NativeScript CLI commands:
[18-10-07 21:02:49.587] (CLI)     - tns build android --bundle
[18-10-07 21:02:49.587] (CLI)     - tns build ios --bundle
[18-10-07 21:02:49.587] (CLI)     - tns run android --bundle
[18-10-07 21:02:49.587] (CLI)     - tns run ios --bundle
[18-10-07 21:02:49.587] (CLI) You can also pass the \"--env.uglify\" flag to use UglifyJS for minification.
[18-10-07 21:02:49.587] (CLI) For more information check out https://docs.nativescript.org/tooling/bundling-with-webpack#bundling.
[18-10-07 21:02:49.587] (CLI)  + tns-ios@4.0.1
[18-10-07 21:02:49.587] (CLI) added 761 packages in 42.784s
[18-10-07 21:03:02.808] (CLI) Project successfully created.
[18-10-07 21:03:02.808] (CLI)  Prepare Project for Platform -  ios
[18-10-07 21:03:04.505] (CLI) Executing before-shouldPrepare hook from /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-shouldPrepare/nativescript-dev-webpack.js
[18-10-07 21:03:04.505] (CLI)  Executing before-prepare hook from /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-prepare/nativescript-dev-typescript.js
[18-10-07 21:03:04.505] (CLI)  Found peer TypeScript 2.7.2
[18-10-07 21:03:07.632] (CLI) Preparing project...
[18-10-07 21:03:07.632] (CLI)  Executing before-prepareJSApp hook from /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/before-prepareJSApp/nativescript-dev-webpack.js
[18-10-07 21:03:07.632] (CLI)  Successfully prepared plugin nativescript-intl for ios.
[18-10-07 21:03:07.632] (CLI)  Successfully prepared plugin nativescript-theme-core for ios.
[18-10-07 21:03:07.632] (CLI)  Successfully prepared plugin tns-core-modules for ios.
[18-10-07 21:03:07.632] (CLI)  Successfully prepared plugin tns-core-modules-widgets for ios.
[18-10-07 21:03:09.031] (CLI) Project successfully prepared (ios)
[18-10-07 21:03:09.031] (CLI)  Executing after-prepare hook from /private/tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/hooks/after-prepare/nativescript-dev-webpack.js
[18-10-07 21:03:11.100] (CLI) Build for Device
[18-10-07 21:03:11.100] (CLI)  1 identity imported.
[18-10-07 21:03:11.100] (CLI)  keychain: \"/Users/builder/Library/Keychains/6fde649c-797b-46a8-88b8-b527c20eec5e-db\"
[18-10-07 21:03:11.100] (CLI) version: 512
[18-10-07 21:03:11.100] (CLI) class: 0x00000010
[18-10-07 21:03:11.100] (CLI) attributes:
[18-10-07 21:03:11.100] (CLI)     0x00000000 <uint32>=0x00000010
[18-10-07 21:03:11.100] (CLI)     0x00000001 <blob>=0x423731323035464200  \"B71205FB\\000\"
[18-10-07 21:03:11.100] (CLI)     0x00000002 <blob>=<NULL>
[18-10-07 21:03:11.100] (CLI)     0x00000003 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000004 <uint32>=0x00000000
[18-10-07 21:03:11.100] (CLI)     0x00000005 <uint32>=0x00000000
[18-10-07 21:03:11.100] (CLI)     0x00000006 <blob>=0x527185A68C05ABB76F9DAF2E81B24980ED5C2FED  \"Rq\\205\\246\\214\\005\\253\\267o\\235\\257.\\201\\262I\\200\\355\\134/\\355\"
[18-10-07 21:03:11.100] (CLI)     0x00000007 <blob>=<NULL>
[18-10-07 21:03:11.100] (CLI)     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  \"{87191ca2-0fc9-11d4-849a-000502b52122}\\000\"
[18-10-07 21:03:11.100] (CLI)     0x00000009 <uint32>=0x0000002A  \"\\000\\000\\000*\"
[18-10-07 21:03:11.100] (CLI)     0x0000000A <uint32>=0x00000800
[18-10-07 21:03:11.100] (CLI)     0x0000000B <uint32>=0x00000800
[18-10-07 21:03:11.100] (CLI)     0x0000000C <blob>=0x0000000000000000
[18-10-07 21:03:11.100] (CLI)     0x0000000D <blob>=0x0000000000000000
[18-10-07 21:03:11.100] (CLI)     0x0000000E <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x0000000F <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000010 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000011 <uint32>=0x00000000
[18-10-07 21:03:11.100] (CLI)     0x00000012 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000013 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000014 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000015 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000016 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000017 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000018 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x00000019 <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)     0x0000001A <uint32>=0x00000001
[18-10-07 21:03:11.100] (CLI)  Building project ...
[18-10-07 21:03:13.052] (CLI) ▸ Check Dependencies
[18-10-07 21:03:13.052] (CLI)  ▸ Running script 'NativeScript PreBuild'
[18-10-07 21:03:22.573] (CLI) ▸ Precompiling RHAReferralCalculator/RHAReferralCalculator-Prefix.pch
[18-10-07 21:03:24.027] (CLI) ▸ Precompiling RHAReferralCalculator/RHAReferralCalculator-Prefix.pch
[18-10-07 21:03:24.027] (CLI)  ▸ Compiling main.m
[18-10-07 21:03:25.514] (CLI) ▸ Compiling main.m
[18-10-07 21:03:25.514] (CLI)  ▸ Linking RHAReferralCalculator
[18-10-07 21:03:25.514] (CLI)  ▸ Linking RHAReferralCalculator
[18-10-07 21:03:25.514] (CLI)  ▸ Running script 'NativeScript PreLink'
[18-10-07 21:03:25.514] (CLI)  ▸ Copying InfoPlist.strings
[18-10-07 21:03:25.514] (CLI)  ▸ Compiling LaunchScreen.storyboard
[18-10-07 21:03:32.810] (CLI) ▸ Processing RHAReferralCalculator-Info.plist
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)     /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)      /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
[18-10-07 21:03:32.810] (CLI)     /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
[18-10-07 21:03:34.359] (CLI) ▸ Copying /tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator/node_modules/tns-core-modules-widgets/platforms/ios/TNSWidgets.framework
[18-10-07 21:03:34.359] (CLI)  ▸ Signing DerivedData/RHAReferralCalculator/Build/Intermediates.noindex/ArchiveIntermediates/RHAReferralCalculator/InstallationBuildProductsLocation/Applications/RHAReferralCalculator.app/Frameworks/TNSWidgets.framework
[18-10-07 21:03:35.932] (CLI) ▸ Running script 'NativeScript PostBuild'
[18-10-07 21:03:37.699] (CLI) ▸ Touching RHAReferralCalculator.app
[18-10-07 21:03:37.699] (CLI)  ▸ Signing DerivedData/RHAReferralCalculator/Build/Intermediates.noindex/ArchiveIntermediates/RHAReferralCalculator/InstallationBuildProductsLocation/Applications/RHAReferralCalculator.app
[18-10-07 21:03:37.699] (CLI)  ▸ Touching RHAReferralCalculator.app.dSYM
[18-10-07 21:03:37.699] (CLI)  ▸ Archive Succeeded
[18-10-07 21:03:37.699] (CLI)  Creating exportOptions.plist file ...
[18-10-07 21:03:37.699] (CLI)  Exporting .xcarchive to .ipa ...
[18-10-07 21:03:38.993] (CLI) Created bundle at path '/var/folders/gw/99dy3s510zq6qr3b7llq4y540000gp/T/RHAReferralCalculator_2018-10-07_21-03-40.221.xcdistributionlogs'.
[18-10-07 21:03:41.911] (CLI) Exported RHAReferralCalculator.xcarchive to: /tmp/builds/_/98bbd3f61a6815fceb461f3504bb11982761e665/4.0.2/4.0.1/RHAReferralCalculator
[18-10-07 21:03:41.911] (CLI)  ** EXPORT SUCCEEDED **
[18-10-07 21:03:41.911] (CLI)  Moving resulting <TemplateAppName>.ipa to app.ipa ...
[18-10-07 21:03:41.911] (CLI) /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2BFR9L55Q8TX5/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/UIKit-2LM3EQU7VVY4O.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Darwin-MI6WZSG1PNOM.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Foundation-A3SOD99KJ0S9.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/Dispatch-12O7S7HHQXK9N.pcm: No such file or directory
[18-10-07 21:03:41.911] (CLI) [xcode-build] /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/AKLQJDH2Y6SE/ObjectiveC-2CD0WTQVXITO7.pcm: No such file or directory
[18-10-07 21:03:43.529] (CLI) Build finished successfully
[18-10-07 21:03:49.748] Build step completed.
[18-10-07 21:03:49.761] (CLI) Finished cloud build of 'C:\World Perfect LLC\RHAReferralCalculator', platform: 'iOS', configuration: 'Debug', buildId: faade02c-0d9c-497d-abf2-4407e1969d6d successfully. Downloading result...
[18-10-07 21:03:49.770] Download step started.
