### ISSUE TITLE
Nativescript Does Not Publish to App Store

### ISSUE THREAD

**Issue by PacSD** [NativeScript/sidekick-feedback#284]
### Did you verify whether this issue has already been reported here?
_Yes/

### Tell us about the problem
_When I use the Publish function, it builds successfully, but hangs on the step "Starting Publishing"

### Which platform(s) does the issue occur on?
_Windows 10 Prio_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop Version: 1.13.0-v.2018.10.5.2 (latest)** 
- **NativeScript CLI: 4.2.3** 
- **CLI extension nativescript-cloud: 1.14.0** 
- **CLI extension nativescript-starter-kits: 0.3.5** 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application, open the project ..
2. Click Publish button
3. Select to build IOS, provide pwd for cert
4. Build completes successfully, enter Apple id/pwd at prompt, 
5. Log reports (CLI) Starting Publishing.  Then hangs.  After half an hour or so, various socket errors come back, timeouts I guess.  At this point I have to kill Sidekick and restart it.

NOTE:  I have used a third party tool to successfully publish the .ipa file to the App Store, so I have eliminated any issues there.  

### Does this issue happen every time?
_Yes

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

**Comment by ggarabedian** [comment]
Hello @PacSD,

This problem seems to be related to network connectivity issues with the AWS, which based on the [AWS Service Health Dashboard](https://status.aws.amazon.com/) are still not resolved. 

Yesterday, I was able to reproduce the hanging on publish sporadically (3 out of 5 publishes) and it seems that the issue still exists. We will have to wait for Amazon to fix their connectivity issues and this should in turn resolve the publishing problem in Sidekick.

**Comment by PacSD** [comment]
I checked the AWS status page today, and tried another publish.  The status page said everything was okay, but the publish still hung up.  This is still an open issue with SideKick.  Here is the last part of the log, you can see that it set for an hour and a half and did not finish.  Eventually you get the socket timeouts.

[18-10-22 13:44:33.325] (CLI) Build finished successfully
[18-10-22 13:44:44.207] Build step completed.
[18-10-22 13:44:44.213] (CLI) Finished cloud build of 'C:\Users\EdLance\Documents\NativeScript\CompassQMS', platform: 'iOS', configuration: 'Release', buildId: e7db5a65-dffb-417c-8a69-4bc9ea3a0735 successfully. Downloading result...
[18-10-22 13:44:44.218] Download step started.
[18-10-22 13:44:46.510] Download step completed.
[18-10-22 13:44:46.514] (CLI) The result of cloud build of 'C:\Users\EdLance\Documents\NativeScript\CompassQMS', platform: 'iOS', configuration: 'Release', buildId: e7db5a65-dffb-417c-8a69-4bc9ea3a0735 successfully downloaded. OutputFilePath: C:\Users\EdLance\Documents\NativeScript\CompassQMS\.cloud\ios\device\CompassQMS.ipa
[18-10-22 13:49:19.110] (CLI) Starting publishing.
[18-10-22 15:26:33.723] Checking for updates...
[18-10-22 15:26:34.462] No updates available.
[18-10-22 15:29:23.731] (CLI) (node:17596) Error: connect ETIMEDOUT 52.216.101.211:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by ggarabedian** [comment]
@PacSD, apologies for the delayed response. The IP in the provided timeout error is still coming from Amazon and I am not sure why they would mark the issue in their infrastructure as resolved before it actually is.

Having said that, I have tested the publish functionality today and it appears to be working normally once again. Can you please confirm if you no longer experience issues when publishing through Sidekick?

**Comment by PacSD** [comment]
@ggarabedian - Publish still does not work.  I don't see how it ever works for you.  I just did another and you can see that it hangs for 25 minutes, then the timeout errors occur:

[18-11-02 09:40:19.126] Download step started.
[18-11-02 09:40:21.139] Download step completed.
[18-11-02 09:40:21.142] (CLI) The result of cloud build of 'C:\Users\EdLance\Documents\NativeScript\CompassQMS', platform: 'iOS', configuration: 'Release', buildId: 93a617c3-a945-4177-9611-e7cf3206cbe4 successfully downloaded. OutputFilePath: C:\Users\EdLance\Documents\NativeScript\CompassQMS\.cloud\ios\device\CompassQMS.ipa
[18-11-02 09:41:59.931] (CLI) Starting publishing.
[18-11-02 10:04:55.343] (CLI) (node:31844) Error: connect ETIMEDOUT 54.231.115.3:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[18-11-02 10:05:31.480] (CLI) (node:31844) Error: connect ETIMEDOUT 52.216.105.99:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[18-11-02 10:05:50.991] (CLI) (node:31844) Error: connect ETIMEDOUT 52.216.230.251:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[18-11-02 10:06:03.000] (CLI) (node:31844) Error: connect ETIMEDOUT 52.216.105.99:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
[18-11-02 10:08:00.097] (CLI) (node:31844) Error: connect ETIMEDOUT 52.216.80.152:443
at Object.exports._errnoException (util.js:1020:11)
at exports._exceptionWithHostPort (util.js:1043:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

**Comment by ggarabedian** [comment]
@PacSD, I did several tests with sample apps and the publish worked each and every time. Additionally, we have another issue related to the same service from last week (#291) and the person who opened it was able to publish successfully. 

Does by any chance your Apple account have two factor authentication enabled? We currently do not work with Apple accounts that have a two factor authentication enabled. Usually, there is a descriptive message instead of a timeout error, however, it's still possible that you are experiencing an issue related to that.

**Comment by PacSD** [comment]
Well that's it then.  Yes my account has 2FA.  It is required by Apple in order to get in to the dev site and app store connect.  We have no choice in the matter.  I suppose those of you who had accounts set up before they made that requirement aren't affected, but any new account, including ours requires 2FA.

Given that is the direction Apple is going, I hope you include support for that for publishing with NativeScript.  The third party tool I use does support 2FA, so I know it can be done.

Thanks

**Comment by ShyshkovOleg** [comment]
Hi, everyone. Could not publish to AppStore too. The error is:
Error: The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>ZTkwYmUyYzMtZDU3Mi00ZmRjLTYyNGUtMjYzZjE3ZDU5Mzgz/results.json</Key><RequestId>F9007BB945AF18DC</RequestId><HostId>1S4OFClrPxpqNQjJqJMk8hHebwjSJxv/+7vMO6OjomqDZlhqib9cuavgQebJ8iOZ+/kqVoYdGYM=</HostId></Error>

Is there an issue with AWS or I've missed something ?

**Comment by tsonevn** [comment]
Hi all,
Can you check if you will have an issue with publishing to App Store while using latest SideKick?

**Comment by PacSD** [comment]
Sorry, we are not in a dev cycle with that project at the moment.  The problem lies with our Apple ID having multi-factor authentication enabled (required by Apple), so if you haven't developed a specific fix for that, our results would be the same.

Ed Lance


http://pacsdinc.com

________________________________
