### ISSUE TITLE
NO SPACE LEFT ON DEVICE (Android)

### ISSUE THREAD

**Issue by Vipul1546** [NativeScript/sidekick-feedback#285]
Hi,

I am using a drawer Navigation template. I just changed some text and facing this error. 
I am getting below error when I create local debug build. I have space left on both phone and system. This only works when I restart the system. After some time is again giving an error. Also, when I close the sidekick then sidekick won't start until I restart the system. Please help

DEVICE: Oneplus 5
System: Ubuntu 18.04

[18-10-20 20:02:36.668] (CLI) events.js:167
throw er; // Unhandled 'error' event
^
Error: ENOSPC: no space left on device, watch '/home/vipul/projects/Vipul/thewordbyte/app/App_Resources/iOS/Assets.xcassets/LaunchScreen.Center.imageset/LaunchScreen-Center@2x.png'
at FSWatcher.start (internal/fs/watchers.js:161:26)
at Object.watch (fs.js:1227:11)
at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
at setFsWatchListener (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:255:21)
at FSWatcher.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:473:21)
at FSReqWrap.oncomplete (fs.js:159:5)
Emitted 'error' event at:
at FSWatcher._handleError (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/index.js:257:10)
at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:39:5)
at setFsWatchListener (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[... lines matching original stack trace ...]
at FSReqWrap.oncomplete (fs.js:159:5)
[18-10-20 20:02:36.771] Build failed. Communication with the child process was ended.
[18-10-20 20:05:18.552] (CLI) events.js:167
throw er; // Unhandled 'error' event
^
Error: ENOSPC: no space left on device, watch '/home/vipul/projects/Vipul/thewordbyte/app/App_Resources/iOS/Assets.xcassets/LaunchImage.launchimage/Default-1125h.png'
at FSWatcher.start (internal/fs/watchers.js:161:26)
at Object.watch (fs.js:1227:11)
at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:37:15)
at setFsWatchListener (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:228:14)
at FSWatcher.NodeFsHandler._handleFile (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:255:21)
at FSWatcher.<anonymous> (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:473:21)
at FSReqWrap.oncomplete (fs.js:159:5)
Emitted 'error' event at:
at FSWatcher._handleError (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/index.js:257:10)
at createFsWatchInstance (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:39:5)
at setFsWatchListener (/usr/local/lib/node_modules/nativescript/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[... lines matching original stack trace ...]
at FSReqWrap.oncomplete (fs.js:159:5)
[18-10-20 20:05:18.595] Build failed. Communication with the child process was ended.

Please let me know if i missed somethig.
Thanks

**Comment by ggarabedian** [comment]
@Vipul1546, there are several issues that can lead to this error when using Sidekick on a Linux system. Can you please check the [suggestions made by NickIliev](https://github.com/NativeScript/nativescript-cli/issues/2876#issuecomment-306178974) regarding a similar issue with the NativeScript CLI and let me know if any of them helps you to resolve the problem.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
