### ISSUE TITLE
iOS cloud build fails after 5.0 upgrade

### ISSUE THREAD

**Issue by simplec-dev** [NativeScript/sidekick-feedback#307]
I just updated to NS 5.0 because of a sidekick upgrade.

I'm trying to build an app that was building ok last time I needed a build -- about a month ago, maybe more.

The local Android build runs fine.  When I run an iOS build, I get this:
[18-12-06 16:34:26.390] Upload step completed.
[18-12-06 16:34:27.009] Build step started.
[18-12-06 16:34:31.249] (CLI) internal/streams/legacy.js:59
[18-12-06 16:34:31.249] (CLI)       throw er; // Unhandled stream error in pipe.
[18-12-06 16:34:31.249] (CLI)       ^
[18-12-06 16:34:31.249] (CLI) Error: getaddrinfo ENOTFOUND livesync.ly livesync.ly:443
[18-12-06 16:34:31.249] (CLI)     at errnoException (dns.js:50:10)
[18-12-06 16:34:31.249] (CLI)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

I found another issue from October where the poster said he created a new certificate and provisioning profile.  That didn't help me.  I'm getting this with all 4 of the apps I build using iOS cloud builds.

**Comment by ggarabedian** [comment]
Hello @simplec-dev, 

the reported error is not related to your upgrade to 5.0, but to a temporary problem with our cloud infrastructure. We have made the nessecary corrections to resolve the issue, however, you might be required to [Clear Your Local DNS Cache](https://documentation.cpanel.net/display/CKB/How+To+Clear+Your+DNS+Cache) before you are able to build in the cloud.

Please, let me know if this helps.

**Comment by sepccom** [comment]
Hi, I tried the link but I still can not build an IOS project.
https://github.com/NativeScript/sidekick-feedback/issues/326#issuecomment-453101770

**Comment by NickIliev** [comment]
@sepccom if you still have troubles making an iOS cloud build then please provide as much information as possible (are you receiving the same error, is this happening with a specific project or with any project you try to build, are you using the latest version of CLI and Sidekick, etc.)

Closing this issue due to inactivity, but if your issue persists then open a new one with the requested details.
