### ISSUE TITLE
Cannot run NativeScript sidekick anymore

### ISSUE THREAD

**Issue by sandoche** [NativeScript/sidekick-feedback#320]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I can't run nativescript sidekick at all. I get this error.
```
[18-12-29 11:28:18.975] (Error) ab.childProcessCommunication.shell.cliStderr - events.js:183
      throw er; // Unhandled 'error' event
      ^
```

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:
Version: 1.14.1-v.2018.11.23.3 (latest)
NativeScript CLI version: 5.0.2
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. I just managed to run my app on an iPad (I opened another issue)
2. Then the livereload crashed so I closed NativeScript Sidekick
3. I reopened it and this error occured (cf logs)
4. I tried to uninstall / resinstall, and even to delete this folder `%AppData%\NativeScriptSidekick\` and same thing happen again and again, I tried also to reboot.

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/sandoche/4e96f2a9c70aefbefb5f50c990ffae02

**Comment by sandoche** [comment]
Actually when I run `tns device` I get this.
```
PS D:\Sandoche\00 - Projects\gitnews> tns device

Connected devices & emulators
Searching for devices...
Error: spawn C:\Users\Sandoche\AppData\Roaming\npm\node_modules\nativescript\node_modules\ios-device-lib\bin\win32\x64\ios-device-lib ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
