### ISSUE TITLE
Error uploading to amazonaws after .ipa file is downloaded

### ISSUE THREAD

**Issue by throwingdarts** [NativeScript/sidekick-feedback#321]
I am continuously getting an "The request can't receive any response." message when trying to upload a production app that builds fine. Is this a network error with AWS?

... redacted ...

[18-12-30 18:49:21.169] Download step started.
[18-12-30 18:50:28.706] Download step completed.
[18-12-30 18:50:28.711] (CLI) The result of cloud build of 'D:\Projects\HBS\mobile\hbs', platform: 'iOS', configuration: 'Release', buildId: 38349cda-d03c-4cf0-bf21-521401c39355 successfully downloaded. OutputFilePath: D:\Projects\HBS\mobile\hbs\.cloud\ios\device\hbs.ipa
[18-12-30 18:52:44.324] (CLI) The request can't receive any response. Retrying request to https://sk-builds-us-east-1-v3-production.s3.amazonaws.com/...
[18-12-30 18:53:44.326] Error while uploading D:\Projects\HBS\mobile\hbs\.cloud\ios\device\hbs.ipa to S3. Errors is: The request can't receive any response., Error: Error while uploading D:\Projects\HBS\mobile\hbs\.cloud\ios\device\hbs.ipa to S3. Errors is: The request can't receive any response.
at Errors.fail (C:\Users\mbull\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:125:28)
at UploadService.<anonymous> (C:\Users\mbull\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\upload-service.js:46:30)
at Generator.throw (<anonymous>)
at rejected (C:\Users\mbull\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\upload-service.js:5:65)
at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by ggarabedian** [comment]
@throwingdarts, thank you for sharing the produced log. It seems that we have introduced a bug with one of our previous releases and projects that produce a larger IPA might fail with the reported error. We are currently working on resolving the issue and we expect the fix to be present in our next release.

In the meantime, as a temporary workaround, you should be able to build successfully by increasing a specific timeout in the code of the NativeScript CLI. To do this, you should:
1. Open a _File Explorer_ and navigate to `%appdata%\npm\node_modules\nativescript\lib\common\`.
2. Open the `http-client.js` file with a code editor.
3. Locate line _**291**_ - `HttpClient.STUCK_REQUEST_TIMEOUT = 60000;` and increase the timeout by adding 1 or 2 zeroes at the end. For example, make the number `6000000`.

This change should let you build successfully until we release our fix.

**Comment by throwingdarts** [comment]
Thanks. The work-around was successful.

**Comment by SoSimpull** [comment]
I am receiving an error like this also since the last update.  My issue happens when trying to upload the build to S3 when publishing with the cloud or trying debug build with the cloud.  I am not sure if it is the exact same issue as this one but could be the same symptom. 

Reported Here
https://github.com/NativeScript/sidekick-feedback/issues/339

**Comment by throwingdarts** [comment]
@ggarabedian, once again getting this same error when trying to publish. Can you investigate asap? Holding us up again. Thanks.
