### ISSUE TITLE
iOS Auto Generate Provisioning Profile and Certificate - error

### ISSUE THREAD

**Issue by Steinholf** [NativeScript/sidekick-feedback#328]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem
I have created a new blank app and tried Auto generating Provisioning Profile and Certificate using a newly created apple account without two factor authentication.

Every time it tried to generate the provisioning profile and certificate it throws the following error:
"An error has occured while generating the certificate and mobile provision. Reason: Cannot read property 'provisioningProfileId' of undefined."

I was unable to find any information about this.

### Which platform(s) does the issue occur on?
_Windows_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.14.1-v.2018.11.23.3 (latest)
- **NativeScript CLI:** 5.1.0
- **CLI extension nativescript-cloud:** 1.15.0
- **CLI extension nativescript-starter-kits:** 0.3.5

### Does this issue happen every time?
_Yes_

### Send the client logs
>_[19-01-14 11:54:52.163] (Error) ab.codeSigning.shell.generateiOSCodeSignFiles - An error has occured while generating the certificate and mobile provision. Reason: Cannot read property 'provisioningProfileId' of undefined., Error: Codesign failed. Reason is: Cannot read property 'provisioningProfileId' of undefined.
    at CloudCodesignService.<anonymous> (C:\Users\Admin\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-codesign-service.js:87:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Admin\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-codesign-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)_

**Comment by Steinholf** [comment]
Ended up being because of an outdated version of iTunes so the device connected wasn't recognized properly
