### ISSUE TITLE
App Store Publishing Error - NoSuchKey, The specified key does not exist.

### ISSUE THREAD

**Issue by throwingdarts** [NativeScript/sidekick-feedback#330]
### Did you verify whether this issue has already been reported here?
Yes, but is an apparent sidekick known issue.

### Tell us about the problem
When publishing on app store I am getting a NoSuchKey error message after I supply my apple dev credentials to upload. Seems to build ok.

`[19-01-21 09:33:41.866] (CLI) Starting publishing.
[19-01-21 09:40:18.989] The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>MmFlNzAwMzUtY2U4My00YWRhLTUzZDYtYWMxZTBiNTQxODI5/results.json</Key><RequestId>769F71FEBD6A5AEF</RequestId><HostId>t8iA8h2nfUEHG63D19kYKWpg0ZaGc50tG+MG2DFKw9ZYfWRv1wlNGbj+3d9jkyfax111gJP7ADY=</HostId></Error>, Error: The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>MmFlNzAwMzUtY2U4My00YWRhLTUzZDYtYWMxZTBiNTQxODI5/results.json</Key><RequestId>769F71FEBD6A5AEF</RequestId><HostId>t8iA8h2nfUEHG63D19kYKWpg0ZaGc50tG+MG2DFKw9ZYfWRv1wlNGbj+3d9jkyfax111gJP7ADY=</HostId></Error>
    at IncomingMessage.responseStream.on (C:\Users\mbull\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\http-client.js:186:45)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:**
Version: 1.15.0-v.2019.1.18.17 (latest)
 
- **NativeScript CLI:** 
NativeScript CLI version: 5.1.1

- **CLI extension nativescript-cloud:** 
CLI extension nativescript-cloud version: 1.15.2

- **CLI extension nativescript-starter-kits:** 
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
Publish  app via Sidekick

### Does this issue happen every time?
Yes

### Send the client logs
[main_19-01-21_09-17-08.579.log](https://github.com/NativeScript/sidekick-feedback/files/2779704/main_19-01-21_09-17-08.579.log)
[console_19-01-21_09-17-06.221.log](https://github.com/NativeScript/sidekick-feedback/files/2779705/console_19-01-21_09-17-06.221.log)
![app-store-issue](https://user-images.githubusercontent.com/10662952/51486600-bf029d00-1d66-11e9-89fb-aa991a9b24d3.jpg)

**Comment by ggarabedian** [comment]
@throwingdarts and @kapiltiwari61, thank you for reporting this issue.

The error was related to a temporary problem in our cloud infrastructure. We have taken the necessary steps to resolve the issue and you should no longer experience this error when publishing applications.

**Comment by kapiltiwari61** [comment]
Now getting some different issue.
![screen shot 2019-01-22 at 3 04 01 pm](https://user-images.githubusercontent.com/29888626/51525827-1da74400-1e57-11e9-9131-6dfd3a0fc425.png)
```
[19-01-22 15:03:07.608] Cannot read property 'match' of undefined, TypeError: Cannot read property 'match' of undefined
    at CloudPublishService.getFormattedError (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:138:31)
    at CloudPublishService.getiOSError (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:80:34)
    at CloudPublishService.<anonymous> (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:105:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-publish-service.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


```

**Comment by throwingdarts** [comment]
@ggarabedian - the fix worked for me. Thanks.
