### ISSUE TITLE
Install NS 5.2 now won't build

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#345]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When I try to run on device, it won't install or run. I get this error:

[19-02-15 21:51:24.125] Error detected during LiveSync on 10374e1cfeaa6b9c878973af885c33280cb34fe5 for /Users/brice/source/class2tns. Error: Failed to install /Users/brice/source/class2tns/.cloud/ios/device/class2tns.ipa on device with identifier 10374e1cfeaa6b9c878973af885c33280cb34fe5. Error is: Could not install application

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:

Version: 1.16.0-v.2019.2.7.3 (latest)
NativeScript CLI version: 5.2.0
CLI extension nativescript-cloud version: 1.16.0
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
Run on Device from within Sidekick
If I run from the command line I get this error:

Error Domain=IDEProvisioningErrorDomain Code=8 "binding.node has conflicting provisioning settings." UserInfo={NSLocalizedDescription=binding.node has conflicting provisioning settings., NSLocalizedRecoverySuggestion=binding.node is automatically signed for distribution, but a conflicting code signing identity iPhone Developer has been manually specified. Remove the "signingCertificate" entry from your Export Options property list, or switch to manual signing by setting "signingStyle" to "Manual.}

This does not happen when I run to an emulator

### Does this issue happen every time?
Yes

### Send the client logs
[main_19-02-15_21-40-48.626.log](https://github.com/NativeScript/sidekick-feedback/files/2871541/main_19-02-15_21-40-48.626.log)
[console_19-02-15_21-40-43.609.log](https://github.com/NativeScript/sidekick-feedback/files/2871542/console_19-02-15_21-40-43.609.log)

**Comment by gitllermopalafox** [comment]
Hi, I don't know if my problem is related, but since a few hours I can't build iOS on cloud...

I first tried with NS 5.1.0 and then upgrade to NS 5.2 in both versions the error is the same.

This is the error:

https://gist.github.com/gitllermopalafox/d39fadbf95d8a698002e3f77fe8f7663

**Comment by bradrice** [comment]
I've completely rebuilt my cert and provision file just in case something was wrong there. Now I'm getting this error:

[19-02-18 10:04:29.611] {"deviceIdentifier":"10374e1cfeaa6b9c878973af885c33280cb34fe5","deviceName":"ToolingU's iPad mini","device":{"identifier":"10374e1cfeaa6b9c878973af885c33280cb34fe5","vendor":"Apple","platform":"iOS","status":"Connected","errorHelp":null,"type":"Device","isTablet":true,"displayName":"ToolingU's iPad mini","model":"iPad mini (Wi-Fi)","version":"9.3.5","color":"white","activeArchitecture":"armv7"},"error":{"name":"Exception","message":"Failed to install /Users/brice/source/class2tns/.cloud/ios/device/class2tns.ipa on device with identifier 10374e1cfeaa6b9c878973af885c33280cb34fe5. Error is: Could not install application","stack":"Error: Failed to install /Users/brice/source/class2tns/.cloud/ios/device/class2tns.ipa on device with identifier 10374e1cfeaa6b9c878973af885c33280cb34fe5. Error is: Could not install application\n    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:125:28)\n    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:135:21)\n    at $iosDeviceOperations.install (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-application-manager.js:45:30)\n    at IOSDeviceOperations.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device-operations.js:206:25)\n    at Generator.throw (<anonymous>)\n    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/mobile/ios/device/ios-device-operations.js:11:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","errorCode":127,"suppressCommandHelp":true,"proxyAuthenticationRequired":false}}
OUTPUT 1

**Comment by bradrice** [comment]
I've found I can open the platform/ios file in Xcode and run it to the device. It corrects a number of things of which I am unsure of what it is doing. However, I need to build and submit to the apple store for Test Flight distribution. It would be nice if I could do that in Sidekick. I did do it several times using sidekick, but for some reason after updating to TNS 5.2 I can't get anything to work other than running in the simulator. I can't run it to a deivice and I can't build for deployment.

**Comment by bradrice** [comment]
I've found that I cannot build out to a device running ios 9. How do I find where the limitation comes from? In Properties I set a deployment target of 9.0, but it fails when I build to a device running this operating system version.

**Comment by ggarabedian** [comment]
@bradrice, apologies for not responding to your previous inquiries. It looks like you were able to resolve them without our help.

The last issue that you have mentioned might be related to provisioning or the type of device and not the iOS version. With this in mind, you should check if your mobile provision contains the iPad device on which you are trying to deploy the app. 

Additionally, if the `<app-name>\.cloud` folder contains an IPA built for an iPhone device, Sidekick might be attempting to install it directly to the iPad device, which in most cases won't work. Having said that, you should delete the `.cloud` folder and see if this resolves the issue.

If none of the above helps, can you share more information about your app (for example, the `package.json` file), so we can attempt to reproduce the issue locally?

**Comment by bradrice** [comment]
Yes, I was never able to get my app to compile for ios9. I have a gist of my package.json here:

https://gist.github.com/bradrice/8b42a5c4ebee6fad2527605cdc03e48a

**Comment by ggarabedian** [comment]
@bradrice, thank you for sharing the `package.json` file. The issue doesn't seem to be related to the plugins or runtime you use, because I am able to build successfully even after setting the Deployment Target to 9.0 or 8.0. I am testing on a couple of iPhone devices running iOS 10.2.1 and 12.1.4 and an iPad running iOS 9.3.5. 

The only way in which I am able to reproduce the issue is when the mobile provision does not contain the specific device. At this point, the only recommendation we can give is for you to double check if the mobile provision contains the device in question.

**Comment by bradrice** [comment]
I am still unable to run or deploy to my iPad running 9.3.5.

I have also tried running from the command line with log trace. Here are the relevant error lines:

`Build system information
error: /Users/brice/source/class2tns/platforms/ios/class2tns/build-debug.xcconfig:3: could not find included file '../plugins-debug.xcconfig' in search paths (in target 'class2tns')

Build system information
error: /Users/brice/source/class2tns/platforms/ios/class2tns/build-debug.xcconfig:3: could not find included file '../plugins-debug.xcconfig' in search paths (in target 'class2tns')

Build system information
error: /Users/brice/source/class2tns/platforms/ios/class2tns/build-debug.xcconfig:3: could not find included file '../plugins-debug.xcconfig' in search paths (in target 'class2tns')

** ARCHIVE FAILED **

Command xcodebuild failed with exit code 65
Unable to apply changes on device: 10374e1cfeaa6b9c878973af885c33280cb34fe5. Error is: Command xcodebuild failed with exit code 65.
Will emit event liveSyncError with data { error:
   { Error: Command xcodebuild failed with exit code 65
       at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:126:28)
       at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:136:21)
       at IOSProjectService.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/services/ios-project-service.js:378:30)
       at Generator.throw (<anonymous>)
       at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/services/ios-project-service.js:5:65)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'Exception',
     message: 'Command xcodebuild failed with exit code 65',
     stack:
      'Error: Command xcodebuild failed with exit code 65\n    at Errors.fail (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:126:28)\n    at Errors.failWithoutHelp (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/common/errors.js:136:21)\n    at IOSProjectService.<anonymous> (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/services/ios-project-service.js:378:30)\n    at Generator.throw (<anonymous>)\n    at rejected (/Users/brice/.nvm/versions/node/v10.13.0/lib/node_modules/nativescript/lib/services/ios-project-service.js:5:65)\n    at process._tickCallback (internal/process/next_tick.js:68:7)',
     errorCode: 127,
     suppressCommandHelp: true,
     proxyAuthenticationRequired: false,
     printOnStdout: undefined },
  deviceIdentifier: '10374e1cfeaa6b9c878973af885c33280cb34fe5',
  projectDir: '/Users/brice/source/class2tns',
  applicationIdentifier: 'com.toolingu.class2tns' }`

**Comment by bradrice** [comment]
I have deleted all my provisioning profiles, created a new one for this device only and downloaded it and associated it with Nativescript Sidekick. Regardless of what I do, it will not deploy to the device. I keep getting "requires a provisioning profile" error:

`[19-04-30 11:32:36.865] Error detected during LiveSync on 10374e1cfeaa6b9c878973af885c33280cb34fe5 for /Users/brice/source/class2tns. Error: Command xcodebuild failed with exit code 70 Error output: 
 2019-04-30 11:32:36.098 xcodebuild[15749:916407] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/0h/xjv_gy2j0m1gdmc1tx_707480000gp/T/class2tns_2019-04-30_11-32-36.097.xcdistributionlogs'.
error: exportArchive: "class2tns.app" requires a provisioning profile.
Error Domain=IDEProvisioningErrorDomain Code=9 ""class2tns.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="class2tns.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Add a profile to the "provisioningProfiles" dictionary in your Export Options property list.}
`
