### ISSUE TITLE
Auto Generation Failed MergeMapSubscriber.api.cliServiceShell.generateCodesignFiles.catch.flatMap [as project] - param is missing or invalid

### ISSUE THREAD

**Issue by jericopulvera** [NativeScript/sidekick-feedback#348]
### Did you verify whether this issue has already been reported here?
No

### Tell us about the problem
I'm trying to Auto Generate iOS Provisioning and Certificates using a free developer account, and I'm getting this error 
```
Auto Generation Failed
MergeMapSubscriber.api.cliServiceShell.generateCodesignFiles.catch.flatMap [as project] - param is missing or invalid
```

### Which platform(s) does the issue occur on?
IOS (12) <br/>
macOS(10.14.3)

### Provide the following version numbers that the issue occurs with:
NativeScript Sidekick 1.16.0-v.2019.2.7.3

### Tell us how to recreate the issue in as much detail as possible
1. Create an app using sidekick with vue template.
2. Click the cog wheel on your connected ios device.
3. Click auto generate 

### Does this issue happen every time?
Yes

### Send the client logs
```
[19-02-28 01:46:49.233] MergeMapSubscriber.api.cliServiceShell.generateCodesignFiles.catch.flatMap [as project] - param is missing or invalid, Error: MergeMapSubscriber.api.cliServiceShell.generateCodesignFiles.catch.flatMap [as project] - param is missing or invalid
    at ValidationService.error (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar/shared/core/validation-service.js:10:15)
    at args.forEach (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar/shared/core/validation-service.js:18:22)
    at Array.forEach (native)
    at ValidationService.areDefined (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar/shared/core/validation-service.js:14:14)
    at MergeMapSubscriber.api.cliServiceShell.generateCodesignFiles.catch.flatMap [as project] (/Applications/NativeScript Sidekick.app/Contents/Resources/app.asar/modules/code-signing/apple-automation-controller.js:74:43)
    at MergeMapSubscriber._tryNext (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/Subscriber.js:93:18)
    at CatchSubscriber.Subscriber._next (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/Subscriber.js:129:26)
    at CatchSubscriber.Subscriber.next (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/Subscriber.js:93:18)
    at /Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/rxjs/observable/PromiseObservable.js:66:36
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by ggarabedian** [comment]
@jericopulvera, thank you for reporting this issue. The error is not related to the actual generation of the code signing assets (they are created successfully), but to the process that assigns them in the certificate and provision fields in Sidekick.

We will investigate and fix this in our next version of Sidekick, but in the meantime, you can manually assign the temporary certificate and provision by following these steps:
1. Open your app in Sidekick.
2. In the **Devices** -> **Connected** section open the **Manage iOS Provisioning and Certificates** dialog for the specific device by clicking on the settings icon next to it.
3. Browse and select the temporary certificate and provision, which are located in the `<app-name>\codesign_files\ios\` folder. 
4. Run the app on the connected device.

I hope this temporary workaround helps.

**Comment by jericopulvera** [comment]
Hi @ggarabedian tried what you suggested and I think it should be working now but now I am getting a different error. After assigning the cert and provision. I run the device which is my iphone connected on my mac. Then I get this error.

```
[19-03-01 00:15:17.675] Error detected during LiveSync on 55f34751ae5d6668698b08efb6ff78cc8cf865d6 for /Users/eco/Code/ChatP. Error: Command xcodebuild failed with exit code null Error output: 
 2019-03-01 00:15:17.658 xcodebuild[76741:276954] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-14460.26/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/RuntimeSupport/MacroExpansion/XCMacroExpansionExtensions.mm:94
Details:  Assertion failed: [value isKindOfClass:[NSString class]] || [value isKindOfClass:[NSArray class]]
Object:   <DVTMacroDefinitionTable: 0x7fe265718710>
Method:   -_xc_setValue:forMacroName:conditionSet:errorHandler:
Thread:   <NSThread: 0x7fe262d15a20>{number = 1, name = main}
Hints: 
Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:conditionSet:errorHandler:] (in DevToolsCore)
  5   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) _xc_setValue:forMacroName:errorHandler:] (in DevToolsCore)
  6   __108-[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:]_block_invoke (in DevToolsCore)
  7   -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] (in CoreFoundation)
  8   -[DVTMacroDefinitionTable(XCMacroExpansionExtensions) xc_setMacroNamesAndValuesFromDictionary:errorHandler:] (in DevToolsCore)
  9   +[DVTMacroDefinitionTable(XCProjectArchivingExtensions) xc_macroDefinitionTableFromDictionaryRepresentationForProjectArchiving:usingPropertyDefinitionsFromSpecificationDomain:] (in DevToolsCore)
 10   -[PBXBuildStyle _setBuildSettings:] (in DevToolsCore)
 11   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 12   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 13   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 14   -[PBXBuildStyle readFromPListUnarchiver:] (in DevToolsCore)
 15   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 16   -[PBXPListUnarchiver _decodeMutableObjectArrayFromPListArray:] (in DevToolsCore)
 17   -[PBXPListUnarchiver decodeMutableObjectArrayForKey:] (in DevToolsCore)
 18   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 19   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 20   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 21   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 22   -[PBXPListUnarchiver decodeObjectForKey:] (in DevToolsCore)
 23   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 24   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 25   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 26   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 27   -[PBXPListUnarchiver _decodeMutableObjectArrayFromPListArray:] (in DevToolsCore)
 28   -[PBXPListUnarchiver decodeMutableObjectArrayForKey:] (in DevToolsCore)
 29   -[PBXUnarchivingBinding readValueForObject:fromPListUnarchiver:] (in DevToolsCore)
 30   -[PBXObject _unarchiveValuesForArchiveMask:fromPListUnarchiver:] (in DevToolsCore)
 31   -[PBXObject readFromPListUnarchiver:] (in DevToolsCore)
 32   -[PBXProject readFromPListUnarchiver:] (in DevToolsCore)
 33   -[PBXPListUnarchiver _unarchiveObjectWithGlobalIDHexString:] (in DevToolsCore)
 34   -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
 35   +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
 36   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
 37   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
 38   _dispatch_client_callout (in libdispatch.dylib)
 39   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
 40   DVTDispatchBarrierSync (in DVTFoundation)
 41   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
 42   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
 43   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 44   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 45   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 46   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 47   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
```

**Comment by jericopulvera** [comment]
@ggarabedian. I understand it now why it's not working I'm using local build option and it needs a paid developer account to work. When I switched to cloud build it works. but It has a limit of 100 builds on free account.

If I run a cloud build on hmr does every change consumes a build?  Please confirm.

Thanks.

**Comment by ggarabedian** [comment]
@jericopulvera, apologies for the delayed response.

LiveSyncing with or without the HMR option will not consume cloud builds. Cloud builds are used up only when you initiate a `Clean build` or when you have made a change to the app that requires a full rebuild - for example, adding a new plugin to the app. The publish functionality also deducts cloud builds.

Additionally, it's strange to hear that local builds don't work with the temporary code signing assets. I'll try to reproduce the reported error and let you know if I identify what might be causing the problem.

**Comment by jericopulvera** [comment]
@ggarabedian It's great to hear that it is possible to develop without a developer account from apple.
