### ISSUE TITLE
Error message when trying to set the orientation of Android App

### ISSUE THREAD

**Issue by shiv19** [NativeScript/sidekick-feedback#35]
NativeScript SideKick version 2.1.2

When I tried to set the orientation of my app, for android to portrait,
I got this error message in the console.

[17-08-14 18:49:21.555] (Error) Source: event handler for "select" Message: Cannot read property 'value' of undefined, TypeError: Source: event handler for "select" Message: Cannot read property 'value' of undefined
    at a.onSelectRow (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:17242:46)
    at n (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:1169)
    at a.e (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:6233)
    at a.t.$emit (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:59016)
    at a.removeSelection (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:16330:30)
    at a.n [as removeSelection] (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:1181)
    at a.selectRow (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:16339:26)
    at a.n [as selectRow] (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:1169)
    at a.onClick (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:16384:30)
    at n (file:///C:/Users/Shiva/AppData/Local/NativeScriptSidekick/app-0.2.2-v2017893/resources/app.asar/ui/app.js:534:1169)

**Comment by Sevensnake** [comment]
I got this message also running android Mac saying cannot read property is userisloggedin undefined

**Comment by bundyo** [comment]
The fix is done, but the version containing it is not released yet. Expect it soon.

**Comment by Sevensnake** [comment]
Ok great. Thanks
