### ISSUE TITLE
Cloud build publishing issue

### ISSUE THREAD

**Issue by kapiltiwari61** [NativeScript/sidekick-feedback#350]
Unable to publish ios build.

Please find log.

```
19-03-01 19:56:28.457] Error while uploading /Users/jkt/Desktop/CDI/cdi_milestone6/cdinativescript/.cloud/ios/device/cdinativescript.ipa to S3. Errors is: The request can't receive any response., Error: Error while uploading /Users/jkt/Desktop/CDI/cdi_milestone6/cdinativescript/.cloud/ios/device/cdinativescript.ipa to S3. Errors is: The request can't receive any response.
    at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:125:28)
    at UploadService.<anonymous> (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/upload-service.js:45:30)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jkt/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/upload-service.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


 

```

**Comment by kapiltiwari61** [comment]
Please provide the solution for above issue. Its urgent as we have to deliver the app ASAP.

**Comment by tsvetie** [comment]
Hey @kapiltiwari61

I guess you are using NS CLI 5.1.1. Can you try updating NS CLI to the latest version (5.2.1) to see if this will fix the problem? In order to update NS CLI, run the following command in the Terminal:

```
npm install -g nativescript@latest
```

**Comment by throwingdarts** [comment]
#321

**Comment by NickIliev** [comment]
use the link posted by @throwingdarts to resolve this issue https://github.com/NativeScript/sidekick-feedback/issues/321#issuecomment-450659093
