### ISSUE TITLE
Sidekick keeps deleting project right after creating it

### ISSUE THREAD

**Issue by tukanoidd** [NativeScript/sidekick-feedback#352]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I'm trying to create Vue blank project. After some time I see the files generated by Sidekick but after a few seconds it just keeps removing all the files created by it.

### Which platform(s) does the issue occur on?
Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:**  1.16.1-v.2019.2.27.1
- **NativeScript CLI:** 5.2.0
- **CLI extension nativescript-cloud:** 1.17.1
- **CLI extension nativescript-starter-kits:**  0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Create App
3. Vue
4. Blank
5. Create

### Does this issue happen every time?
Yes

### Send the client logs
[19-03-04 04:30:34.478] (Info) ab.actionsLogger.shell.appVersion - {"name":"NativeScript Sidekick","version":"1.16.1-v.2019.2.27.1"}
[19-03-04 04:30:34.497] (Info) ab.analytics.shell.clientId - 1177399871.1551668541
[19-03-04 04:30:34.512] (Info) ab.appContext.shell.appContext - No value provided
[19-03-04 04:30:34.514] (Info) ab.appContext.shell.projectType - No value provided
[19-03-04 04:30:34.514] (Info) ab.appContext.shell.isProjectShared - No value provided
[19-03-04 04:30:34.553] (Info) ab.appValidityWatcher.shell.isAppValid - No value provided
[19-03-04 04:30:34.571] (Info) ab.autoUpdate.shell.updates - {"eventName":"checking-for-update","message":"Checking for updates..."}
[19-03-04 04:30:34.604] (Info) ab.buildDeploy.shell.buildConfigChanged - {"platform":null,"buildType":"Cloud","buildConfig":"Debug","isClean":false,"useSharedCloud":false,"webpack":{"isWebpack":false,"env":{"uglify":true,"snapshot":true,"aot":{"debug":false,"release":true},"sourceMap":false}},"isHmr":false}
[19-03-04 04:30:34.611] (Info) ab.buildDeploy.shell.isWebpackSupported - No value provided
[19-03-04 04:30:34.613] (Info) ab.buildDeploy.shell.isWebpackInPreviewSupported - No value provided
[19-03-04 04:30:34.616] (Info) ab.buildDeploy.shell.isWebpackRequired - No value provided
[19-03-04 04:30:34.617] (Info) ab.buildDeploy.shell.isAOTSupported - No value provided
[19-03-04 04:30:34.618] (Info) ab.buildDeploy.shell.isSourceMapsSupported - No value provided
[19-03-04 04:30:34.620] (Info) ab.buildDeploy.shell.isLiveSyncInProgress - true
[19-03-04 04:30:34.621] (Info) ab.buildDeploy.shell.isHMRSupported - No value provided
[19-03-04 04:30:34.625] (Info) ab.buildDeploy.shell.isSharedCloudFlagSupported - No value provided
[19-03-04 04:30:34.634] (Info) ab.certificateStore.shell.isSupported - true
[19-03-04 04:30:34.647] (Info) ab.codeSigning.shell.codeSigningChanged - {"ios":{},"android":{}}
[19-03-04 04:30:34.654] (Info) ab.codeSigning.shell.csrStore - {}
[19-03-04 04:30:34.689] (Info) ab.createApp.shell.lastUsedAppDirectory - {"appDirectory":"E:\\vitalik27062001@gmail.com\\University\\Classes\\Year 1\\Block 3\\Project Block 3"}
[19-03-04 04:30:34.719] (Info) ab.editor.shell.editorSettings - {"editorPath":"E:\\Microsoft VS Code Insiders\\Code - Insiders.exe","args":"{projectPath}"}
[19-03-04 04:30:34.747] (Info) ab.kinveyAuth.shell.configData - {"shouldConfigure":false}
[19-03-04 04:30:34.865] (Info) ab.preview.shell.playgroundAppQrCode - {}
[19-03-04 04:30:34.866] (Info) ab.preview.shell.appQrCode - {}
[19-03-04 04:30:34.867] (Info) ab.preview.shell.configuration - {"isWebpack":false,"isHmr":false}
[19-03-04 04:30:34.868] (Info) ab.preview.shell.previewAppWarnings - {}
[19-03-04 04:30:34.875] (Info) ab.privacy.shell.privacyConfig - {"skipTracking":true,"privacyPolicyUrl":"https://www.progress.com/legal/privacy-policy","intercomPrivacyPolicyUrl":"https://www.intercom.com/terms-and-policies#privacy","forgetMeUrl":"https://app.onetrust.com/app/#/webform/7897e80a-b8a4-4797-883a-bdacfe1ab8e4","unsubscribeUrl":"https://forms.progress.com/emailoptin","partnersUrl":"https://www.progress.com/partners/partner-directory","privacyInfoShown":true,"emailsAccepted":true}
[19-03-04 04:30:34.879] (Info) ab.proxy.shell.proxySettings - {}
[19-03-04 04:30:34.900] (Info) ab.subscriptions.shell.usageInfo - No value provided
[19-03-04 04:30:34.901] (Info) ab.subscriptions.shell.accountFeatures - []
[19-03-04 04:30:35.017] (Info) ab.userAccounts.shell.userAccountList - []
[19-03-04 04:30:35.021] (Info) ab.userAccounts.shell.activeUserAccount - No value provided
[19-03-04 04:30:35.148] (Info) ab.tnsDoctor.shell.checkDependencies - {"node":{"name":"NodeJS","version":"11.10.1","versionRange":">=8.0.0 <10.6.0 || >=10.10.0","versionToInstall":"8.11.3","isMet":true,"isAutoFixSupported":false},"npm":{"name":"npm","version":"6.7.0","isMet":true,"isAutoFixSupported":false},"tns":{"name":"NativeScript CLI","version":"5.2.0","versionRange":">=5.1.1","versionToInstall":"latest","isMet":true,"isAutoFixSupported":false}}
[19-03-04 04:30:35.769] (Info) ab.autoUpdate.shell.updates - {"eventName":"update-not-available","message":"No updates available."}
[19-03-04 04:30:36.517] (Info) ab.childProcessCommunication.shell.cliStdout - Using NativeScript CLI located in C:\Users\tukan\AppData\Roaming\npm\node_modules\nativescript

[19-03-04 04:30:37.138] (Info) ab.analytics.ui.setVersion - {"version":"1.16.1-v.2019.2.27.1"}
[19-03-04 04:30:37.142] (Info) ab.buildDeploy.ui.pendingRequests - No value provided
[19-03-04 04:30:37.207] (Info) ab.vueService.ui.routeChanged - {"path":"/recent-apps","query":{"back":false}}
[19-03-04 04:30:37.330] (Info) ab.buildDeploy.shell.isLiveSyncInProgress - No value provided
[19-03-04 04:30:37.332] (Info) ab.connectedDevices.ui.devicesListChanged - {}
[19-03-04 04:30:37.775] (Info) ab.childProcessCommunication.shell.cliStdout - Searching for devices...

[19-03-04 04:30:38.516] (Info) ab.childProcessCommunication.shell.cliStdout - iTunes is not installed. Install it on your system and run this command again.

[19-03-04 04:30:38.569] (Info) ab.cliExtensions.shell.extensionLoaded - {"extensionName":"nativescript-cloud","extensionVersion":"1.17.1"}
[19-03-04 04:30:38.574] (Info) ab.cliExtensions.shell.extensionLoaded - {"extensionName":"nativescript-starter-kits","extensionVersion":"0.3.5"}
[19-03-04 04:30:38.578] (Info) ab.cliExtensions.shell.extensionsLoaded - [{"extensionName":"nativescript-cloud","extensionVersion":"1.17.1"},{"extensionName":"nativescript-starter-kits","extensionVersion":"0.3.5"}]
[19-03-04 04:30:40.882] (Info) ab.connectedDevices.shell.deviceFound - {"identifier":"fddc42fd","displayName":"OnePlus6T","model":"ONEPLUS A6013","version":"9","vendor":"OnePlus","platform":"Android","status":"Connected","errorHelp":null,"isTablet":false,"type":"Device"}
[19-03-04 04:30:40.887] (Info) ab.connectedDevices.ui.devicesListChanged - {"0":{"debuggableAppsList":[],"deviceType":"Phone","displayName":"OnePlus6T","errorHelp":null,"identifier":"fddc42fd","isDebugEnabled":false,"isDebugStarted":false,"isEmulator":false,"isLiveSyncStarted":false,"isPreviewDevice":false,"isTablet":false,"logData":[],"model":"ONEPLUS A6013","platform":"Android","selected":true,"status":"Connected","type":"Device","unauthorized":false,"vendor":"Oneplus","version":"9"}}
[19-03-04 04:30:40.889] (Info) ab.connectedDevices.ui.devicesListChanged - {"0":{"debuggableAppsList":[],"deviceType":"Phone","displayName":"OnePlus6T","errorHelp":null,"identifier":"fddc42fd","isDebugEnabled":false,"isDebugStarted":false,"isEmulator":false,"isLiveSyncStarted":false,"isPreviewDevice":false,"isTablet":false,"logData":[],"model":"ONEPLUS A6013","platform":"Android","selected":true,"status":"Connected","type":"Device","unauthorized":false,"vendor":"Oneplus","version":"9"}}
[19-03-04 04:30:40.891] (Info) ab.connectedDevices.ui.deviceSelected - {"debuggableAppsList":[],"deviceType":"Phone","displayName":"OnePlus6T","errorHelp":null,"identifier":"fddc42fd","isDebugEnabled":false,"isDebugStarted":false,"isEmulator":false,"isLiveSyncStarted":false,"isPreviewDevice":false,"isTablet":false,"logData":[],"model":"ONEPLUS A6013","platform":"Android","selected":true,"status":"Connected","type":"Device","unauthorized":false,"vendor":"Oneplus","version":"9"}
[19-03-04 04:30:41.365] (Info) ab.emulatorImages.shell.emulatorImageFound - {"identifier":null,"imageIdentifier":"Android_Accelerated_x86_Oreo","displayName":"Android_Accelerated_x86_Oreo","version":"8.1.0","vendor":"Avd","status":"Not running","errorHelp":null,"isTablet":false,"type":"Emulator","platform":"Android"}
[19-03-04 04:30:41.370] (Info) ab.cliExtensions.shell.tnsInitialize - {}
[19-03-04 04:30:41.624] (Info) ab.preview.shell.playgroundAppQrCode - {"android":{"originalUrl":"https://play.google.com/store/apps/details?id=org.nativescript.play","shortenUrl":"https://play.nativescript.org/s/0gvux3t","imageData":"data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22155%22%20height%3D%22155%22%20viewBox%3D%220%200%2031%2031%22%3E%3Cpath%20d%3D%22M1%201h7v7h-7zM10%201h6v1h-5v1h-1zM17%201h5v1h-2v1h-1v-1h-1v2h1v1h-1v1h-1v-1h-1v-3h1zM23%201h7v7h-7zM2%202v5h5v-5zM24%202v5h5v-5zM3%203h3v3h-3zM9%203h1v1h1v-1h1v2h-1v2h-1v2h-1zM13%203h1v1h1v1h-1v1h-1v1h-1v-2h1zM20%203h1v1h-1zM25%203h3v3h-3zM21%204h1v4h-1v-2h-1v-1h1zM15%205h1v1h-1zM14%206h1v1h-1zM16%206h1v1h-1zM19%206h1v2h1v1h-2zM11%207h1v1h-1zM13%207h1v2h-2v-1h1zM15%207h1v2h1v-2h1v2h1v1h-1v3h-1v-1h-2v-2h-1v-1h1zM1%209h1v1h1v1h-2zM3%209h5v1h-1v1h1v-1h1v2h-3v-2h-3zM23%209h5v1h-2v2h-2v1h-2v-1h1v-1h-1v1h-1v-1h-1v-1h3zM12%2010h2v1h-1v1h-1v2h3v1h2v2h2v1h7v2h-1v-1h-2v1h-1v-1h-3v1h-1v1h-1v-1h-1v-1h2v-1h-3v-1h1v-1h-1v1h-1v1h-1v1h-1v1h-2v-1h1v-1h1v-1h1v-1h1v-1h-3v-2h-1v-1h1v-1h1zM16%2010v1h1v-1zM24%2010v1h1v-1zM29%2010h1v1h-1zM4%2011h1v2h-1v1h-1v1h-1v-1h-1v-2h3zM19%2012h2v1h-1v1h1v-1h1v1h2v-1h1v1h1v1h2v1h-2v1h-1v-1h-1v1h-3v-2h-2v1h-1v-1h-1v-1h1v-1h1zM26%2012h1v1h1v1h-2zM28%2012h1v1h-1zM7%2013h2v1h-2zM16%2013h1v1h-1zM6%2014h1v1h1v1h-5v-1h3zM29%2014h1v1h-1zM10%2015h1v1h-1zM22%2015v1h1v-1zM19%2016h1v1h-1zM28%2016h1v1h-1zM1%2017h1v1h1v1h-1v3h-1zM7%2017h4v1h-1v1h-1v1h-2v1h1v1h-2v-3h2v-1h-1zM26%2017h2v3h-1v-2h-1zM4%2018h2v1h-1v1h-1v1h-1v-2h1zM29%2018h1v1h-1zM13%2019h1v2h-1zM9%2020h1v1h-1zM15%2020h1v1h-1zM20%2020h2v1h2v-1h1v1h1v1h1v-1h1v-1h1v1h1v2h-2v1h-2v2h-5v-1h-2v-1h-4v1h-2v-1h1v-2h2v1h4v-1h1v-1h-1zM10%2021h3v2h-2v-1h-1zM18%2021h1v1h-1zM9%2022h1v1h-1zM22%2022v3h3v-3zM1%2023h7v7h-7zM23%2023h1v1h-1zM2%2024v5h5v-5zM9%2024h3v1h-1v1h-1v2h-1zM29%2024h1v1h-1zM3%2025h3v3h-3zM15%2025h4v1h-1v1h1v1h-1v1h-1v-1h-2v2h-2v-1h1v-1h-1v-1h-1v1h1v1h-2v1h-2v-1h1v-1h1v-2h4v1h2v-1h-2zM27%2025h1v1h2v1h-1v2h-1v-1h-1v1h1v1h-3v-2h-2v-1h3v-1h1zM19%2026h2v1h-2zM21%2027h1v2h-1zM18%2029h3v1h-3zM22%2029h1v1h-1z%22%2F%3E%3C%2Fsvg%3E"},"ios":{"originalUrl":"https://itunes.apple.com/us/app/nativescript-playground/id1263543946?mt=8&ls=1","shortenUrl":"https://play.nativescript.org/s/pbfdchp","imageData":"data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22155%22%20height%3D%22155%22%20viewBox%3D%220%200%2031%2031%22%3E%3Cpath%20d%3D%22M1%201h7v7h-7zM10%201h2v1h-1v1h-1zM17%201h5v1h-2v1h-1v-1h-2zM23%201h7v7h-7zM2%202v5h5v-5zM12%202h1v1h-1zM14%202h1v1h-1zM16%202h1v1h1v1h-1v1h-2v1h-1v-2h1v-1h1zM24%202v5h5v-5zM3%203h3v3h-3zM9%203h1v2h1v1h-1v2h1v1h-2zM20%203h1v1h-1zM25%203h3v3h-3zM11%204h1v1h-1zM18%204h1v1h-1zM21%204h1v4h-1v-2h-1v-1h1zM17%205h1v1h-1zM11%206h3v2h-1v-1h-1v1h-1zM16%206h1v1h-1zM19%206h1v2h1v1h-2zM15%207h1v1h-1zM17%207h1v2h-1zM1%209h1v1h-1zM3%209h5v1h-5zM12%209h5v1h-1v1h-1v-1h-1v3h-1v1h-1v-1h-1v-2h1v1h1v-1h-1zM18%209h1v1h-1zM23%209h5v1h-2v2h-2v1h-2v-1h1v-1h-1v1h-1v-1h-1v-1h3zM17%2010h1v1h-1zM24%2010v1h1v-1zM29%2010h1v1h-1zM1%2011h3v1h-2v1h-1zM7%2011h3v1h-1v1h-1v-1h-1zM16%2011h1v1h-1zM4%2012h1v1h-1zM6%2012h1v1h-1zM19%2012h2v1h-1v1h1v-1h1v1h2v-1h1v1h1v1h2v1h-2v1h-1v-1h-1v1h-3v-2h-2v1h-1v-1h-1v-1h1v-1h1zM26%2012h1v1h1v1h-2zM28%2012h1v1h-1zM2%2013h1v1h1v1h-1v2h-2v-3h1zM5%2013h1v1h-1zM7%2013h1v1h-1zM16%2013h1v1h-1zM6%2014h1v1h-1zM9%2014h1v2h-1zM14%2014h1v1h2v2h2v1h7v2h-1v-1h-2v1h-1v-1h-3v1h-1v1h-1v-1h-1v-1h1v-1h-2v-1h1v-1h-1v1h-1v4h-1v-2h-1v-1h-1v4h1v1h-3v-1h1v-3h-2v-1h-2v-2h1v1h2v1h1v-2h1v1h1v-1h1v-1h1zM29%2014h1v1h-1zM7%2015h1v1h-1zM22%2015v1h1v-1zM4%2016h1v1h-1zM19%2016h1v1h-1zM28%2016h1v1h-1zM26%2017h2v3h-1v-2h-1zM1%2018h2v1h-1v3h-1zM5%2018h1v1h-1zM29%2018h1v1h-1zM4%2019h1v2h-1zM7%2019h1v1h-1zM6%2020h1v1h2v1h-3zM15%2020h1v1h-1zM20%2020h2v1h2v-1h1v1h1v1h1v-1h1v-1h1v1h1v2h-2v1h-2v2h-5v-1h-2v-1h-4v1h-1v-1h-1v-2h3v1h4v-1h1v-1h-1zM12%2021h1v1h-1zM18%2021h1v1h-1zM22%2022v3h3v-3zM1%2023h7v7h-7zM23%2023h1v1h-1zM2%2024v5h5v-5zM9%2024h4v1h-1v1h-2v1h1v1h1v1h-1v1h-2v-1h1v-1h-1zM29%2024h1v1h-1zM3%2025h3v3h-3zM15%2025h4v1h-1v1h1v1h-1v1h-1v-1h-1v-1h1v-1h-2zM27%2025h1v1h2v1h-1v2h-1v-1h-1v1h1v1h-3v-2h-2v-1h3v-1h1zM13%2026h1v1h-1zM19%2026h2v1h-2zM14%2027h1v1h-1zM21%2027h1v2h-1zM13%2029h1v1h-1zM18%2029h3v1h-3zM22%2029h1v1h-1z%22%2F%3E%3C%2Fsvg%3E"}}
[19-03-04 04:30:41.759] (Info) ab.analyticsProvider.shell.enableTracking - No value provided
[19-03-04 04:30:41.784] (Info) ab.analytics.shell.analyticsEnabled - true
[19-03-04 04:30:41.786] (Info) ab.eula.shell.eulaData - {"url":"https://www.nativescript.org/nativescript-sidekick/eula","shouldAcceptEula":false}
[19-03-04 04:30:41.913] (Info) ab.tnsDoctor.shell.checkLocalBuild - {"iOS":{"canExecuteLocalBuild":false,"warnings":[]},"Android":{"canExecuteLocalBuild":false,"warnings":[{"warning":"WARNING: adb from the Android SDK is not installed or is not configured properly. ","additionalInformation":"For Android-related operations, the NativeScript CLI will use a built-in version of adb.\r\nTo avoid possible issues with the native Android emulator, Genymotion or connected\r\nAndroid devices, verify that you have installed the latest Android SDK and\r\nits dependencies as described in http://developer.android.com/sdk/index.html#Requirements","platforms":["Android"]},{"warning":"Cannot find a compatible Android SDK for compilation. To be able to build for Android, install Android SDK 28 or later.","additionalInformation":"Run `$ sdkmanager` to manage your Android SDK versions.","platforms":["Android"]},{"warning":"You need to have the Android SDK Build-tools installed on your system. You can install any version in the following range: '>=23 <=28'.","additionalInformation":"Run `$ sdkmanager` from your command-line to install required `Android Build Tools`. In case you already have them installed, make sure `ANDROID_HOME` environment variable is set correctly.","platforms":["Android"]},{"warning":"Error executing command 'javac'. Make sure you have installed The Java Development Kit (JDK) and set JAVA_HOME environment variable.","additionalInformation":"You will not be able to build your projects for Android.\r\nTo be able to build for Android, verify that you have installed The Java Development Kit (JDK) and configured it according to system requirements as\r\n described in http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-win.html#system-requirements","platforms":["Android"]},{"warning":"WARNING: The Java Development Kit (JDK) is not installed or is not configured properly.","additionalInformation":"You will not be able to work with the Android SDK and you might not be able\r\nto perform some Android-related operations. To ensure that you can develop and\r\ntest your apps for Android, verify that you have installed the JDK as\r\ndescribed in http://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html (for JDK 8).","platforms":["Android"]}]}}
[19-03-04 04:30:42.974] (Info) ab.kinveyAuth.shell.configData - {"shouldConfigure":false}
[19-03-04 04:30:43.003] (Info) ab.dependenciesLoader.shell.dependenciesReady - {"installedExtensionsCount":0}
[19-03-04 04:30:43.007] (Info) ab.authentication.shell.userInfo - {"email":"tukanoid@outlook.com","firstName":"Vitalii Lukyanov","lastName":""}
[19-03-04 04:30:45.374] (Info) ab.authentication.shell.userAvatar - No value provided
[19-03-04 04:30:45.408] (Info) ab.userAccounts.shell.activeUserAccount - {"id":"52689186-ddd2-4e4e-a361-e08c5a4b0b33","name":"Vitalii Lukyanov ","type":"personal"}
[19-03-04 04:30:45.409] (Info) ab.userAccounts.shell.userAccountList - [{"id":"52689186-ddd2-4e4e-a361-e08c5a4b0b33","name":"Vitalii Lukyanov ","type":"personal"}]
[19-03-04 04:30:49.147] (Info) ab.subscriptions.shell.accountFeatures - {"CloudBuilds":{"feature":"Cloud Builds","enabled":true,"type":"CloudBuilds"},"PrivateCloud":{"feature":"Private Cloud","enabled":false,"type":"PrivateCloud"}}
[19-03-04 04:30:49.301] (Info) ab.subscriptions.shell.usageInfo - {"accountId":"52689186-ddd2-4e4e-a361-e08c5a4b0b33","cloudBuildUsage":{"feature":"Cloud Builds","description":"Builds executed in the cloud.","usage":0,"softUsageLimit":80,"allowedUsage":100,"licenseExpiration":"2019-04-04T01:47:46.483Z","licenseExpirationDate":"2119-03-04T01:47:46.483Z","resetDate":"2019-04-04T01:47:46.483Z","licenseType":"Free","editionType":"NativeScript Sidekick Free","unlimited":false}}
[19-03-04 04:33:16.487] (Info) ab.vueService.ui.routeChanged - {"path":"/create-app","query":{}}
[19-03-04 04:33:16.497] (Info) ab.startScreen.ui.createApp - No value provided
[19-03-04 04:33:30.357] (Info) ab.analyticsProvider.shell.trackIntercomEvent - {"eventCategory":"createApp","eventAction":"","eventLabel":"tns-template-blank-vue"}
[19-03-04 04:33:30.363] (Info) ab.createApp.shell.lastUsedAppDirectory - {"appDirectory":"E:\\vitalik27062001@gmail.com\\University\\Classes\\Year 1\\Block 3\\Project Block 3"}
[19-03-04 04:33:30.366] (Info) ab.createApp.ui.create - {"appDirectory":"E:\\vitalik27062001@gmail.com\\University\\Classes\\Year 1\\Block 3\\Project Block 3","appIdentifier":"org.nativescript.ProjectApp","appName":"ProjectApp","template":"tns-template-blank-vue"}
[19-03-04 04:33:30.401] (Info) ab.analyticsProvider.ui.trackIntercomEvent - {"eventAction":"","eventCategory":"createApp","eventLabel":"tns-template-blank-vue"}
[19-03-04 04:33:46.281] (Info) ab.subscriptions.ui.requestUsageInfo - No value provided
[19-03-04 04:33:47.995] (Info) ab.subscriptions.ui.requestUsageInfo - No value provided
[19-03-04 04:33:50.351] (Info) ab.menu.shell.about - {"isAlreadyTracked":false}
[19-03-04 04:35:16.145] (Error) ab.childProcessCommunication.shell.cliStderr - rm: could not remove directory (code EBUSY): E:/vitalik27062001@gmail.com/University/Classes/Year 1/Block 3/Project Block 3/ProjectApp

[19-03-04 04:35:16.150] (Error) ab.createApp.shell.create - rm: could not remove directory (code EBUSY): E:/vitalik27062001@gmail.com/University/Classes/Year 1/Block 3/Project Block 3/ProjectApp, Error: rm: could not remove directory (code EBUSY): E:/vitalik27062001@gmail.com/University/Classes/Year 1/Block 3/Project Block 3/ProjectApp
    at FileSystem.deleteDirectory (C:\Users\tukan\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:122:19)
    at ProjectService.<anonymous> (C:\Users\tukan\AppData\Roaming\npm\node_modules\nativescript\lib\services\project-service.js:111:26)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\tukan\AppData\Roaming\npm\node_modules\nativescript\lib\services\project-service.js:11:65)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
[19-03-04 04:35:24.858] (Info) ab.menu.shell.showLogs - {"isAlreadyTracked":false}

**Comment by tsvetie** [comment]
Hey @tukanoidd,

Sorry to keep you waiting like this. The error that you got during create was "could not remove directory (code EBUSY)". I'm guessing the folder that you were trying to create an app in was either not empty, or it was locked by another process. Do you still get the error?

**Comment by NickIliev** [comment]
Closing due to inactivity
