### ISSUE TITLE
Couldn't enable debugging on Android

### ISSUE THREAD

**Issue by kenchan98** [NativeScript/sidekick-feedback#375]
Hi there,

I tried testing the default sample angular app on my Xiaomi Pocco phone and got this error of 'couldnt enable debugging for (my device identifier)

I have already enabled USB debugging as well as installation via USB on the device. 

Thanks in advance

the error log as follows
-------------------
```
[19-05-01 16:24:57.334] Error detected during LiveSync on 2e5186af for /Users/kenchan/Documents/_projects/nativescript/angularApp. Error: spawn ./gradlew ENOENT
[19-05-01 16:24:57.341] Couldn't enable debugging for 2e5186af, Error: Couldn't enable debugging for 2e5186af
at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:253:30)
at Generator.next (<anonymous>)
at /usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:9:12)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:250:16)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/common/decorators.js:67:47)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:290:25)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:10:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
[19-05-01 16:34:35.816] Error detected during LiveSync on 2e5186af for /Users/kenchan/Documents/_projects/nativescript/angularApp. Error: spawn ./gradlew ENOENT
[19-05-01 16:34:35.823] Couldn't enable debugging for 2e5186af, Error: Couldn't enable debugging for 2e5186af
at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:253:30)
at Generator.next (<anonymous>)
at /usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:9:12)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:250:16)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/common/decorators.js:67:47)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:290:25)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:10:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
[19-05-01 16:44:18.401] Error detected during LiveSync on 2e5186af for /Users/kenchan/Documents/_projects/nativescript/angularApp. Error: spawn ./gradlew ENOENT
[19-05-01 16:44:18.406] Couldn't enable debugging for 2e5186af, Error: Couldn't enable debugging for 2e5186af
at Errors.fail (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:126:28)
at Errors.failWithoutHelp (/usr/local/lib/node_modules/nativescript/lib/common/errors.js:136:21)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:253:30)
at Generator.next (<anonymous>)
at /usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:9:12)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:250:16)
at LiveSyncService.enableDebuggingCoreWithoutWaitingCurrentAction (/usr/local/lib/node_modules/nativescript/lib/common/decorators.js:67:47)
at LiveSyncService.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:290:25)
at Generator.next (<anonymous>)
at fulfilled (/usr/local/lib/node_modules/nativescript/lib/services/livesync/livesync-service.js:10:58)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by NickIliev** [comment]
@kenchan98 what option are you using to debug (the default ChromeDev Tools via the CLI or the VSCode debug) - in both cases, I think the issue is related to the CLI (or the VSCode extension) - please post the issue with all the required information in[ the nativescript-cli issues](https://github.com/NativeScript/nativescript-cli/issues).
