### ISSUE TITLE
Nativescript sidekick error : EISDIR: illegal operation... 

### ISSUE THREAD

**Issue by Nahiduzzaman** [NativeScript/sidekick-feedback#403]
I am getting following error when publisihing my app for ios:

19-07-25 16:53:45.508] (CLI) Starting Cloud publish iOS. Cloud operation id: d09d0b38-6964-4914-bc3c-dc70136ce529
[19-07-25 16:53:46.562] EISDIR: illegal operation on a directory, read, Error: EISDIR: illegal operation on a directory, read
   at Object.readSync (fs.js:498:3)
   at tryReadSync (fs.js:332:20)
   at Object.readFileSync (fs.js:369:19)
   at FileSystem.readFile (/usr/local/lib/node_modules/nativescript/lib/common/file-system.js:171:19)
   at UploadService.<anonymous> (/Users/test/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/upload-service.js:34:45)
   at Generator.next (<anonymous>)
   at fulfilled (/Users/test/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/upload-service.js:4:58)
   at process._tickCallback (internal/process/next_tick.js:68:7)

Can anyone help me.

**Comment by NickIliev** [comment]
@Nahiduzzaman the issue seems related to a local read operation issue - can you please send us the full log generated from SIdekick?

In order to fully investigate please provide as much information as possible from the start a "New issue" template

```
## Please, provide the details below:

### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._

```
