### ISSUE TITLE
Cloud build fails with error code 2 / ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by overwise** [NativeScript/sidekick-feedback#407]
The build that worked before, now stopped working. The change that happened was:
1. I updated Sidekick. It asked to update nativescript to 6.0.0. I accepted.
2. I'm using schematics which still doesn't support 6.0.0. I downgraded nativescript to 5.4.2. I don't remember what was the latest NS version that worked for with my code, so it might be that it was 5.4.1 or less.
3. I try to build it on my iOS device with following settings:
  - Certificate and provision are set and correct
  - Build type: cloud
  - Clean build
  - Build configuration: debug
  - Webpack enabled
  - Start debugger enabled

It fails with following output:

```
[19-07-25 13:16:14.771] (CLI) NativeScript CLI version 4.2.4
[19-07-25 13:16:14.771] (CLI) Add platform ios with runtime version 4.2.0
[19-07-25 13:16:16.423] (CLI) ReferenceError: internalBinding is not defined
[19-07-25 13:16:16.423] (CLI)     at internal/util/inspect.js:31:15
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
[19-07-25 13:16:16.423] (CLI)     at util.js:25:21
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
[19-07-25 13:16:16.423] (CLI)     at fs.js:42:21
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at Object.req [as require] (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:54:10)
[19-07-25 13:16:16.423] (CLI)     at Object.<anonymous> (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
[19-07-25 13:16:16.423] (CLI) ReferenceError: internalBinding is not defined
[19-07-25 13:16:16.423] (CLI)     at internal/util/inspect.js:31:15
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
[19-07-25 13:16:16.423] (CLI)     at util.js:25:21
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
[19-07-25 13:16:16.423] (CLI)     at fs.js:42:21
[19-07-25 13:16:16.423] (CLI)     at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
[19-07-25 13:16:16.423] (CLI)     at Object.req [as require] (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:54:10)
[19-07-25 13:16:16.423] (CLI)     at Object.<anonymous> (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
[19-07-25 13:16:19.400] Build step completed.
[19-07-25 13:16:19.411] Error detected during LiveSync on 49bea0639c6f8d762fff97f629856220d625ef58 for /Users/vladimir/Projects/westcomiljo/westcomiljoapp. Error: Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:03.060] [WARN]  ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
[00:00:03.285] [ERROR] ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at require (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:110:12)
    at fs.js:42:21
at req_ (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/builder/nativescript-cli/4.2.4/node_modules/nativescript/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
'Build failed with error code 2'.
```

I have tried deleting /platforms/ios, cleaning workspace, and restarting Sidekick. This error stays.

Any ideas?

**Comment by overwise** [comment]
Very similar error for Android too:  'Build failed with error code 2' and "ReferenceError: internalBinding is not defined".

**Comment by overwise** [comment]
Maybe useful bit of info:
In the console, a little bit before the error is thrown, there are these lines:
```
[19-07-25 14:00:23.247] (CLI) NativeScript CLI version 4.2.4
[19-07-25 14:00:23.247] (CLI) Add platform android with runtime version 4.2.0
[19-07-25 14:00:23.247] (CLI) ReferenceError: internalBinding is not defined
```
NativeScript CLI version 4.2.4? Where is this coming from?

**Comment by overwise** [comment]
Look at me, asking and resolving this issue myself... Feeling both smart and stupid same time...

Here's what made Sidekick use very old Nativescript CLI. In my package.js tns-android and tns.ios were 4.2.0. When I changed that to 5.4.0, it all clicked back in place. 
```
"nativescript": {
    "tns-android": {
      "version": "5.4.0"
    },
    "tns-ios": {
      "version": "5.4.0"
    }
  }
```
