### ISSUE TITLE
[ERROR] Executing webpack failed with exit code 2

### ISSUE THREAD

**Issue by Izrab** [NativeScript/sidekick-feedback#419]
### Did you verify whether this issue has already been reported here?
No_

### Tell us about the problem
I'm trying to build my app in cloud for my Android device using NativeScript Sidekick, I also tried removing `platforms`, `.cloud`, and `node_modules` folders, but no avail.
**I get the following error message**

> [19-08-31 16:37:00.069] Error detected during LiveSync on 192.168.100.215:5555 for C:\Users\Bridge\Desktop\Vessel\souq366. Error: Build failed. Reason is: 'Build failed with error code 2'. Additional information: [00:00:21.931] [WARN]  Executing webpack failed with exit code 2.
> [00:00:22.103] [ERROR] Executing webpack failed with exit code 2.
> 'Build failed with error code 2'.
> [19-08-31 16:37:00.077] Couldn't enable debugging for 192.168.100.215:5555, Error: Couldn't enable debugging for 192.168.100.215:5555
>     at Errors.fail (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:126:28)
>     at Errors.failWithoutHelp (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\errors.js:136:21)
>     at DebugController.<anonymous> (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:116:30)
>     at Generator.next (<anonymous>)
>     at C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:13:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:9:12)
>     at DebugController.enableDebuggingCoreWithoutWaitingCurrentAction (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:113:16)
>     at DebugController.enableDebuggingCoreWithoutWaitingCurrentAction (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\common\decorators.js:67:47)
>     at DebugController.<anonymous> (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:209:25)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\Bridge\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\debug-controller.js:10:58)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> 

here is my package.json file for information about the plugins I use
```
{
  "nativescript": {
    "id": "com.souq366.buyerapp",
    "tns-android": {
      "version": "6.0.2"
    },
    "tns-ios": {
      "version": "6.0.2"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "apollo-client": "2.6.4",
    "nativescript-apple-sign-in": "1.0.0",
    "nativescript-bottom-navigation": "2.0.3",
    "nativescript-carousel": "6.1.0",
    "nativescript-cognito": "1.1.3-alpha",
    "nativescript-geolocation": "5.1.0",
    "nativescript-inappbrowser": "2.0.0",
    "nativescript-lottie": "4.0.0",
    "nativescript-permissions": "1.3.7",
    "nativescript-picker": "2.1.2",
    "nativescript-plugin-firebase": "9.1.1",
    "nativescript-theme-core": "2.0.8",
    "nativescript-ui-autocomplete": "5.1.0",
    "nativescript-ui-dataform": "5.0.0",
    "nativescript-ui-listview": "7.0.4",
    "nativescript-ui-sidedrawer": "7.0.0",
    "tns-core-modules": "6.0.7"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "1.1.1",
    "typescript": "3.6.2"
  },
  "gitHead": "42f2a6a9c94eaf9c68d2a41e0daaa1a2544bc28f",
  "readme": "NativeScript Application"
}
```
### Which platform(s) does the issue occur on?
_Android 9
_Windows 10_

### Provide the following version numbers that the issue occurs with:
![image](https://user-images.githubusercontent.com/22328131/64064076-2365c480-cbb2-11e9-8980-5821cc0ed8c1.png)

### Does this issue happen every time?
_Yes

### Send the client logs

[main_19-08-31_15-56-08.121.log](https://github.com/NativeScript/sidekick-feedback/files/3562453/main_19-08-31_15-56-08.121.log)
[console_19-08-31_15-56-05.354.log](https://github.com/NativeScript/sidekick-feedback/files/3562454/console_19-08-31_15-56-05.354.log)

**Comment by tsonevn** [comment]
Hi @Izrab,
Can you try to clear up again the project by deleting `platforms`, `.cloud`, `node_modules` as well as `hooks`, `package-lock.json` and `webpack.config.js`? Then try to rebuild the project and check if the issue will be still reproducible.
