### ISSUE TITLE
Exception when using with Node LTS (12.13.0)

### ISSUE THREAD

**Issue by dmytro-gokun** [NativeScript/sidekick-feedback#434]
[19-11-09 21:08:20.868] NativeScript Sidekick version: 1.19.1-v.2019.8.1.2
[19-11-09 21:08:20.929] Checking for updates...
[19-11-09 21:08:21.659] Dependencies versions: NodeJS: 12.13.0, npm: 6.13.0, NativeScript CLI: 6.2.0.
[19-11-09 21:08:21.975] No updates available.
[19-11-09 21:08:22.624] (CLI) Using NativeScript CLI located in C:\Users\Dmytro\AppData\Roaming\npm\node_modules\nativescript
[19-11-09 21:08:25.238] (CLI) Searching for devices...
[19-11-09 21:08:25.290] Loaded CLI extension nativescript-cloud, version 1.19.2.
[19-11-09 21:08:25.292] Loaded CLI extension nativescript-starter-kits, version 0.3.5.
[19-11-09 21:08:25.542] (CLI) (node:9760) UnhandledPromiseRejectionWarning: ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at emitUnhandledRejectionWarning (internal/process/promises.js:141:15)
    at processPromiseRejections (internal/process/promises.js:203:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
[19-11-09 21:08:25.545] (CLI) (node:9760) ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\Dmytro\AppData\Roaming\.nativescript-cli\extensions\node_modules\graceful-fs\graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
(node:9760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:153:11)
    at processPromiseRejections (internal/process/promises.js:205:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
[19-11-09 21:08:27.617] The user Dmytro Gokun logged in.
[19-11-09 21:08:33.661] Devices service initialized.
[19-11-09 21:08:36.308] Checking for updates...
[19-11-09 21:08:36.925] No updates available.

**Comment by atchaiecommerce** [comment]
one solution is to downgrade nodejs to v10

**Comment by Akimotorakiyu** [comment]
can't install whit node 12.13.0

**Comment by rosen-vladimirov** [comment]
Hey everyone,
This issue is resolved in the latest version of nativescript-cloud - 1.19.3. Just restart your NativeScript Sidekick and it will take care to update the nativescript-cloud extension.
In case you have any troubles, feel free to reopen the issue or log a new one following the template.
