### ISSUE TITLE
Sidekick Auto Generate for provision and certificate failed.

### ISSUE THREAD

**Issue by pollyolly** [NativeScript/sidekick-feedback#435]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
After I tried to use auto generate for the ISO provisioning and certificate this error comes out.

**Auto Generation Failed**
_An error has occured while generating the certificate and mobile provision. Reason: expecting an array or an iterable object but got [object Null]._ 

### Which platform(s) does the issue occur on?
iOS 13x MacBook Pro

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the sidekick
2. In the connected devises.
3. Click the gear icon and use auto generate of provision and certificate.
4. Provide iOS free apple account.
5. Error comes out.

### Does this issue happen every time?
Yes

### Send the client logs

[19-11-11 13:48:52.545] (CLI) Starting Cloud code sign. Cloud operation id: 48a0ea04-c5fe-4fbf-9b15-166b6010dd48
[19-11-11 13:48:52.545] (CLI) Starting generation of iOS certificate and provision files.
[19-11-11 13:49:00.441] An error has occured while generating the certificate and mobile provision. Reason: expecting an array or an iterable object but got [object Null]., Error: Codesign failed. Reason is: expecting an array or an iterable object but got [object Null].
    at CloudCodesignService.<anonymous> (/Users/UPDILC/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:75:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/UPDILC/.local/share/.nativescript-cli/extensions/node_modules/nativescript-cloud/lib/services/cloud-codesign-service.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by pollyolly** [comment]
Same error even I already created a new project using sidekick.
Please help.

**Comment by rosen-vladimirov** [comment]
Hey everyone, 
Thank you for reporting this issue. We've reproduced it and we've investigated the case - the problem is caused by change in Apple's API for the Free Developer program. We'll need some time to investigate it further and see how to resolve this issue.
Please, excuse us for the caused inconvenience.

**Comment by edmundpf** [comment]
> Hey everyone,
> Thank you for reporting this issue. We've reproduced it and we've investigated the case - the problem is caused by change in Apple's API for the Free Developer program. We'll need some time to investigate it further and see how to resolve this issue.
> Please, excuse us for the caused inconvenience.

Hi, thanks for looking into this. Any updates?

**Comment by Nickmanbear** [comment]
Haha. I got excited when it said there was an update. But then it was just a better looking error message.😅
I take this won't be an easy fix and might take a little while?

**Comment by edmundpf** [comment]
Any updates on this? Looks like windows users just can't do cloud builds without this functionality, currently stuck on deployment of an app since I can't test for iOS

**Comment by robomaniac** [comment]
Is there a workaround for this until the bug is fix? Do I open a MAC and generate the certificate and provision that I then copy to my PC?

**Comment by gzimgashi** [comment]
Any Update?

**Comment by poldixd** [comment]
Maybe it's because 2FA?

**Comment by mayerlench** [comment]
Hey, is there any workaround for this?
With our this it doesnt seem possible to work off a windows machine with a free apple account

**Comment by hasanbildirici** [comment]
Is there any progress with this issue yet?

**Comment by vick16ach** [comment]
Still Sidekick showing this error today. Is there any update on this issue.

**Comment by mayerlench** [comment]
> Still Sidekick showing this error today. Is there any update on this issue.

No, right now the only way to develop for IOS on a windows machine is to use cloud builds with a payed developer license. I spun up a MacOS virtual machine on my windows machine and i am able to develop using the free IOS developer account

**Comment by vick16ach** [comment]
> > Still Sidekick showing this error today. Is there any update on this issue.
> 
> No, right now the only way to develop for IOS on a windows machine is to use cloud builds with a payed developer license. I spun up a MacOS virtual machine on my windows machine and i am able to develop using the free IOS developer account
Hey mayerlench, Can you post the exact steps to achieve what you did. So, that it will be very help full which might reduce the burden of researching. Currently i started exploring aws virtual machine to build ios app. but I didn't achieved it yet and wasting time in lot of researching.

**Comment by pollyolly** [comment]
> > Still Sidekick showing this error today. Is there any update on this issue.
> 
> No, right now the only way to develop for IOS on a windows machine is to use cloud builds with a payed developer license. I spun up a MacOS virtual machine on my windows machine and i am able to develop using the free IOS developer account

What MACOS for VM you use? can you share it?

**Comment by mayerlench** [comment]
In order to use the free apple developer license you need to be on MacOS. You can achieve this by using an apple computer or running MacOS virtually on a windows machine. 

I dont recommend to do this if you arent familiar with virtual machines. Heres a link https://bit.ly/31ezWpX

Once you are running MacOS you will need to install all the nativescript dependencies and download Xcode to provision the free developer certificate for you app

**Comment by CameronRiou** [comment]
Hi @rosen-vladimirov have you got any update on this issue?

**Comment by mcasto** [comment]
@mayerlench, I'm running on a Mac and I have this issue too, so I'm not sure setting up a Mac VM will resolve it.

**Comment by mayerlench** [comment]
> @mayerlench, I'm running on a Mac and I have this issue too, so I'm not sure setting up a Mac VM will resolve it.

Have you generated the certificate in xcode?

**Comment by mcasto** [comment]
Shouldn't Auto Generate provisioning profile & cert within NativeScript Sidekick do that? Or are you saying I need to do something extra in Xcode?

**Comment by mayerlench** [comment]
> Shouldn't Auto Generate provisioning profile & cert within NativeScript Sidekick do that? Or are you saying I need to do something extra in Xcode?

You need to open the project in xcode and theres a button there to provision the certificate but this must be done through xcode

**Comment by mcasto** [comment]
Interesting. I haven't used NS in ~1.5 years. At that point, I could generate the cert in NS Sidekick & it worked. Apparently, things have changed a little :D

**Comment by mayerlench** [comment]
> Interesting. I haven't used NS in ~1.5 years. At that point, I could generate the cert in NS Sidekick & it worked. Apparently, things have changed a little :D

Yup. The ability to to provision through sidekick has been broken for a while as apples api no longer supports because shame be it on them to make developers lifes a little easier 😅

**Comment by mcasto** [comment]
Right? I love my Mac & iPhone (though, since Jobs's death they seem to have slipped a bit in some areas), but, as a developer ... { groan }

**Comment by nonereally** [comment]
> > Still Sidekick showing this error today. Is there any update on this issue.
> 
> No, right now the only way to develop for IOS on a windows machine is to use cloud builds with a payed developer license. I spun up a MacOS virtual machine on my windows machine and i am able to develop using the free IOS developer account

I did the same.
How to get your ipa loaded to a device for testing?
Thanks!
