### ISSUE TITLE
Create a Guide for Recovery from "Spawn failed. , Error: Spawn failed."

### ISSUE THREAD

**Issue by EdJones** [NativeScript/sidekick-feedback#441]
## Please, provide the details below:
Sidekick publish to Apple often ends with the unhelpfully terse message :
 ```
Spawn failed.
, Error: Spawn failed. 
```

Together we can examine the hidden logs, as well as attempted solutions, and produce a guide that allows developers to check potential causes and attempt potential solutions.
### Did you verify whether this issue has already been reported here?
_Yes/No_
Yes
### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._
Add a guide that allows developers to get past this issue.
### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_
Probably Windows/MacOS/Linux. (I'm on Windows)
### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.19.1-v.2019.8.1.2
- **NativeScript CLI:** 6.2 and earlier
- **CLI extension nativescript-cloud:** 1.19.5
- **CLI extension nativescript-starter-kits:** 0.3.5

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...Click "publish" for a working app.
3. Await build and download processes to complete without error.
4. Await for Sidekick to request Apple developer credentials 
```
Starting Cloud publish iOS. Cloud operation id: d89a9d8e-890d-40e6-94c2-fc995121a63b
[19-11-15 07:47:35.918] (CLI) Starting publishing.
[19-11-15 07:47:42.028] (CLI) Build machine host name: administrators-Mac-18.local
```
5. Upload fails with "Spawn error", e.g.
```
[19-11-15 07:48:31.634] Spawn failed.
, Error: Spawn failed.
    at CloudPublishService.getiOSError (C:\Users\ed_000\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:79:21)
    at CloudPublishService.<anonymous> (C:\Users\ed_000\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:96:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ed_000\AppData\Roaming\.nativescript-cli\extensions\node_modules\nativescript-cloud\lib\services\cloud-publish-service.js:4:58)
```
### Does this issue happen every time?
_Yes/No_
Varies
### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._
Errors may vary. My latest said 
```
[19-11-15 07:47:48.984] (Info) ab.publish.shell.inputRequested - {"type":"inputRequest","cloudOperationId":"d89a9d8e-890d-40e6-94c2-fc995121a63b","body":{"inputType":"text","inputRequestId":"bdd4134f-7e60-41ee-b8e9-8922a6ecf55a","message":"Please enter the 6 digit code: "}}
[19-11-15 07:48:28.236] (Info) ab.publish.ui.sendCloudMessage - {"requestData":{"body":{"inputRequestId":"bdd4134f-7e60-41ee-b8e9-8922a6ecf55a","inputType":"text","message":"Please enter the 6 digit code: "},"cloudOperationId":"d89a9d8e-890d-40e6-94c2-fc995121a63b","type":"inputRequest"},"response":"224955"}
[19-11-15 07:48:28.576] (Info) ab.publish.shell.sendCloudMessage - No value provided
[19-11-15 07:48:31.634] (Error) ab.publish.shell.publishToItunesConnect - Spawn failed.
, Error: Spawn failed.
```

**Comment by NickIliev** [comment]
@EdJones it seems that you are hitting a bug related to a changed API on iOS (related[ to this comment](https://github.com/NativeScript/sidekick-feedback/issues/435#issuecomment-553250450)).

I will post as soon as we have a stable fix (which will be published in a new version of Sidekick)

**Comment by prabh08** [comment]
@NickIliev I am also getting same issue. Please help asap.

**Comment by EdJones** [comment]
> 
> 
> @EdJones it seems that you are hitting a bug related to a changed API on iOS (related[ to this comment](https://github.com/NativeScript/sidekick-feedback/issues/435#issuecomment-553250450)).
> 
> I will post as soon as we have a stable fix (which will be published in a new version of Sidekick)

@NickIliev, it may be that's my issue this time. But either way, the "Spawn failed" error is cryptic, and more info can sometimes be gleaned from the logs hidden under Sidekick's Help menu. I've seen enough people ask to think a guide would be appreciated.

**Comment by OWOWORLD** [comment]
any fix  for this?

**Comment by asharghi** [comment]
Bump
