### ISSUE TITLE
"Cannot read property 'pid' of undefined"

### ISSUE THREAD

**Issue by EdJones** [NativeScript/sidekick-feedback#461]
### Did you verify whether this issue has already been reported here?
_Yes

### Tell us about the problem
This error arrived when I clicked "stop Livesync".

I'm hoping this error might provide some insight into other issues with 'run on device'. 

### Which platform(s) does the issue occur on?
_iOS<br/>
_Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.19.2-v.2019.11.18.2
- **NativeScript CLI:** 6.3.2
- **CLI extension nativescript-cloud:** 1.19.3
- **CLI extension nativescript-starter-kits:** 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. Run an app on a device.
3. Click "stop Livesync"

### Does this issue happen every time?
Unsure. Stop button is normally disabled. 

### Send the client logs
20-01-20 11:26:25.216] Cannot read property 'pid' of undefined, TypeError: Cannot read property 'pid' of undefined
at WebpackCompilerService.<anonymous> (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:262:73)
at Generator.next (<anonymous>)
at C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:9:12)
at WebpackCompilerService.stopWebpackForPlatform (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:259:16)
at WebpackCompilerService.<anonymous> (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:147:28)
at Generator.next (<anonymous>)
at C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:13:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:9:12)
at WebpackCompilerService.stopWebpackCompiler (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\services\webpack\webpack-compiler-service.js:145:16)
at PrepareController.<anonymous> (C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\prepare-controller.js:64:52)
at Generator.next (<anonymous>)
at C:\Users\ed_000\AppData\Roaming\npm\node_modules\nativescript\lib\controllers\prepare-controller.js:13:71
at new Promise (<anonymous>)

**Comment by aqweeva** [comment]
Any solution for this one yet? I'm have the same issue.
It happened right after renaming my project (which was in many locations) and then running nativescript sidekick to install run the app on my android phone.  Was working fine prior to renaming my project.

**Comment by EdJones** [comment]
For what it's worth, I experienced this while running cloud builds--which are now gone.
