### ISSUE TITLE
Unable to build for android

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/sidekick-feedback#470]
## Please, provide the details below:
Release build fails for Androi. The first error is no such file or directory: C:\Users\...\koy\platforms\android\app\snapshot-build\build\include.gradle

### Did you verify whether this issue has already been reported here?
Yes

### Which platform(s) does the issue occur on?
Android (if applicable, tell us the specific version of the platform)_ <br/>
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.2.2
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the build.

### Does this issue happen every time?
Yes

### Send the client logs
[20-01-30 13:38:52.402] App Settings saved successfully.
[20-01-30 13:40:15.570] Build started.
[20-01-30 13:40:16.201] (CLI) Starting Cloud build. Cloud operation id: 98ab0db0-b984-4b8f-8bf5-81f5d35834af
[20-01-30 13:40:16.201] (CLI) Getting accounts information...
[20-01-30 13:40:16.792] (CLI) Using account 0db2d315-bc7c-48c8-b55b-a0297aae0a41.
[20-01-30 13:40:16.795] (CLI) Cloud build of 'C:\Users\acon\Documents\Visual Studio 2017\Projects\koy', platform: 'Android', configuration: 'Release'.
[20-01-30 13:40:16.799] Prepare step started.
[20-01-30 13:40:16.834] (CLI) Preparing project...
[20-01-30 13:40:19.724] (CLI) Project root: C:\Users\acon\Documents\Visual Studio 2017\Projects\Koy
[20-01-30 13:40:19.725] (CLI) Snapshots build directory: C:\Users\acon\Documents\Visual Studio 2017\Projects\Koy\platforms\android\app\snapshot-build\build
[20-01-30 13:40:22.232] (CLI) Skipping snapshot tools.
[20-01-30 13:40:22.232] (CLI) Webpack compilation complete.
[20-01-30 13:40:22.232] (CLI) Successfully generated snapshots!
[20-01-30 13:40:22.259] (CLI) Hash: 1b6fcb9913d8a18dce18
[20-01-30 13:40:22.259] (CLI) Version: webpack 4.27.1
[20-01-30 13:40:22.259] (CLI) Time: 2412ms
[20-01-30 13:40:22.259] (CLI) Built at: 01/30/2020 1:40:22 PM
[20-01-30 13:40:22.259] (CLI)                    Asset       Size  Chunks             Chunk Names
[20-01-30 13:40:22.259] (CLI)                bundle.js    171 KiB       2  [emitted]  bundle
[20-01-30 13:40:22.259] (CLI) fonts/Armata-Regular.ttf   84.2 KiB          [emitted]
[20-01-30 13:40:22.259] (CLI)    fonts/FontAwesome.ttf    162 KiB          [emitted]
[20-01-30 13:40:22.259] (CLI)  fonts/fa-brands-400.ttf    131 KiB          [emitted]
[20-01-30 13:40:22.259] (CLI) fonts/fa-regular-400.ttf   39.1 KiB          [emitted]
[20-01-30 13:40:22.259] (CLI)   fonts/fa-solid-900.ttf    204 KiB          [emitted]
[20-01-30 13:40:22.259] (CLI)             package.json  112 bytes          [emitted]
[20-01-30 13:40:22.259] (CLI)        snapshot-entry.js    114 KiB       0  [emitted]  snapshot-entry
[20-01-30 13:40:22.259] (CLI)      tns-java-classes.js    0 bytes          [emitted]
[20-01-30 13:40:22.259] (CLI)                vendor.js    927 KiB       1  [emitted]  vendor
[20-01-30 13:40:22.259] (CLI) Entrypoint bundle = snapshot-entry.js vendor.js bundle.js
[20-01-30 13:40:22.259] (CLI) Entrypoint snapshot-entry = snapshot-entry.js vendor.js
[20-01-30 13:40:22.259] (CLI)   [7] ./shared/config.js 600 bytes {2} [built]
[20-01-30 13:40:22.259] (CLI)  [24] ./shared/utils.js 926 bytes {2} [built]
[20-01-30 13:40:22.259] (CLI)  [72] ./app.scss 121 KiB {0} {2} [optional] [built]
[20-01-30 13:40:22.259] (CLI)  [77] ./app.js 1.92 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [104] ./browse/browse-view-model.js 544 bytes {2} [built]
[20-01-30 13:40:22.259] (CLI) [105] ./character/characterviewmodel.js 8.11 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [116] ./characters/charactersviewmodel.js 1.86 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [123] ./home/calendarviewmodel.js 2.87 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [125] ./login/login-viewmodel.js 2.91 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [126] ./newcharacters/newcharactersviewmodel.js 1.89 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [127] ./profile/profileviewmodel.js 3.78 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [129] ./register/registerviewmodel.js 2.97 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [130] ./search-page/search-view-model.js 554 bytes {2} [built]
[20-01-30 13:40:22.259] (CLI) [203] . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$ 1.47 KiB {2} [built]
[20-01-30 13:40:22.259] (CLI) [282] ../platforms/android/app/snapshot-entry.js 564 bytes {0} [built]
[20-01-30 13:40:22.259] (CLI)     + 272 hidden modules
[20-01-30 13:40:23.419] (CLI) Project successfully prepared (android)
[20-01-30 13:40:23.594] (CLI) cp: no such file or directory: C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\platforms\android\app\snapshot-build\build\include.gradle
[20-01-30 13:40:23.596] (CLI) shell.js: internal error
[20-01-30 13:40:23.596] (CLI) Error: ENOENT: no such file or directory, stat 'C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\platforms\android\app\snapshot-build\build\snapshots\blobs\'
[20-01-30 13:40:23.596] (CLI)     at Object.statSync (fs.js:915:3)
[20-01-30 13:40:23.596] (CLI)     at C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\node_modules\shelljs\src\cp.js:148:21
[20-01-30 13:40:23.596] (CLI)     at Array.forEach (<anonymous>)
[20-01-30 13:40:23.596] (CLI)     at Object._cp (C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\node_modules\shelljs\src\cp.js:144:13)
[20-01-30 13:40:23.596] (CLI)     at Object.cp (C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\node_modules\shelljs\src\common.js:240:23)
[20-01-30 13:40:23.596] (CLI)     at ProjectSnapshotGenerator.installSnapshotArtefacts (C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\node_modules\nativescript-dev-webpack\snapshot\android\project-snapshot-generator.js:110:17)
[20-01-30 13:40:23.596] (CLI)     at module.exports (C:\Users\acon\Documents\Visual Studio 2017\Projects\koy\node_modules\nativescript-dev-webpack\lib\after-prepare.js:16:3)
[20-01-30 13:40:23.596] (CLI)     at Yok.resolveConstructor (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:296:25)
[20-01-30 13:40:23.596] (CLI)     at Yok.resolve (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\yok.js:255:25)
[20-01-30 13:40:23.596] (CLI)     at HooksService.<anonymous> (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:118:57)
[20-01-30 13:40:23.596] (CLI)     at Generator.next (<anonymous>)
[20-01-30 13:40:23.596] (CLI)     at C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:7:71
[20-01-30 13:40:23.596] (CLI)     at new Promise (<anonymous>)
[20-01-30 13:40:23.596] (CLI)     at __awaiter (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:3:12)
[20-01-30 13:40:23.596] (CLI)     at HooksService.executeHooksInDirectory (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:87:16)
[20-01-30 13:40:23.596] (CLI)     at HooksService.<anonymous> (C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript\lib\common\services\hooks-service.js:76:45)
[20-01-30 13:40:23.611] Build failed. Communication with the child process was ended.
[20-01-30 13:40:24.054] (CLI) Using NativeScript CLI located in C:\Users\acon\AppData\Roaming\npm\node_modules\nativescript
[20-01-30 13:40:25.476] (CLI) Searching for devices...
[20-01-30 13:40:25.525] Loaded CLI extension nativescript-cloud, version 1.19.3.
[20-01-30 13:40:25.526] Loaded CLI extension nativescript-starter-kits, version 0.3.5.
[20-01-30 13:40:31.640] Devices service initialized.
[20-01-30 13:41:03.607] Checking for updates...
[20-01-30 13:41:04.583] No updates available.

**Comment by rosen-vladimirov** [comment]
Hey @alexisconsuegra ,
We've fixed a similar error in our nativescript-dev-webpack package. Can you try installing the `rc` version of the mentioned package and see if it resolves your issue:
```
npm i --save-exac --save-dev nativescript-dev-webpack@rc
```

**Comment by alexisconsuegra** [comment]
Hi @rosen-vladimirov 
I installed it and now I get a different error. "[20-02-03 21:46:51.006] Build failed. Only 8, 16, 24, or 32 bits supported: 872". Any idea? Thanks

**Comment by rosen-vladimirov** [comment]
Hey @alexisconsuegra ,
This error indicates your certificate is not a valid `.p12` file. Can you try using another `.p12` file and see if it works?

**Comment by alexisconsuegra** [comment]
Thanks Rosen. I am following the SideKick documentation "https://docs.nativescript.org/tooling/publishing/publishing-android-apps#certificates" but I do not find any reference to .p12 file. Is the documentation outdated?
