### ISSUE TITLE
Cannot properly run SideKick and build iOS application

### ISSUE THREAD

**Issue by vladikKBR85** [NativeScript/sidekick-feedback#477]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
The NativeScript SideKick application shows an error:
`[20-03-18 17:32:26.160] (Error) ab.errorHandler.shell.error - Cannot find module 'core-util-is', Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\lvm\AppData\Roaming\.nativescript-cli\extensions\node_modules\verror\lib\verror.js:9:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\lvm\AppData\Roaming\.nativescript-cli\extensions\node_modules\jsprim\lib\jsprim.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)`

and when trying to build my application-

[20-03-18 10:37:09.483] (Error) ab.childProcessCommunication.shell.cliStderr - (node:19480) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:735:23)
    at process.target.send (internal/child_process.js:634:19)
    at MessageService.sendMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\message-service.js:34:21)
    at sendMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:13:24)
    at sendErrorMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:19:9)
    at promise.then.catch (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:36:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at emitWarning (internal/process/promises.js:81:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)
(node:19480) TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:735:23)
    at process.target.send (internal/child_process.js:634:19)
    at MessageService.sendMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\message-service.js:34:21)
    at sendMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:13:24)
    at sendErrorMessage (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:19:9)
    at promise.then.catch (C:\Users\lvm\AppData\Local\NativeScriptSidekick\app-1.19.2-v201911182\resources\app.asar.unpacked\shared\child-process\child-helpers.js:36:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

[20-03-18 10:37:09.486] (Error) ab.childProcessCommunication.shell.cliStderr - (node:19480) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:95:13)
    at emitWarning (internal/process/promises.js:88:3)
    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)
    at process._tickCallback (internal/process/next_tick.js:69:34)

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

Version: 1.19.2-v.2019.11.18.2 (latest)
NativeScript CLI version: 6.4.1
CLI extension nativescript-cloud version: 1.19.3
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start the NativeScript SideKick
2. Build application using iOS configuration

### Does this issue happen every time?
Yes

### Send the client logs
[https://gist.github.com/vladikKBR85/b158d09611029e6c0c828a850ac1dc8b](https://gist.github.com/vladikKBR85/b158d09611029e6c0c828a850ac1dc8b)

**Comment by NickIliev** [comment]
@vladikKBR85 if possible please provide the content of your `package.json`

**Comment by vladikKBR85** [comment]
Of course!
`{
  "nativescript": {
    "id": "com.monitel.Sirius",
    "tns-ios": {
      "version": "6.4.0"
    },
    "tns-android": {
      "version": "6.4.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "nativescript-audio": "^5.0.4",
    "nativescript-bottom-navigation": "^2.0.5",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-imagepicker": "~7.0.0",
    "nativescript-local-notifications": "^4.2.0",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-mediafilepicker": "^3.0.1",
    "nativescript-plugin-firebase": "^10.2.1",
    "nativescript-signalr-core": "^1.0.11",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-autocomplete": "^6.0.1",
    "nativescript-ui-listview": "~7.0.0",
    "nativescript-ui-sidedrawer": "^8.0.0",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-vue": "~2.4.0",
    "nativescript-websockets": "^1.5.5",
    "tns-core-modules": "^6.2.0-next-2019-09-25-140422-01",
    "tween.js": "^16.6.0",
    "tweenjs": "^1.0.2",
    "typescript": "^3.8.3",
    "ui": "^0.2.4",
    "vue": "^2.6.11",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "~7.1.0",
    "@babel/preset-env": "~7.1.0",
    "application": "^0.1.4",
    "babel-loader": "~8.0.0",
    "dateformat": "^3.0.3",
    "nativescript-dev-webpack": "~1.5.0",
    "nativescript-fonticon": "^2.0.0",
    "nativescript-image-zoom": "^3.0.3",
    "nativescript-vue-template-compiler": "~2.4.0",
    "node-sass": "^4.7.1",
    "vue-loader": "~15.4.0"
  },
  "gitHead": "9475c272a4c74ea6baf24d578bdf46c23a400fea",
  "readme": "NativeScript Application"
}
`

**Comment by vladikKBR85** [comment]
Of course! [https://gist.github.com/vladikKBR85/b158d09611029e6c0c828a850ac1dc8b#gistcomment-3223250](https://gist.github.com/vladikKBR85/b158d09611029e6c0c828a850ac1dc8b#gistcomment-3223250)

**Comment by rosen-vladimirov** [comment]
Hey @vladikKBR85 ,
It seems there's a problem with your local installation of one of the required packages. Can you try following this steps:
1. Stop Sidekick
2. Delete `C:\Users\lvm\AppData\Roaming\.nativescript-cli\extensions` directory
3. Start Sidekick and wait while it installs required dependnecies
4. Try building again

Can you try these steps and inform us if they resolve the issue on your side?

**Comment by vladikKBR85** [comment]
Works fine. Thank you very much!

**Comment by rosen-vladimirov** [comment]
@vladikKBR85 awesome, I'm closing this thread.
