### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by surdu** [NativeScript/sidekick-feedback#48]
I get this issue every time I start the app:
```
[17-09-13 19:10:27.462] (Error) {"extensionName":"nativescript-starter-kits","extensionVersion":"0.1.16","error":{"stack":"Error: Command npm install nativescript-starter-kits@0.1.16 --save --save-exact failed with exit code 243 Error output: \n npm ERR! path /Users/nicolae.surdu/.npm/clone/2.1.1\nnpm ERR! code EACCES\nnpm ERR! errno -13\nnpm ERR! syscall mkdir\nnpm ERR! Error: EACCES: permission denied, mkdir '/Users/nicolae.surdu/.npm/clone/2.1.1'\nnpm ERR!  { Error: EACCES: permission denied, mkdir '/Users/nicolae.surdu/.npm/clone/2.1.1'\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   syscall: 'mkdir',\nnpm ERR!   path: '/Users/nicolae.surdu/.npm/clone/2.1.1',\nnpm ERR!   parent: 'node-cache' }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\n    at ChildProcess.childProcess.on (/Users/nicolae.surdu/.npm-global/lib/node_modules/nativescript/lib/node-package-manager.js:235:36)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:194:7)\n    at maybeClose (internal/child_process.js:899:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)","message":"Command npm install nativescript-starter-kits@0.1.16 --save --save-exact failed with exit code 243 Error output: \n npm ERR! path /Users/nicolae.surdu/.npm/clone/2.1.1\nnpm ERR! code EACCES\nnpm ERR! errno -13\nnpm ERR! syscall mkdir\nnpm ERR! Error: EACCES: permission denied, mkdir '/Users/nicolae.surdu/.npm/clone/2.1.1'\nnpm ERR!  { Error: EACCES: permission denied, mkdir '/Users/nicolae.surdu/.npm/clone/2.1.1'\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   syscall: 'mkdir',\nnpm ERR!   path: '/Users/nicolae.surdu/.npm/clone/2.1.1',\nnpm ERR!   parent: 'node-cache' }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n"}}
```

OS: MacOS
Versions:
```
Version: 0.2.3-v.2017.9.13.2 (latest)
NativeScript CLI version: 3.2.0
CLI extension nativescript-cloud version: 0.13.0
CLI extension nativescript-starter-kits version: 0.1.11
```

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

**Comment by ivanovit** [comment]
Hi @surdu,
NativeScript Sidekick uses npm to install some packages/dependencies. In your case, it seems that npm doesn't have permissions to write in the cache folder(~/.npm). This mostly happens when you have run npm commands with sudo. The npm command with sudo changes the permissions of all folders where it writes and you may not be able to run it again without sudo.

You should be able to fix the problem by deleting the npm cache folder ``sudo rm -rf ~/.npm`` and then start NativeScript again.

Please let us know if this fixes your issue.

**Comment by surdu** [comment]
Thanks! Solved the problem!
