### ISSUE TITLE
issue with newest sidekick update

### ISSUE THREAD

**Issue by kelinwu** [NativeScript/sidekick-feedback#50]
Hi

just let you know the new UI-Pro plug-in doesn't work well with updated sidekick. I just updated to version 3.2.1 of nativescript cli, everything was good before add UI-Pro plugin.

remove the plugin uses sidekick, doesn't solve problem too.

recreate new app without adding UI-Pro, works fine.

Thanks

**Comment by ginev** [comment]
Hello @kelinwu - could you please share some more details about this? Is there an exception? Could you please share the stack trace at the point of the exception?

**Comment by kelinwu** [comment]
Hi, here is the error,
---------------------------------
[17-09-21 21:07:28.579] (Error) Error detected during LiveSync on 05157df5d2234e2a for C:\Users\cccc\Desktop\AAA\Projects\XXX\testapp. Error: Command gradlew.bat failed with exit code 1 Error output: 
 Exception in thread "main" java.lang.IllegalArgumentException: Class com.telerik.android.common.Procedure conflict: C:\Users\cccc\Desktop\AAA\Projects\XXX\testapp\platforms\android\build\intermediates\exploded-aar\Common-2017.1.918-dev-release\jars\classes.jar and C:\Users\cccc\Desktop\AAA\Projects\XXX\testapp\platforms\android\build\intermediates\exploded-aar\Common-2017.1.914-dev-release\jars\classes.jar
	at com.telerik.metadata.ClassRepo.addToCache(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:38)
	at com.telerik.metadata.Generator.main(Generator.java:44)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_131\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
-----------------------------------------------


thanks

**Comment by tsvetie** [comment]
Hey @kelinwu, try the following:
1. Close Sidekick
2. Delete the platforms and node_modules folders from the root of your application
3. Start Sidekick, open the project and execute Run -> Run on device again

**Comment by meshmmanuel** [comment]
Not working yet.

Error detected during live sync
[17-10-26 23:32:32.320] (Error) Error detected during LiveSync on 82883879cdb****  for /Users/*******/Desktop/NativeScript/DemoApp. Error: PKCS#12 MAC could not be verified. Invalid password?
 DEVICES 1  OUTPUT 1

**Comment by tsvetie** [comment]
@meshmmanuel can you give us more information about your case? For example, steps to reproduce and logs? The log files are situated here:

**Comment by denislearni** [comment]
i am having the same problem

**Comment by tsvetie** [comment]
@denislearni can you give me move information about the problem? E.g. steps to reproduce, log files, versions of NS CLI, node, npm, anything else you think will help us detect the problem?

**Comment by Bhargav79** [comment]
[17-12-22 00:30:20.435] (Error) Error detected during LiveSync on f95679b5482508388599eff36ab92620fb0c0067 for B:\..\mobile\...NativeScript. Error: The specified provision's (C:\Users\kbkr\AppData\Roaming\NativeScriptSidekick\CodeSigning\..\ios\provision.mobileprovision) application identifier (org.nativescript.totalBash) doesn't match your project's application identifier (org.nativescript.totalbash).

**Comment by ggarabedian** [comment]
Hello everyone,

I’m closing this issue because it has been inactive for a long time and the original problem seems to be resolved. If any you continue to experience any of the reported problems with the latest version of Sidekick, please open a new issue and fill the template with information relevant to your case.

Thank you!

**Comment by anasvn** [comment]
It due to denying the app installation permission in your mobile. Allow USB installation in developer option to overcome this issue.
