### ISSUE TITLE
Login Exception: Cannot read property 'ExceptionMessage' of null

### ISSUE THREAD

**Issue by StevenLJackson1** [NativeScript/sidekick-feedback#64]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I try to log in behind our corporate proxy, I get the following exception:

```
[17-10-11 13:16:50.769] (Error) The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null, Error: The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null
    at ClientRequest.onError (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\nativescript\node_modules\tunnel-agent\index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
We have had issues before using `appbuilder` with our authenticating proxy, and I'm wondering if this is a similar issue.  We need to provide authentication information so that the proxy will let us through to the outside world.

### Which platform(s) does the issue occur on?
Windows 7

### Provide the following version numbers that the issue occurs with:
Version: 0.2.5-v.2017.9.27.4 (latest)
NativeScript CLI version: 3.2.1
CLI extension nativescript-cloud version: 0.13.0
CLI extension nativescript-starter-kits version: 0.1.16

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application
2. Click "Login"

### Does this issue happen every time?
Yes

### Send the client logs.
All I see in the most recent log files is:

```
Using NativeScript CLI located in C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\nativescript
Searching for devices...
iTunes is not installed. Install it on your system and run this command again.
```

**Comment by rosen-vladimirov** [comment]
Hey @StevenLJackson1 ,
In case you are working behind a proxy, you should set it for NativeScript CLI via:
```
$ tns proxy set <url>[<username> [<password>]]
```
For example:
```
$ tns proxy set http://127.0.0.1:8888
```

You can find more information for this command by executing:
```
$ tns help proxy set
```

Also, in case you want to use local Android builds, you may have to set the proxy for your gradle calls. More information can be found [here](https://docs.gradle.org/3.3/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy).

Can you please try using the mentioned command and inform us if it helps?

**Comment by StevenLJackson1** [comment]
I was pretty sure that I had already set the proxy for the `tns` command, so I checked it:
```
> tns proxy
Proxy Url: http://...
Username: xxx
Proxy is Enabled
```
Next I did a `tns login`, and successfully logged in via the web page that popped up, thinking that Sidekick might use the same login information that `tns` persists.  However, when I opened Sidekick again I still got the same error.

Here are all of the messages I see when starting the app (not just the error) in case anything else in here helps:
```
[17-10-11 20:20:45.857] (Info) Version: 0.2.5-v.2017.9.27.4
[17-10-11 20:20:45.974] (Info) Checking for updates...
[17-10-11 20:20:49.842] (Info) No updates available.
[17-10-11 20:20:51.397] (Info) Dependencies versions: NodeJS: 6.9.2, npm: 5.4.1, NativeScript CLI: 3.2.1.
[17-10-11 20:20:53.401] (Info) Loaded CLI extension nativescript-cloud, version 0.13.0.
[17-10-11 20:20:53.404] (Info) Loaded CLI extension nativescript-starter-kits, version 0.1.16.
[17-10-11 20:20:55.488] (Info) Devices service initialized.
[17-10-11 20:21:01.731] (Error) The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null, Error: The server returned unexpected response: TypeError: Cannot read property 'ExceptionMessage' of null
    at ClientRequest.onError (C:\Users\sxj112\AppData\Roaming\npm\node_modules\nativescript\node_modules\tunnel-agent\index.js:177:17)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Notice that there is about a 2 second delay between the app coming into view (i.e., no splash screen any more) and the error popping up--possibly a timeout condition?

Thanks again!

**Comment by rosen-vladimirov** [comment]
Hey @StevenLJackson1 ,
You are correct in your assumption that `tns login` and Sidekick share the login information. I'm not sure exactly which call failed on your side. I've tried to reproduce the behavior by using a system wide proxy (on Windows 10), but without success. After that I've tried using `https` proxy with invalid certificate and I received an error similar to yours. Can you check if you have System proxy and its certificate is valid?
Meanwhile, in order to investigate the issue further, may I ask you to execute the following:
1. Navigate to Sidekick logs directory:
```
Windows: %AppData%\NativeScriptSidekick\Logs
macOS: ~/Library/Application Support/NativeScriptSidekick/Logs
Linux: ~/.config/NativeScriptSidekick/Logs
```
2. Delete all logs
3. Ensure you have set the proxy configuration for NativeScript and npm
3.1 `$ tns proxy` - already verified from your previous version
3.2 `$ npm config get proxy` (in case it is not set, please set it via `npm config set proxy`)
3.3 `$ npm config get https-proxy` (in case it is not set, please set it via `npm config set https-proxy`)
4. Open Sidekick
5. When the login fails, zip the files in the Logs and send them to us.

I'm looking forward to hearing from you.

**Comment by StevenLJackson1** [comment]
As it turns out, I had a typo in my tns proxy URL.  I fixed it and now I see that I am logged in to Sidekick.

Thanks for your help!
