### ISSUE TITLE
Unable to create new page, Version: 0.2.7-v.2017.10.26.3 (latest)

### ISSUE THREAD

**Issue by shiv19** [NativeScript/sidekick-feedback#78]
```
[17-10-30 22:18:56.636] (Error) Communication with the child process was ended. Errors: events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm.cmd ENOENT
    at exports._errnoException (util.js:1028:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[17-10-30 22:18:56.639] (Error) Communication with the child process was ended. Errors: events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm.cmd ENOENT
    at exports._errnoException (util.js:1028:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rosen-vladimirov** [comment]
@shiv19 can you give information about your operating system, Node.js version and npm version, i.e.:
* output of `node --version`
* output of `npm --version`
* logs located at `~/Library/Application Support/NativeScriptSidekick/Logs`

**Comment by shiv19** [comment]
Logs:
[Logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1428028/Logs.zip)

npm 3.10.10
node 7.6.0

**Comment by rosen-vladimirov** [comment]
Hey @shiv19 , 
Can you send us the output of the following command, please execute in terminal:
```
node -e "console.log(process.platform)"
```

**Comment by shiv19** [comment]
`darwin`

MacBook Pro 13", HighSierra

**Comment by tsvetie** [comment]
@shiv19 , this is a bug and we will fix it in the next update

**Comment by shiv19** [comment]
@tsvetie alrighty. Thank you! 😃

**Comment by toddanglin** [comment]
Same problem here.

Version: 0.2.7-v.2017.10.26.3 (latest)
NativeScript CLI version: 3.3.0
CLI extension nativescript-cloud version: 0.16.0
CLI extension nativescript-starter-kits version: 0.3.1

Is there any workaround to manually create new pages from these templates while we wait on the bug patch?

**Comment by tsvetie** [comment]
The fix is already released. And better late then never - there was no workaround.

**Comment by shiv19** [comment]
@tsvetie thanks, it works perfectly now
