### ISSUE TITLE
Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by laimonas** [NativeScript/sidekick-feedback#99]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When starting i get error : Cannot find module 'tough-cookie', Error: Cannot find module 'tough-cookie' 
After application started, i'm trying to create project, but "project type" is not active, in older versions i can choose from angular, typesript and js projects.

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 1.0.1
- **NativeScript CLI:** 3.3.1
- **CLI extension nativescript-cloud:** 1.0.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Does this issue happen every time?
Yes

### Send the client logs.
[17-11-29 18:01:16.501] (Error) ab.errorHandler.shell.error - Cannot find module 'tough-cookie', Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\request-promise-native\lib\rp.js:11:5
    at module.exports (C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\stealthy-require\lib\index.js:38:9)
    at Object.<anonymous> (C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\request-promise-native\lib\rp.js:7:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
[17-11-29 18:01:16.526] (Error) ab.errorHandler.shell.error - Cannot find module 'tough-cookie', Error: Cannot find module 'tough-cookie'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\request-promise-native\lib\rp.js:11:5
    at module.exports (C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\stealthy-require\lib\index.js:38:9)
    at Object.<anonymous> (C:\Users\lma\AppData\Roaming\.nativescript-cli\extensions\node_modules\request-promise-native\lib\rp.js:7:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by tsvetie** [comment]
Hey @laimonas,

Can you try the following to see if it will fix the problem:

1. delete the extensions folder in

```
C:\Users\lma\AppData\Roaming\.nativescript-cli
```
2. start Sidekick again

In case the problem persists, can you send me all log files that were created - you should have a main, cli, console and fsw log files, situated here:

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

The best approach is to delete the files in the Logs folder, start Sidekick and wait for the error notification, close Sidekick and send me the newly created files.

**Comment by laimonas** [comment]
Hi,
I have deleted  this folder and now everything is working correct.
Hope this will not happen after next updated. Because reinstalling applications is not solving this issue.
